fix(route): 修正南京大学本科生院教学信息网信息获取
DIYgod/RSSHub pull request #10749
Opened 2022-09-08 17:50 UTC by cqjjjzr

## 该 PR 相关 Issue / Involved issue

（无）

## 完整路由地址 / Example for the proposed route(s)

```routes
/nju/jw/ggtz
/nju/jw/jxdt
```

## 说明 / Note

将 HTML 解释改为利用 WebPlus 的 REST 接口。通过自定义 `returnInfos` 可以实现 返回格式的自定义，特别是可以获取时间信息。增大每次返回条目数。

2022-09-08 18:02 UTC, cqjjjzr commented
CC @ret-1

2022-09-09 09:17 UTC, TonyRL reviewed
Please update maintainer.js as well.

2022-09-09 10:44 UTC, TonyRL requested changes
This API endpoint is returning outdated feeds.
Please cross-check with https://jw.nju.edu.cn/ggtz/list.htm and https://jw.nju.edu.cn/_s414/24774/list.psp

2022-09-09 11:37 UTC, cqjjjzr commented
I don't think so. As I mentioned before, you should pull the feed with `sorted=false` since the returned 

However, I noticed the search order (in the search criteria) and time parsing are wrong. Pushed to fix.

2022-09-09 11:51 UTC, TonyRL commented on lib/v2/nju/jw.js
> +        link: `https://jw.nju.edu.cn/${type_dict[type][0]}/list.htm`,
https://jw.nju.edu.cn/26263/list.htm will not work, it should be https://jw.nju.edu.cn/ggtz/list.htm

2022-09-09 14:26 UTC, merged