fix(route): Anti-Anti-Spider 哔哩哔哩
DIYgod/RSSHub pull request #10886
Opened 2022-09-24 14:00 UTC by cyx20080216

## 该 PR 相关 Issue / Involved issue

#10511

## 完整路由地址 / Example for the proposed route(s)

```routes
/bilibili/user/video/335098315
/bilibili/user/video-all/335098315
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [ ] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note
这个 PR 试图通过在调用哔哩哔哩API之前访问`https://www.bilibili.com/`获得Cookie，并携带Cookie访问会使该API被调用的页面，最后携带Cookie访问API来反反爬虫

2022-09-25 11:13 UTC, sqliuchang commented
实测这个PR可以正常抓取，运行了8小时了，没再出现用户名undefined了

2022-09-26 20:32 UTC, TonyRL requested changes

2022-09-26 20:32 UTC, TonyRL commented on lib/v2/bilibili/cache.js
> +        const key = 'cookie';
Please pick another cache key name like `bilibili:cookie`

2022-09-26 20:32 UTC, TonyRL commented on lib/v2/bilibili/cache.js
> +        let cookie = await ctx.cache.get(key);
Please use `cache.tryGet`

2022-09-26 20:32 UTC, TonyRL commented on lib/v2/bilibili/cache.js
> +                url: `https://www.bilibili.com/`,
Why use template literals when there's no expression

2022-09-26 20:32 UTC, TonyRL commented on lib/v2/bilibili/cache.js
> +const UA = require('@/utils/rand-user-agent')({ browser: 'chrome', os: 'windows', device: 'desktop' });
Does UA really matter since RSSHub is using `{ browser: 'chrome', os: 'mac os', device: 'desktop' }` by default

2022-09-26 20:32 UTC, TonyRL commented on lib/v2/bilibili/cache.js
> +                url: `https://space.bilibili.com/${uid}/`,
got request can be simplified
```suggestion
            await got(`https://space.bilibili.com/${uid}/`, {
```

2022-09-26 20:32 UTC, TonyRL commented on lib/v2/bilibili/cache.js
> +        let name = await ctx.cache.get(key);
Please use `cache.tryGet`

2022-09-26 20:32 UTC, TonyRL commented on lib/v2/bilibili/cache.js
> +                url: `https://space.bilibili.com/${uid}/`,
```suggestion
            await got(`https://space.bilibili.com/${uid}/`, {
```

2022-09-26 20:32 UTC, TonyRL commented on lib/v2/bilibili/video.js
> +        method: 'get',
got request can be simplified

2022-09-27 13:59 UTC, cyx20080216 commented on lib/v2/bilibili/video.js
> +        url: `https://space.bilibili.com/${uid}/video?tid=0&page=1&keyword=&order=pubdate`,
I think we should use raw API format because browsers don't use the simplified format and it may become a reason to ban the spider.

2022-09-27 14:08 UTC, TonyRL commented on lib/v2/bilibili/video.js
> +        url: `https://space.bilibili.com/${uid}/video?tid=0&page=1&keyword=&order=pubdate`,
https://github.com/sindresorhus/got/blob/main/documentation/1-promise.md#promise-api

This is semantically **the same** as the first approach.

In fact, even your PR includes both <code>got(url: string | URL, options?: [OptionsInit](typescript.md#optionsinit), defaults?: [Options](2-options.md))</code> and <code>got(options: [OptionsInit](typescript.md#optionsinit))</code>

https://github.com/DIYgod/RSSHub/blob/de6dc376e38aba481f00efe98e6e8786d641d9d6/lib/v2/bilibili/video-all.js#L32-L38

https://github.com/DIYgod/RSSHub/blob/de6dc376e38aba481f00efe98e6e8786d641d9d6/lib/v2/bilibili/cache.js#L9-L15

2022-09-27 14:12 UTC, cyx20080216 commented on lib/v2/bilibili/video.js
> +        url: `https://space.bilibili.com/${uid}/video?tid=0&page=1&keyword=&order=pubdate`,
Sorry, you may misunderstand what I mean. I means the URL to call the API of Bilibili.

2022-09-27 15:03 UTC, TonyRL commented on lib/v2/bilibili/cache.js
> +                    'User-Agent': config.UA
No need to set UA again as it's already set in `lib/utils/got`
https://github.com/DIYgod/RSSHub/blob/3e6f0542c2ae51e9650376f4c435c109e548a85d/lib/utils/got.js#L33-L35

2022-09-28 03:08 UTC, raining1123 commented
请问更新到最新版本后，还需要手动在env里填写SESSDATA吗？

2022-09-28 13:41 UTC, cyx20080216 commented
> 请问更新到最新版本后，还需要手动在env里填写SESSDATA吗？

需要，这个Cookie是用于标识未登录用户身份的，不能获取您账户中的信息

2022-09-28 14:11 UTC, merged