feat(route): add Uber Engineering Blog
DIYgod/RSSHub pull request #11106
Opened 2022-10-17 13:27 UTC by hulb

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/uber/blog
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [x] 新的路由 New Route
  - [x] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [x] 文档说明 Documentation
  - [x] 中文文档 CN
  - [x] 英文文档 EN
- [x] 全文获取 fulltext
  - [x] 使用缓存 Use Cache
- [x] 反爬/频率限制 anti-bot or rate limit?
  - [x] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [x] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note
The source site uses strict anti-scraping policy. I only use asyncPool to bypass it, but there is possibility that some articles are not full-text scrapped.

2022-10-17 14:10 UTC, TonyRL reviewed
Since this is a WordPress-based site. Have you tried its API yet?
i.e., https://blogapi.uber.com/wp-json/blog/v1/data?page=1&parent=pittsburgh&slug=engineering and https://blogapi.uber.com/wp-json/blog/v1/data?slug=introducing-workflowguard

2022-10-27 19:19 UTC, TonyRL requested changes

2022-10-27 19:19 UTC, TonyRL commented on lib/v2/uber/radar.js
> +    'www.uber.com': {
You need to specify the root domain only.
```suggestion
    'uber.com': {
```

2022-10-27 19:19 UTC, TonyRL commented on lib/v2/uber/maintainer.js
> +    '/uber/blog': ['hulb'],
The key here **MUST** match the path in `router.js`

2022-11-03 13:43 UTC, hulb commented on docs/en/blog.md
> +<Route author="hulb" example="/uber/blog" path="/uber/blog/:maxPage" />
> * `path` should be `/uber/blog/:maxPage?` according to `lib/v2/uber/router.js`

Actually yes, but I don't want to expose this parameter.I don't think it's useful for everyone.I make it for myself.

2022-11-03 13:44 UTC, hulb commented on docs/blog.md
> +<Route author="hulb" example="/uber/blog" path="/uber/blog/:maxPage" />
Actually yes, but I don't want to expose this parameter.I don't think it's useful for everyone.I make it for myself.

2022-11-03 13:46 UTC, hulb commented
Thank you for reviewing. I need a while to modify to make it look good.

2022-11-06 14:15 UTC, hulb commented on lib/v2/uber/blog.js
> +const got = require('@/utils/got');
Thanks for the detailed guidance

2022-11-06 14:34 UTC, hulb commented on lib/v2/uber/radar.js
> +                docs: 'https://docs.rsshub.app/blog.html#you-bu',
I'm not sure whether this doc link is correct

2022-11-06 14:37 UTC, hulb commented on lib/v2/uber/radar.js
> +                docs: 'https://docs.rsshub.app/blog.html#you-bu',
I have made some updates according to the comments. Let me known if mistakes exist. Thanks again.

2022-11-06 14:37 UTC, hulb commented
I have made some updates according to the comments. Let me known if mistakes exist. Thanks again.

2022-11-06 15:03 UTC, TonyRL commented on docs/blog.md
> +<Route author="hulb" example="/uber/blog/:maxPage?" path="/uber/blog/:maxPage?" :paramsDesc="['获取的最多页数，默认最多获取第一页']" />
```suggestion
<Route author="hulb" example="/uber/blog" path="/uber/blog/:maxPage?" :paramsDesc="['获取的最多页数，默认最多获取第一页']" />
```

2022-11-06 15:03 UTC, TonyRL commented on docs/en/blog.md
> +<RouteEn author="hulb" example="/uber/blog/:maxPage?" path="/uber/blog/:maxPage?" :paramsDesc="['max number of pages to retrieve, default to 1 page at most']" />
```suggestion
<RouteEn author="hulb" example="/uber/blog" path="/uber/blog/:maxPage?" :paramsDesc="['max number of pages to retrieve, default to 1 page at most']" />
```

2022-11-06 15:03 UTC, TonyRL commented on lib/v2/uber/radar.js
> +                title: 'Uber Blog - Engineering',
```suggestion
                title: 'Engineering',
```
No need to repeat `_name`

2022-11-06 15:20 UTC, merged