feat[route]: 新增广州市人民政府
DIYgod/RSSHub pull request #11339
Opened 2022-11-28 01:16 UTC by drgnchan

## 该 PR 相关 Issue / Involved issue

## 完整路由地址 / Example for the proposed route(s)

```routes
/gzgov/xw/gzyw
/gzgov/xw/jrtt
/gzgov/xw/tzgg
/gzgov/zwgk/zcjd
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [x] 新的路由 New Route
  - [x] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [x] 文档说明 Documentation
  - [x] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [x] 可以解析 Parsed
  - [x] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note

2022-11-28 06:04 UTC, TonyRL requested changes
Please place `gov`-related route inside `gov` folder

2022-11-28 07:23 UTC, drgnchan commented
> Please place `gov`-related route inside `gov` folder

I have finished that.

2022-11-28 08:42 UTC, TonyRL requested changes

2022-11-28 08:42 UTC, TonyRL commented on lib/v2/gov/router.js
> +    router.get('/gzgov/:channel/:category', require('./gzgov/index'));
- The domain name is `gz` please use that instead.
- Please help maintain entries in this file in alphabetical order

2022-11-28 16:18 UTC, TonyRL commented on lib/v2/gov/gz/index.js
> +        title: `广州市人民政府 - ${categoryMap[category]}`,
You can extract the page title using
```suggestion
        title: `广州市人民政府 - ${$('.main_title').text()}`,
```
In this way, there's no need to update the entries in `categoryMap` above.

2022-11-28 16:18 UTC, TonyRL commented on lib/v2/gov/gz/index.js
> +
```suggestion
```

2022-11-28 23:55 UTC, drgnchan commented
@TonyRL Thanks a lot.All done.

2022-12-06 09:53 UTC, drgnchan commented
@TonyRL hi,can you review if you have time to?

2022-12-06 14:05 UTC, TonyRL reviewed
Missing respective updates for `maintainer.js` and `radar.js`

2022-12-06 14:05 UTC, TonyRL commented on docs/government.md
> +<Route author="drgnchan" example="/gov/gz/xw/gzyw" path="/gov/gz/xw/:category">
Missing `:paramsDesc` attributes

2022-12-06 14:05 UTC, TonyRL commented on docs/government.md
> +<Route author="drgnchan" example="/gov/gz/zwgk/zcjd" path="/gov/gz/zwgk/:category">
Missing `:paramsDesc` attributes

2022-12-07 17:15 UTC, merged