add(route): 增加浙江中医药大学教务处
DIYgod/RSSHub pull request #11579
Opened 2023-01-08 15:50 UTC by CCraftY

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```
/zcmu/jwc/1
/zcmu/jwc/2
/zcmu/jwc/3
/zcmu/jwc/4
/zcmu/jwc/5
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [x] 新的路由 New Route
  - [x] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [x] 文档说明 Documentation
  - [x] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note

2023-01-08 16:02 UTC, CCraftY commented
routes标识已修正 @NeverBehave

2023-01-08 21:44 UTC, NeverBehave commented
LGTM

2023-01-09 12:29 UTC, TonyRL commented on docs/university.md
> +### 浙中医大教务处
```suggestion
### 教务处
```

2023-01-09 12:29 UTC, TonyRL commented on docs/university.md
> +<Route author="CCraftY" example="zcmu/jwc/1" path="zcmu/jwc/:type?" :paramsDesc="['通知模块id']">
```suggestion
<Route author="CCraftY" example="/zcmu/jwc/1" path="/zcmu/jwc/:type?" :paramsDesc="['通知模块id']">
```

2023-01-09 12:29 UTC, TonyRL commented on lib/v2/zcmu/radar.js
> +                title: '浙江中医药大学',
```suggestion
                title: '教务处',
```

2023-01-09 23:49 UTC, CCraftY commented
updated

2023-01-10 12:54 UTC, TonyRL requested changes
Every item has its `pubDate`. Please add it as well.

2023-01-11 09:51 UTC, merged