feat(route): add mixcloud
DIYgod/RSSHub pull request #11672
Opened 2023-01-23 10:13 UTC by Misaka13514

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/mixcloud/dholbach
/mixcloud/dholbach/uploads
/mixcloud/dholbach/favorites
/mixcloud/dholbach/listens
/mixcloud/FirstEar/stream
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [x] 新的路由 New Route
  - [x] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [x] 文档说明 Documentation
  - [x] 中文文档 CN
  - [x] 英文文档 EN
- [x] 全文获取 fulltext
  - [x] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [x] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [x] `Puppeteer`

## 说明 / Note

添加 Mixcloud

似乎没有音频直链，所以没有`enclosure`。相对日期不精确。

2023-01-23 13:12 UTC, TonyRL requested changes
Why use puppeteer? Everything can be queried through their GraphQL endpoint.

2023-01-27 14:01 UTC, TonyRL commented on lib/v2/mixcloud/index.js
> +            query: 'query UserStreamQuery(\n  $lookup: UserLookup!\n) {\n  user: userLookup(lookup: $lookup) {\n    username\n    ...UserStreamPage_user\n    id\n  }\n  viewer {\n    ...UserStreamPag
You can put query string in template literals so that the indentation can be kept and is more readable

2023-01-27 14:02 UTC, TonyRL commented on docs/en/multimedia.md
> +<RouteEn author="Misaka13514" example="/mixcloud/dholbach/uploads" path="/mixcloud/:username/:type?" :paramsDesc="['Username, can be found in URL', 'Type, see below, uploads by default']" radar="1" r
```suggestion
<RouteEn author="Misaka13514" example="/mixcloud/dholbach/uploads" path="/mixcloud/:username/:type?" :paramsDesc="['Username, can be found in URL', 'Type, see below, uploads by default']" radar="1" rssbud="1" supportPodcast="1">
```

2023-01-27 14:02 UTC, TonyRL commented on docs/multimedia.md
> +<Route author="Misaka13514" example="/mixcloud/dholbach/uploads" path="/mixcloud/:username/:type?" :paramsDesc="['用户名，可在对应用户页 URL 中找到', '分类，见下表，默认为 uploads']" radar="1" rssbud="1">
```suggestion
<Route author="Misaka13514" example="/mixcloud/dholbach/uploads" path="/mixcloud/:username/:type?" :paramsDesc="['用户名，可在对应用户页 URL 中找到', '分类，见下表，默认为 uploads']" radar="1" rssbud="1" supportPodcast="1">
```

2023-01-27 15:03 UTC, merged

2023-01-27 15:04 UTC, Misaka13514 commented
@TonyRL Thanks for your help