fix(route): blockbeats
DIYgod/RSSHub pull request #11713
Opened 2023-01-28 06:50 UTC by jameshih

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/blockbeats/newsflash
/blockbeats/article
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [ ] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note

2023-01-28 10:41 UTC, TonyRL commented
Please remove any changes on yarn.lock unless you add a new package

2023-01-30 12:24 UTC, TonyRL requested changes
Those feeds are still returning empty items

2023-01-30 12:29 UTC, TonyRL reviewed
You can use API endpoints instead of looking at the HTML
https://api.theblockbeats.info/v3/newsflash/select
https://api.theblockbeats.info/v3/Information/newsall

2023-02-04 12:04 UTC, TonyRL commented on lib/v2/blockbeats/index.js
>          .get();
This needs to be resolved before merging.

2023-02-05 01:40 UTC, jameshih commented on lib/v2/blockbeats/index.js
>          .get();
Working on it

2023-02-05 11:14 UTC, merged