feat(route): add 6vdy
DIYgod/RSSHub pull request #11907
Opened 2023-02-19 07:57 UTC by tc9011

## 该 PR 相关 Issue / Involved issue

### 类型
社交媒体

### 网站地址
http://www.hao6v.cc/
http://www.hao6v.com/
http://www.hao6v.tv/

### 网站描述
6v 电影是一个电影爱好者交流网站，提供最新的电影和电视剧的下载。

### 需要生成什么内容？
音视频

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/6vdy/latestMovies
/6vdy/latestTVSeries
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [x] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [x] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [x] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [x] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note

2023-02-19 10:22 UTC, TonyRL requested changes

2023-02-19 10:22 UTC, TonyRL commented on lib/v2/6vdy/maintainer.js
> +    '/6vdy/latestTVSeries': ['tc9011'],
```suggestion
    '/latestMovies': ['tc9011'],
    '/latestTVSeries': ['tc9011'],
```

2023-02-19 10:22 UTC, TonyRL commented on lib/v2/6vdy/utils.js
> +        const cache = await ctx.cache.get(link);
Please use `ctx.cache.tryGet` instead

2023-02-19 10:22 UTC, TonyRL commented on lib/v2/6vdy/utils.js
> +                };
Please cache the whole returned object instead

2023-02-19 14:19 UTC, TonyRL commented on lib/v2/6vdy/utils.js
> +                    };
Please cache these statements instead of the list. Otherwise, the list will never be updated after the cache is fetched.

2023-02-19 14:21 UTC, TonyRL commented on lib/v2/6vdy/radar.js
> +        ],
You can create a variable for these entries instead of copy-pasting them 3 three times

2023-02-22 06:11 UTC, TonyRL commented on lib/v2/6vdy/utils.js
> +                        }));
Do not remove `link` since users won't be able to open the web page after that

2023-02-23 11:39 UTC, merged

2023-02-24 02:13 UTC, tc9011 commented
Hey, @TonyRL  thanks for reviewing, and May I ask why changed the route path from `6vdy` to `6v123 `?

2023-02-24 05:29 UTC, TonyRL commented
Site URL is released from `https://www.6v123.net`