重新支持获取文章正文
DIYgod/RSSHub pull request #12039
Opened 2023-03-04 17:11 UTC by lin1005q

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
NOROUTE
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [ ] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note
接口变更，继续支持

2023-03-04 17:18 UTC, lin1005q commented
@DIYgod

2023-03-04 19:11 UTC, TonyRL requested changes
Do not use `NOROUTE` for route related changes

2023-03-06 12:45 UTC, TonyRL commented on lib/v2/infoq/utils.js
> +                const content1 = data.content_url ? (await got.get(data.content_url)).body : data.content;
```suggestion
                const content = data.content_url ? (await got(data.content_url)).body: data.content;
```

2023-03-06 12:45 UTC, TonyRL commented on lib/v2/infoq/utils.js
> +                    description: parseContent(content1),
```suggestion
                    description: parseContent(content),
```

2023-03-06 14:01 UTC, merged