feat(route): the atlantic
DIYgod/RSSHub pull request #12092
Opened 2023-03-12 22:42 UTC by NavePnow

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/theatlantic/latest
/theatlantic/technology
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [x] 新的路由 New Route
  - [x] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [x] 文档说明 Documentation
  - [x] 中文文档 CN
  - [x] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note

2023-03-13 12:24 UTC, TonyRL requested changes

2023-03-13 14:24 UTC, NavePnow commented on lib/v2/theatlantic/news.js
> +    const items = await asyncPoolAll(1, list, (item) => parseArticle(item, ctx));
lol i reused that code block from wsj in case they will take it in the future.

2023-03-14 13:47 UTC, TonyRL commented on lib/v2/theatlantic/utils.js
> +                item.imgCaption = data.leadArt.image.attributionText;
```suggestion
                item.imgUrl = data.leadArt.image?.url;
                item.imgAlt = data.leadArt.image?.altText;
                item.imgCaption = data.leadArt.image?.attributionText;
```

2023-03-14 13:47 UTC, TonyRL commented on lib/v2/theatlantic/templates/article-description.art
> +    </figure>
```suggestion
    {{ if item.imgUrl }}
    <figure>
        <img src="{{item.imgUrl}}" alt="{{item.imgAlt}}">
        <figcaption>{{item.imgCaption}}</figcaption>
    </figure>
    {{ /if }}
```

2023-03-14 17:37 UTC, merged

2024-08-18 02:05 UTC, Vikramnaik143 commented on docs/en/traditional-media.md
> +<RouteEn author="NavePnow" example="/theatlantic/latest" path="/theatlantic/:category" :paramsDesc="['category', 'see below']">
mobile camera hacking processor