fix(route): 重新适配了CUG的各类网站-网站改版
DIYgod/RSSHub pull request #12739
Opened 2023-07-02 07:27 UTC by Doradx

## 该 PR 相关 Issue / Involved Issue

Close #

## 路由地址示例 / Example for the Proposed Route(s)

```routes
/cug/news
/cug/graduate
/cug/gcxy/0
/cug/gcxy/1
/cug/gcxy/2
/cug/gcxy/3
/cug/gcxy/4
/cug/gcxy/5
/cug/gcxy/6
```

## 新 RSS 路由检查表 / New RSS Route Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [x] 文档说明 Documentation
  - [x] 中文文档 CN
  - [ ] 英文文档 EN
- [x] 全文获取 fulltext
  - [x] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [x] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note
由于网站改版，之前的规则无法适应，故重新适配，并优化代码。

2023-07-04 14:22 UTC, TonyRL commented on lib/routes/universities/cug/gcxy/index.js
> +        type = parseInt(type);
The type of path variable will be either `String` or `undefined`. It won't be a `Number`.
docs: https://docs.rsshub.app/joinus/new-rss/before-start.html

2023-07-04 14:22 UTC, TonyRL commented on lib/routes/universities/cug/gcxy/index.js
> +                        description: '',
```suggestion
```

2023-07-04 14:22 UTC, TonyRL commented on lib/routes/universities/cug/gcxy/index.js
> +                            const result = await got.get(String(element.link));
https://github.com/DIYgod/RSSHub/blob/4fea5c788a5bf1c63f97122e930cd463421c87ee/lib/routes/universities/cug/gcxy/index.js#L73
`.href` returns a `String`. Don't recast the same type.
docs: https://nodejs.org/api/url.html#urlhref
https://docs.rsshub.app/joinus/script-standard.html

2023-07-04 14:22 UTC, TonyRL commented on lib/routes/universities/cug/gcxy/index.js
> +                            const result = await got.get(String(element.link));
Please stick with one convention only.
Either
https://github.com/DIYgod/RSSHub/blob/4fea5c788a5bf1c63f97122e930cd463421c87ee/lib/routes/universities/cug/gcxy/index.js#L58-L64
or
https://github.com/DIYgod/RSSHub/blob/4fea5c788a5bf1c63f97122e930cd463421c87ee/lib/routes/universities/cug/gcxy/index.js#L84

2023-07-04 14:22 UTC, TonyRL commented on docs/university.md
> +<Route author="Dorad" example="/cug/gcxy/0" path="/cug/gcxy/:type" />
Since the previous example works, I don't see the necessity of changing this.

2023-07-25 14:44 UTC, TonyRL reviewed
https://github.com/DIYgod/RSSHub/pull/12739#discussion_r1251287700
https://github.com/DIYgod/RSSHub/pull/12739#discussion_r1251289177
https://github.com/DIYgod/RSSHub/pull/12739#discussion_r1252054154
https://github.com/DIYgod/RSSHub/pull/12739#discussion_r1252063672
https://github.com/DIYgod/RSSHub/pull/12739#discussion_r1252088515
https://github.com/DIYgod/RSSHub/pull/12739#discussion_r1252090801
https://github.com/DIYgod/RSSHub/pull/12739#discussion_r1252094271

2023-08-01 02:34 UTC, Doradx reviewed
all comments have been reviewed and resolved.

2023-08-01 11:44 UTC, TonyRL requested changes

2023-08-01 11:44 UTC, TonyRL commented on lib/routes/universities/cug/gcxy/index.js
> +                        description: '',
Please explain how setting an empty property `description: ''` can help converting relative path to absolute path.

2023-08-01 11:44 UTC, TonyRL commented on lib/routes/universities/cug/gcxy/index.js
> +                            const result = await got.get(String(element.link));
Please explain how recasting `element.link` **from `string` to `string`** can help converting relative path to absolute path.

2023-08-01 11:44 UTC, TonyRL commented on lib/routes/universities/cug/graduate.js
> +                    const result = await got.get(element.link);
This is not fixed at all.

2023-08-01 11:44 UTC, TonyRL commented on lib/routes/universities/cug/news.js
> +                    const result = await got.get(element.link);
This is not fixed at all.

2023-09-01 23:32 UTC, closed without merging