修改官网地址错误
DIYgod/RSSHub pull request #5791
Opened 2020-10-04 06:02 UTC by Qifcn

官网更新加了www二级域名

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

2020-10-05 13:59 UTC, HenryQW requested changes

2020-10-05 13:59 UTC, HenryQW commented on lib/router.js
> +router.get('/scvtc/xyxw', require('./routes/universities/scvtc/xyxw/xyxw'));
这个错了吧？

2020-10-05 13:59 UTC, HenryQW commented on lib/router.js
> +router.get('/scvtc/xyxw', require('./routes/universities/scvtc/xyxw/xyxw'));
直接用 `scvtc/xyxw` 就好了，下面的路由也是

2020-10-05 13:59 UTC, HenryQW requested changes

2020-10-05 13:59 UTC, HenryQW commented on docs/university.md
> +<Route author="nczitzk" example="/scvtc/xyxw" path="/scvtc/xyxw" />
作者没改

2020-10-05 18:18 UTC, Qifcn commented on lib/router.js
> +router.get('/scvtc/xyxw', require('./routes/universities/scvtc/xyxw/xyxw'));
你好，我在本地测试scvtc/xyxw不通过，没法启动服务，scvtc/xyxw/xyxw反而可行

2020-10-05 18:20 UTC, Qifcn commented on docs/university.md
> +<Route author="nczitzk" example="/scvtc/xyxw" path="/scvtc/xyxw" />
作者是因为我觉得我改动的只是很少一部分，胜之不武，所以第一个作者贡献最大所以还是用原来作者名字

2020-10-09 22:11 UTC, HenryQW commented
你需要提高代码复用率，参考其他路由如 https://docs.rsshub.app/university.html#bei-jing-lin-ye-da-xue
不能单纯复制一个文件修改链接就是一条新路由。

2020-10-09 22:11 UTC, closed without merging