fix: add doi for linkresearcher
DIYgod/RSSHub pull request #5936
Opened 2020-10-18 23:39 UTC by nczitzk

## 完整路由地址 / Example for the proposed route(s)

/linkresearcher/category=theses&subject=生物

2020-10-19 10:47 UTC, HenryQW requested changes
`doi`应该直接代替`link`，然后通过用户变量开启。
文档也需要加一个`scihub=1`

2020-10-19 23:03 UTC, nczitzk commented
> `doi`应该直接代替`link`，然后通过用户变量开启。
> 文档也需要加一个`scihub=1`

文档已添加 `supportScihub="1"`。仿照路由 /pnas 的处理，link 就不直接被 doi 代替了，而保留原网页地址。

2020-10-20 10:14 UTC, HenryQW commented
DOI这部分逻辑我写的，我给忘记了

2020-10-20 10:15 UTC, merged

2020-10-21 00:11 UTC, nczitzk commented
> DOI这部分逻辑我写的，我给忘记了

😂

2020-10-24 08:29 UTC, laampui commented
Close #5929