feat: a very basic support for miniflux
DIYgod/RSSHub pull request #5988
Opened 2020-10-24 06:51 UTC by emdoe

## 该 PR 相关 Issue / Involved issue

Related to #5744 

## 完整路由地址 / Example for the proposed route(s)

### `/miniflux/subscription/:parameters`

1. `/miniflux/subscription/`
2. `/miniflux/subscription/all`
3. `/miniflux/subscription/feeds=1,2`
4. `/miniflux/subscription/category=1&category=2`
5. `/miniflux/subscription/feed=1&feed=2&categories=1,2`

### `/miniflux/:feeds/:parameters`

1. `/miniflux/all/`
2. `/miniflux/all/feed_name=1&mark=read?limit=3`
3. `/miniflux/feed=1&feed=2/status=unread&limit=3?limit=5`
4. `/miniflux/feeds=1&2/status=unread&limit=5?limit=3`
5. `/miniflux/1&2/status=read&limit=7`

2020-10-25 17:51 UTC, HenryQW requested changes

2020-10-25 17:51 UTC, HenryQW commented on lib/routes/nytimes/morning_post.js
> +
其他路由的改动分开提交吧

2020-10-25 17:51 UTC, HenryQW commented on docs/other.md
> +2.  分类 ID 或订阅源 ID 请于`分类`（快捷键 `g` `c`）或`源`（快捷键 `g` `f`）页面获取，每个分类（或订阅源）的网址即显示其 ID 信息。
markdown 支持自动序号
```
1.
1.
1.
```
1.
1.
1.

2020-10-25 17:51 UTC, HenryQW commented on lib/routes/solidot/_article.js
> +            .replace(/(href.*?)<u>(.*?)<\/u>/g, `$1$2`)
其他路由的改动分开提交吧

2020-10-25 17:51 UTC, HenryQW commented on lib/config.js
> +        miniflux: {
可能需要在 install.md 中添加关于这些变量的说明

2020-10-25 17:58 UTC, emdoe commented on docs/other.md
> +2.  分类 ID 或订阅源 ID 请于`分类`（快捷键 `g` `c`）或`源`（快捷键 `g` `f`）页面获取，每个分类（或订阅源）的网址即显示其 ID 信息。
请问序号这里也希望修改？

2020-10-25 18:01 UTC, emdoe commented on lib/routes/solidot/_article.js
> +            .replace(/(href.*?)<u>(.*?)<\/u>/g, `$1$2`)
改动部分可以一起提交还是要再分拆成两次提交？

2020-10-29 15:39 UTC, HenryQW commented on lib/routes/solidot/_article.js
> +            .replace(/(href.*?)<u>(.*?)<\/u>/g, `$1$2`)
最好是拆分，改动不大的话可以合并

2020-10-29 15:39 UTC, HenryQW commented on docs/other.md
> +2.  分类 ID 或订阅源 ID 请于`分类`（快捷键 `g` `c`）或`源`（快捷键 `g` `f`）页面获取，每个分类（或订阅源）的网址即显示其 ID 信息。
format的锅。。。

2020-10-29 15:40 UTC, HenryQW commented on lib/routes/solidot/_article.js
> +            .replace(/(href.*?)<u>(.*?)<\/u>/g, `$1$2`)
udn肯定和这个PR无关了，分开提交吧。

2020-10-29 15:49 UTC, emdoe commented on lib/routes/solidot/_article.js
> +            .replace(/(href.*?)<u>(.*?)<\/u>/g, `$1$2`)
那两个已经撤回了，我以为和之前一样添加新的路由是可以多个一起整合的，请稍等一下

2020-10-29 16:10 UTC, emdoe commented on lib/routes/solidot/_article.js
> +            .replace(/(href.*?)<u>(.*?)<\/u>/g, `$1$2`)
@HenryQW 回退到纯 miniflux 的了，请问还有什么地方需要改动的么？

2020-10-29 17:04 UTC, HenryQW commented on lib/routes/solidot/_article.js
> +            .replace(/(href.*?)<u>(.*?)<\/u>/g, `$1$2`)
我得跑个miniflux测一下

2020-10-29 17:11 UTC, HenryQW commented on lib/routes/solidot/_article.js
> +            .replace(/(href.*?)<u>(.*?)<\/u>/g, `$1$2`)
说实话我觉得你都可以单独作为一个npm包发布了

2020-10-29 17:13 UTC, HenryQW commented on lib/routes/solidot/_article.js
> +            .replace(/(href.*?)<u>(.*?)<\/u>/g, `$1$2`)
貌似重复了轮子 https://github.com/isavegas/miniflux-rss/blob/master/src/module.ts

2020-10-29 17:13 UTC, emdoe commented on lib/routes/solidot/_article.js
> +            .replace(/(href.*?)<u>(.*?)<\/u>/g, `$1$2`)
只支持了和读文章相关的部分…帐号修改，增删订阅那些并没有支持

2020-10-29 17:20 UTC, emdoe commented on lib/routes/solidot/_article.js
> +            .replace(/(href.*?)<u>(.*?)<\/u>/g, `$1$2`)
> 貌似重复了轮子 https://github.com/isavegas/miniflux-rss/blob/master/src/module.ts

skim 了一下，应该有些许区别，因为目的上有差吧。那个纯粹而挺漂亮的支持了 API，但这个之后做内容再发布（see #5744）应该会更方便一些——前提是 Miniflux 那边支持利用 API 获得分享链接

2020-10-29 17:28 UTC, HenryQW commented
测试了大部分路由和一部分参数，可是说是目前测试难度最大的PR了😎

2020-10-29 18:03 UTC, merged