feat: Dota2战队最新比赛结果
DIYgod/RSSHub pull request #6005
Opened 2020-10-26 12:07 UTC by wzekin

## 完整路由地址 / Example for the proposed route(s)

* /liquipedia/dota2/matches/Team_Aster

2020-10-29 16:40 UTC, HenryQW requested changes

2020-10-29 16:40 UTC, HenryQW commented on lib/routes/liquipedia/dota2_matches.js
> +                        guid: date_time,
guid默认为link，没有必要赋值。设置成时间可能会导致缓存冲突。

2020-10-30 00:15 UTC, wzekin commented on lib/routes/liquipedia/dota2_matches.js
> +                        guid: date_time,
但link不是唯一的，而datetime可以保证是唯一的

2020-10-30 09:27 UTC, HenryQW commented on lib/routes/liquipedia/dota2_matches.js
> +                        guid: date_time,
如果datetime和其他源的datetime冲突了呢？link不是唯一的情况下，可以用link+datetime解决

2020-10-30 09:42 UTC, wzekin commented on lib/routes/liquipedia/dota2_matches.js
> +                        guid: date_time,
缓存策略我不大了解，已经修改了

2020-10-30 09:48 UTC, merged