feat: 新增【Prestige 蚊香社】系列作品订阅
DIYgod/RSSHub pull request #6016
Opened 2020-10-27 11:35 UTC by minimalistrojan

## 该 PR 相关 Issue / Involved issue

【Prestige 蚊香社】系列作品订阅

## 完整路由地址 / Example for the proposed route(s)

`/prestige-av/series/847/near`

2020-10-29 16:04 UTC, HenryQW requested changes

2020-10-29 16:04 UTC, HenryQW commented on package.json
> +    "cross-env": "^7.0.2",
不要提交 package.json 以及 yarn.lock 的修改

2020-10-29 16:35 UTC, minimalistrojan commented on package.json
> +    "cross-env": "^7.0.2",
啊，疏忽了。那现在应该怎么办，我解决掉这个冲突可以吗？

2020-10-29 16:42 UTC, HenryQW commented on package.json
> +    "cross-env": "^7.0.2",
本地解决之后再push就好啦

2020-10-31 01:26 UTC, minimalistrojan commented
> 有不使用`puppeteer`的实现方法吗？

文档里的前两种方法都不行。因为直接访问链接拿不到页面，所以只能用 puppeteer 模拟点击一下，才能拿到 HTML 数据。

2020-11-01 15:16 UTC, merged

2020-11-02 02:46 UTC, minimalistrojan commented
@HenryQW 大佬，被合并到官方文档后，打开报下面的错，您知道如何解决吗？我在本地测试还没遇到过这个。

<img width="1178" alt="Xnip2020-11-02_10-44-58" src="https://user-images.githubusercontent.com/22811809/97825028-7c6e4280-1cf8-11eb-852f-f4398d0035a8.png">