fix: zaobao.com from hk
DIYgod/RSSHub pull request #6129
Opened 2020-11-08 07:40 UTC by shunf4

## 该 PR 相关 Issue / Involved issue

Close #6125 

## 完整路由地址 / Example for the proposed route(s)

`/zaobao/realtime/china`

2020-11-12 15:43 UTC, HenryQW requested changes

2020-11-12 15:43 UTC, HenryQW commented on lib/routes/zaobao/util.js
> +                    pubDate: new Date().toUTCString(), // TODO: correct date here
TODO

2020-11-12 15:50 UTC, shunf4 commented on lib/routes/zaobao/util.js
> +                    pubDate: new Date().toUTCString(), // TODO: correct date here
调查了一下，此处因为链接过去的不是文章而是互动页面（如 https://interactive.zaobao.com/2020/Trump-Biden-emotions/ ），是拿不到时间的。这种情况如何处理？

2020-11-12 17:51 UTC, HenryQW commented on lib/routes/zaobao/util.js
> +                    pubDate: new Date().toUTCString(), // TODO: correct date here
我看所有interactive页面最下方都会有发布日期，就用这个吧
![image](https://user-images.githubusercontent.com/5896343/98976803-b2d56a00-250f-11eb-8636-197119bc91ab.png)

2020-11-13 11:57 UTC, shunf4 commented on lib/routes/zaobao/util.js
> +                    pubDate: new Date().toUTCString(), // TODO: correct date here
interactive 页面的 HTML 没有发布日期，发布日期是运行 JavaScript 后生成的。
我还是解析新闻列表页元素里边的日期吧。

2020-11-14 19:40 UTC, merged