新增特斯拉系统更新
DIYgod/RSSHub pull request #6275
Opened 2020-11-27 07:37 UTC by mrbruce516

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

/tesla

2020-11-27 08:58 UTC, laampui requested changes

2020-11-27 08:58 UTC, laampui commented on lib/routes/tesla/update.js
> +                        pubDate: targetDate[0],
pubDate 这里有问题，每个版本的更新说明都只取了最新那个说明的日期。

2020-11-27 14:23 UTC, mrbruce516 commented on lib/routes/tesla/update.js
> +                        pubDate: targetDate[0],
谢谢提醒，我看一下这个问题

2020-11-28 15:39 UTC, laampui approved these changes

2020-11-29 19:12 UTC, HenryQW commented
凡尔赛 PR

2020-11-29 19:13 UTC, merged