新增141jav和141ppv
DIYgod/RSSHub pull request #6639
Opened 2021-01-09 12:00 UTC by cgkings

## 该 PR 相关 Issue / Involved issue

Close #
仿照onejav，只是更新了网址，这2个站和onejav是一个网站模板，但内容不同,我自己已经测试成功了
我仿照onejav，修改了以下文件
lib/routes/141jav/141jav.js
lib/routes/141ppv/141ppv.js
docs/multimedia.md
assets/radar-rules.js
lib/router.js

## 完整路由地址 / Example for the proposed route(s)

2021-01-09 15:17 UTC, cgkings commented
磁力链获取已经修复，现在完美了

2021-01-09 15:34 UTC, cgkings commented
更新了multimedia.md

2021-01-10 08:55 UTC, NeverBehave requested changes

2021-01-10 08:55 UTC, NeverBehave commented on lib/routes/javdb/utils.js
> +            .slice(0, 25)
这里修改是为什么呢?

2021-01-11 02:52 UTC, cgkings commented on lib/routes/javdb/utils.js
> +            .slice(0, 25)
这个是我改的爬取色花堂和javdv磁力链接数量，这个不要采纳，纯个人需求
只看我提交的以下文件即可：
lib/routes/141jav/141jav.js
lib/routes/141ppv/141ppv.js
docs/multimedia.md
assets/radar-rules.js
lib/router.js

2021-01-11 02:55 UTC, NeverBehave commented on lib/routes/javdb/utils.js
> +            .slice(0, 25)
你需要将他们从你的提交中移除
创建一个新的分支, 修改后重新提交一下

2021-01-11 21:05 UTC, NeverBehave commented
暂时关闭, 在贡献者整理无关修改后请开启一个新的PR请求

2021-01-11 21:05 UTC, closed without merging