fix: 官网改版，采用JS加密，换用Puppeteer请求
DIYgod/RSSHub pull request #6682
Opened 2021-01-12 12:36 UTC by huyyi

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/uestc/sice
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [ ] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [x] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [x] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  - 使用瑞树JS加密，第一次请求返回202下发cookie，js运算后生成新cookie，用新cookie请求返回正常页面
  

## 说明 / Note

2021-01-12 12:46 UTC, huyyi commented on lib/routes/universities/uestc/sice.js
> +        delete newProto.webdriver;  // 删除navigator.webdriver字段
该部分代码仅在Chrome版本低于88时有效，暂未找到其他替代方案

2021-01-12 21:42 UTC, NeverBehave commented
那就锁定一下Headless Chrome版本, 最后可用版本是哪个?

2021-01-12 21:57 UTC, NeverBehave commented on lib/routes/universities/uestc/sice.js
> +        delete newProto.webdriver;  // 删除navigator.webdriver字段
目前在`Dockerfile`中锁定版本了, 暂时也不要追的这么紧, 后面有解决方案再更新

2021-01-12 21:58 UTC, NeverBehave requested changes

2021-01-12 21:58 UTC, NeverBehave commented on lib/routes/universities/uestc/sice.js
> +    await page.evaluateOnNewDocument(() => { // 在每个新页面打开前执行以下脚本
这段处理可以放在`lib/puppeteer`下吗, 大多数路由都可以用到

2021-01-13 02:59 UTC, huyyi commented on lib/routes/universities/uestc/sice.js
> +    await page.evaluateOnNewDocument(() => { // 在每个新页面打开前执行以下脚本
`lib/puppeteer`返回的是`browser`，这部分代码是针对`page`的，我想不到修改的思路，但是更老版本的Chrome可以在`puppeteer.launch()`中加入参数使浏览器忽略`webdriver`，具体如下：
```js
    const browser = await puppeteer.launch({
        ignoreDefaultArgs: ["--enable-automation"],
    });
```
目前测试的结果是78*是最后支持该特性的Chrome版本：
```
Chrome-Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.0 Safari/537.36
navigator.webdriver=true

Chrome-Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3882.0 Safari/537.36
navigator.webdriver=undefined
```

2021-01-13 03:13 UTC, NeverBehave commented on lib/routes/universities/uestc/sice.js
> +    await page.evaluateOnNewDocument(() => { // 在每个新页面打开前执行以下脚本
稍微看了一下, `event: 'targetcreated'`似乎可以在每次browser创建一个新page的时候获取到新page的实例
`page.evaluateOnNewDocument`可以在page定向前先注入指定脚本
不过没有关系: 如果觉得不好做可以先这样

2021-01-13 08:41 UTC, huyyi commented on lib/routes/universities/uestc/sice.js
> +    await page.evaluateOnNewDocument(() => { // 在每个新页面打开前执行以下脚本
看了一下，尝试用如下方式实现：
```js
function preload() {
    const newProto = navigator.__proto__;
    delete newProto.webdriver;  //删除navigator.webdriver字段
    navigator.__proto__ = newProto;
    window.chrome = {};  //添加window.chrome字段，为增加真实性还需向内部填充一些值
    window.chrome.app = {"InstallState":"hehe", "RunningState":"haha", "getDetails":"xixi", "getIsInstalled":"ohno"};
    window.chrome.csi = function(){};
    window.chrome.loadTimes = function(){};
    window.chrome.runtime = function(){};
    Object.defineProperty(navigator, 'userAgent', {  //userAgent在无头模式下有headless字样，所以需覆写
            get: () => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36",
    });
    Object.defineProperty(navigator, 'plugins', {  //伪装真实的插件信息
            get: () => [{"description": "Portable Document Format",
                            "filename": "internal-pdf-viewer",
                            "length": 1,
                            "name": "Chrome PDF Plugin"}]
    });
    Object.defineProperty(navigator, 'languages', { //添加语言
            get: () => ["zh-CN", "zh", "en"],
    });
    const originalQuery = window.navigator.permissions.query; //notification伪装
            window.navigator.permissions.query = (parameters) => (
            parameters.name === 'notifications' ?
            Promise.resolve({ state: Notification.permission }) :
            originalQuery(parameters)
    );
}    
browser = await puppeteer.launch(options);
    browser.on("targetcreated", async (target) => {
        if (target.type() !== 'page') {
            return;
        } else {
            console.log("new page created");
            let page = await target.page();
            await page.evaluateOnNewDocument(preload);
        }
    });
```
但是`await page.evaluateOnNewDocument(preload);`部分代码不会被执行，这似乎是`puppeteer`未解决的一个问题：

> https://github.com/puppeteer/puppeteer/issues/1443
https://github.com/puppeteer/puppeteer/issues/1378
https://github.com/puppeteer/puppeteer/issues/3667

2021-01-13 21:13 UTC, NeverBehave commented on lib/routes/universities/uestc/sice.js
> +    await page.evaluateOnNewDocument(() => { // 在每个新页面打开前执行以下脚本
看到了, 目前似乎社区也被这个问题困扰着...确实没想到呢hhh
那暂时先这样吧

2021-01-13 21:14 UTC, merged