feat-wordpress: add cdn for http images
DIYgod/RSSHub pull request #6790
Opened 2021-01-26 01:00 UTC by lonelykid

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/blogs/wordpress/wjd.name/http/1
```
Note: this blog is just a random blog from google for demo

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [ ] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

I want to subscribe a wordpress blog without https. Images won't load because chrome upgrades the embeded figures to https. By redirecting images with a cdn, it also get rid of some anti-hotlink issues.

2021-01-26 01:04 UTC, NeverBehave commented
这个设置应当在配置内进行

2021-01-26 01:12 UTC, lonelykid commented
https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
好像不太行。把资源全替换成https也算好事。

2021-01-26 01:15 UTC, NeverBehave requested changes

2021-01-26 01:15 UTC, NeverBehave commented on lib/routes/blogs/wordpress.js
> +    const cdnList = ['https://imageproxy.pimg.tw/resize?url=', 'https://images.weserv.nl/?url=', 'https://pic1.xuehuaimg.com/proxy/', 'https://cors.netnr.workers.dev/'];
这个设置应当在配置内进行
参考： f187ff9

2021-01-26 01:17 UTC, lonelykid commented on lib/routes/blogs/wordpress.js
> +    const cdnList = ['https://imageproxy.pimg.tw/resize?url=', 'https://images.weserv.nl/?url=', 'https://pic1.xuehuaimg.com/proxy/', 'https://cors.netnr.workers.dev/'];
明白了。这样就不方便白嫖rsshub.app了😂。我改一下再提交。

2021-01-26 01:24 UTC, NeverBehave commented on lib/routes/blogs/wordpress.js
> +    const cdnList = ['https://imageproxy.pimg.tw/resize?url=', 'https://images.weserv.nl/?url=', 'https://pic1.xuehuaimg.com/proxy/', 'https://cors.netnr.workers.dev/'];
如果有相关需求建议去 https://github.com/DIYgod/RSSHub/discussions/6671 提噢
未来这些修订可能都会调整

2021-01-26 02:27 UTC, lonelykid commented on lib/routes/blogs/wordpress.js
> +    const cdnList = ['https://imageproxy.pimg.tw/resize?url=', 'https://images.weserv.nl/?url=', 'https://pic1.xuehuaimg.com/proxy/', 'https://cors.netnr.workers.dev/'];
留了一个基于cloudflare的url作为默认，我找到的都是基于cloudflare和akamai这两家cdn的，如有国内访问更友好的请告知。另外还是在url留了个开关。

2021-01-26 03:43 UTC, NeverBehave requested changes

2021-01-26 03:43 UTC, NeverBehave commented on lib/router.js
> +router.get('/blogs/wordpress/:domain/:https?/:cdn?', require('./routes/blogs/wordpress'));
默认不应该使用CDN，应该是如果检测到有设置则使用，否则维持原本内容

2021-01-26 03:45 UTC, NeverBehave commented on lib/router.js
> +router.get('/blogs/wordpress/:domain/:https?/:cdn?', require('./routes/blogs/wordpress'));
如果默认有推荐可以写在文档里面

2021-01-26 05:06 UTC, NeverBehave requested changes

2021-01-26 05:06 UTC, NeverBehave commented on docs/blog.md
> +可通过`WORDPRESS_CDN`定义链接，替换 http 图片链接为 https 链接，可供考虑的服务有:
请将说明放置在`install.md`中

2021-01-27 00:52 UTC, NeverBehave approved these changes
LGTM

2021-01-27 00:52 UTC, merged