feat: Adding UMASS Amherst ECE seminar
DIYgod/RSSHub pull request #6809
Opened 2021-01-29 19:00 UTC by GammaPi

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
   /umass/amherst/eceseminar
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [x] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

At the time of the PR, ECE department may have no coming seminars.
Please change line 7 of eceseminar.js  to "  link: 'https://ece.umass.edu/seminars/archive' " if you need additional testing.

I also changed the Chinese name of our school to "麻省大学" in documentation, because most people use this name.

2021-01-30 05:30 UTC, NeverBehave requested changes
路由检测报错，路由为空
是否在本地验证有效？

2021-01-30 05:30 UTC, NeverBehave commented on docs/university.md
> +## 麻省大学 阿默斯特分校 (UMASS Amherst)
为什么这里名字要修改？ 
https://zh.wikipedia.org/wiki/%E9%A9%AC%E8%90%A8%E8%AF%B8%E5%A1%9E%E5%A4%A7%E5%AD%A6%E9%98%BF%E9%BB%98%E6%96%AF%E7%89%B9%E5%88%86%E6%A0%A1

2021-01-30 13:27 UTC, GammaPi commented on docs/university.md
> +## 麻省大学 阿默斯特分校 (UMASS Amherst)
今年系里还没有发布新研讨会的通知。本地测试可以将 eceseminar.js 的第七行链接改为  'https://ece.umass.edu/seminars/archive' " 查看效果。我已本地测试通过。

改名是因为大家普遍将学校称为 “麻省大学”。我在新提交中已改回官方称谓。

2021-01-30 13:30 UTC, GammaPi commented
目前网站还没有研讨会相关信息，故路由为空。测试可将链接改为 'https://ece.umass.edu/seminars/archive'  查看效果。
我已经进行过本地测试。

修改名称主要是大家将我校成为麻省大学。不过在最新提交中已改回维基百科上的名称。

2021-01-31 06:22 UTC, NeverBehave requested changes

2021-01-31 06:22 UTC, NeverBehave commented on docs/university.md
> +
如果路由可能存在无法抓取内容的情况，请再文档中说明一些，谢谢

2021-01-31 13:39 UTC, GammaPi commented on docs/university.md
> +
已在文档中说明，感谢提醒

2021-01-31 22:09 UTC, NeverBehave approved these changes
LGTM

2021-01-31 22:09 UTC, merged