feat: add Fur Affinity routes
DIYgod/RSSHub pull request #6912
Opened 2021-02-13 05:13 UTC by TigerCubDen

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/furaffinity/home
/furaffinity/browse
/furaffinity/status
/furaffinity/search/tiger
/furaffinity/watching/okami9312
/furaffinity/watchers/malikshadowclaw
/furaffinity/commissions/flashlioness
/furaffinity/shouts/redodgft
/furaffinity/gallery/flashlioness
/furaffinity/scraps/flashlioness
/furaffinity/favorites/tiger-jungle
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [x] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

本次新增的Fur Affinity 系列路由如下：
主页 Home
浏览 Browse
站点状态 Status
搜索 Search
用户关注列表 Watching
用户被关注列表 Watchers
用户接受委托信息 Commissions
用户的Shouts留言 Shouts
用户的创作画廊 Gallery
用户的废弃(非正式)作品 Scraps
用户的喜爱列表 favorites

2021-02-13 18:46 UTC, NeverBehave requested changes

2021-02-13 18:46 UTC, NeverBehave commented on lib/routes/bilibili/followings_dynamic.js
> -                author: item.desc.user_profile.info.uname,
为什么Bilibili的路由被修改了？

2021-02-14 04:12 UTC, TigerCubDen commented on lib/routes/bilibili/followings_dynamic.js
> -                author: item.desc.user_profile.info.uname,
已解决

2021-02-15 03:15 UTC, NeverBehave approved these changes
LGTM

2021-02-15 03:16 UTC, merged