feat:add macked
DIYgod/RSSHub pull request #6913
Opened 2021-02-13 05:31 UTC by HXHL

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/macked/app/cleanmymac-x
/macked/app/iconjar
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [x] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-02-13 05:35 UTC, HXHL commented
CodeFactor 报错的内容不是我的代码,是之前别人的commit,和本地遇上的问题应该是一样的,就是eslint不支持 ?. 运算符

2021-02-13 18:48 UTC, NeverBehave commented on .eslintrc
> +        "ecmaVersion": 2020,
This part is fixing eslint on radar, keep a note here

2021-02-13 18:49 UTC, NeverBehave requested changes

2021-02-13 18:49 UTC, NeverBehave commented on lib/routes/macked/app.js
> +            description: `<strong>简介<\\strong><br>${$('div.entry').text()}<br><img src=https:${$('div.entry').find('img').last().attr('src')}><br>
可以避免出现中文吗？

2021-02-14 00:47 UTC, HXHL commented on lib/routes/macked/app.js
> +            description: `<strong>简介<\\strong><br>${$('div.entry').text()}<br><img src=https:${$('div.entry').find('img').last().attr('src')}><br>
我应该如何优雅的实现i18n?

2021-02-15 03:13 UTC, merged