feat: add 中国共产党新闻网 24 小时滚动新闻
DIYgod/RSSHub pull request #6931
Opened 2021-02-15 13:43 UTC by nczitzk

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/people/cpc/24h
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [x] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-02-24 21:57 UTC, NeverBehave requested changes

2021-02-24 21:57 UTC, NeverBehave commented on lib/router.js
> -router.get('/shinybbs/:id?', require('./routes/shinybbs/index'));
这里的修订是？

2021-02-25 00:59 UTC, nczitzk commented on lib/router.js
> -router.get('/shinybbs/:id?', require('./routes/shinybbs/index'));
似乎是复制的时候不小心带过来了...

2021-03-02 05:21 UTC, NeverBehave requested changes

2021-03-02 05:21 UTC, NeverBehave commented on lib/router.js
> -router.get('/shinybbs/p/:id', require('./routes/shinybbs/p'));
还有这里？

2021-03-03 23:19 UTC, nczitzk commented on lib/router.js
> -router.get('/shinybbs/p/:id', require('./routes/shinybbs/p'));
👌

2021-03-07 10:15 UTC, NeverBehave approved these changes

2021-03-07 10:18 UTC, NeverBehave requested changes

2021-03-07 10:18 UTC, NeverBehave commented on lib/router.js
> -router.get('/shinybbs/:id?', require('./routes/shinybbs/index'));
这些修订是 https://github.com/DIYgod/RSSHub/pull/6910 的把，这个pr里面就不要带这些修订了
如果要的话单独再开一下，分开路由层级

2021-03-08 04:13 UTC, nczitzk commented on lib/router.js
> -router.get('/shinybbs/:id?', require('./routes/shinybbs/index'));
好的

2021-03-14 06:09 UTC, NeverBehave approved these changes

2021-03-14 06:10 UTC, merged