feat: add Eagle route and radar rules
DIYgod/RSSHub pull request #6946
Opened 2021-02-17 11:46 UTC by TigerCubDen

## 该 PR 相关 Issue / Involved issue

Close #6939

## 完整路由地址 / Example for the proposed route(s)

```routes
/eagle/changelog
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [x] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

添加 Eagle 更新日志的路由和Radar规则
Eagle网址如下：https://cn.eagle.cool

2021-02-20 08:40 UTC, NeverBehave requested changes
处理一下conflict

P.S. 可以的话请不要产生过多的commit，会很消耗CI次数

2021-02-21 09:24 UTC, TigerCubDen commented
> 处理一下conflict
> 
> P.S. 可以的话请不要产生过多的commit，会很消耗CI次数

1.已处理
2.好的，不过弱弱问下减少commit有哪些方法呢？

2021-02-22 23:43 UTC, NeverBehave requested changes

2021-02-22 23:43 UTC, NeverBehave commented on lib/router.js
> +router.get('/eagle/changelog/:language?', require('./routes/eagle/changelog'));
文件路径是错的，测试没有通过

2021-02-22 23:44 UTC, NeverBehave commented
> > 处理一下conflict
> > P.S. 可以的话请不要产生过多的commit，会很消耗CI次数
> 
> 1.已处理
> 2.好的，不过弱弱问下减少commit有哪些方法呢？

不要使用网页提交修改，在本地修改好，整理好commit以后再开pr

2021-02-24 21:49 UTC, NeverBehave approved these changes

2021-02-24 21:49 UTC, merged