feat: enable high quality player for bilibili video
DIYgod/RSSHub pull request #6968
Opened 2021-02-19 03:29 UTC by hoilc

## 该 PR 相关 Issue / Involved issue

Close #6957

## 完整路由地址 / Example for the proposed route(s)

```routes
/bilibili/user/dynamic/2267573
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [ ] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

效果如下

![image](https://user-images.githubusercontent.com/9067094/108453545-a8143900-72a5-11eb-93ca-c067e609d555.png)

2021-02-23 00:09 UTC, NeverBehave requested changes

2021-02-23 00:09 UTC, NeverBehave commented on docs/social-media.md
> +## Fur Affinity
这个变动是？

2021-02-23 01:40 UTC, hoilc commented on docs/social-media.md
> +## Fur Affinity
在此之前master上合并的commit有问题，自动format时带上了

2021-02-24 22:10 UTC, NeverBehave approved these changes

2021-02-24 22:12 UTC, merged