feat(ncm): 添加网易云音乐-歌手歌曲
DIYgod/RSSHub pull request #7038
Opened 2021-02-25 11:51 UTC by ZhongMingKun

## 该 PR 相关 Issue / Involved issue

Close #7037 

## 完整路由地址 / Example for the proposed route(s)

```routes
/ncm/artist_songs/12039226/10
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

网易云音乐-歌手歌曲

2021-03-02 21:40 UTC, NeverBehave requested changes

2021-03-02 21:40 UTC, NeverBehave commented on docs/multimedia.md
> +<Route author="ZhongMingKun" example="/ncm/artist_songs/12039226/10" path="/ncm/artist_songs/:id/:limit?" :paramsDesc="[' 歌手 id, 可在歌手详情页 URL 中找到', '请求数量,默认10条']" radar="1" />
请在稳定获取的基础上尽可能获取，rsshub会处理限制数量的操作

2021-03-04 02:12 UTC, ZhongMingKun commented on docs/multimedia.md
> +<Route author="ZhongMingKun" example="/ncm/artist_songs/12039226/10" path="/ncm/artist_songs/:id/:limit?" :paramsDesc="[' 歌手 id, 可在歌手详情页 URL 中找到', '请求数量,默认10条']" radar="1" />
暂时测试100条都能稳定获取。是要改成100条吗？

2021-03-11 05:58 UTC, NeverBehave commented on docs/multimedia.md
> +<Route author="ZhongMingKun" example="/ncm/artist_songs/12039226/10" path="/ncm/artist_songs/:id/:limit?" :paramsDesc="[' 歌手 id, 可在歌手详情页 URL 中找到', '请求数量,默认10条']" radar="1" />
一般是按照需要进行的请求进行判断：如果一次请求可以完成的，尽量不要发起多个请求。所以这里的话我建议是限制在两个请求内，如果可以一个请求能获取多少就是多少

2021-10-05 09:12 UTC, NeverBehave commented
由于 #8236
旧版本的新路由请求将会被关闭，请按照新版路由规范修改后重新开启，谢谢！
需要帮助请在讨论下留言，我们可以协助迁移

2021-10-05 09:12 UTC, closed without merging