docs: replace socks5 with socks5h in install docs
DIYgod/RSSHub pull request #7086
Opened 2021-03-02 14:47 UTC by shunf4

## 该 PR 相关 Issue / Involved issue

无

## 完整路由地址 / Example for the proposed route(s)

```routes
NOROUTE
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [X] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

更新了文档中 SOCKS5 代理的使用方式。为防止域名污染和 DNS 查询泄露，所有 SOCKS5 用户都应首先考虑使用 socks5h（传域名的 SOCKS5）。

2021-03-02 21:47 UTC, NeverBehave requested changes

2021-03-02 21:47 UTC, NeverBehave commented on docs/en/install/README.md
> +`PROXY_PROTOCOL`: Using proxy, Supports socks, socks5, socks5h, http, https, etc.
请将issue中的理由写入文档，或者添加socks5h说明的网址，方便用户选择适合自己场景的操作

2021-03-03 05:07 UTC, shunf4 commented on docs/en/install/README.md
> +`PROXY_PROTOCOL`: Using proxy, Supports socks, socks5, socks5h, http, https, etc.
Done

2021-03-07 10:06 UTC, NeverBehave approved these changes

2021-03-07 10:06 UTC, merged