fix: adapt to new sjtu-jwc webpage
DIYgod/RSSHub pull request #7160
Opened 2021-03-12 06:14 UTC by SeanChao

## 该 PR 相关 Issue / Involved issue

Close #

No involved issue

## 完整路由地址 / Example for the proposed route(s)

[https://rsshub.app/sjtu/jwc](https://rsshub.app/sjtu/jwc)

```routes
/sjtu/jwc
/sjtu/jwc/all
/sjtu/jwc/notice
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [x] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

Update rules since the target webpage is updated.

2021-03-16 21:37 UTC, NeverBehave requested changes

2021-03-16 21:37 UTC, NeverBehave commented on docs/university.md
> +| news     | notice   | operation | affairs  | yjb    | jgb    | zhb    | language | party      | ge       |
请在正文部分列出所有可能type进行测试

2021-03-17 00:07 UTC, SeanChao commented on docs/university.md
> +| news     | notice   | operation | affairs  | yjb    | jgb    | zhb    | language | party      | ge       |
加上了

2021-04-13 08:13 UTC, dzx-dzx commented on docs/university.md
> +| news     | notice   | operation | affairs  | yjb    | jgb    | zhb    | language | party      | ge       |
@NeverBehave

2021-04-19 06:57 UTC, skyzh commented
This PR may close https://github.com/DIYgod/RSSHub/issues/7392

2022-02-01 12:40 UTC, TonyRL requested changes
v2 script standard https://github.com/DIYgod/RSSHub/discussions/8236

2022-02-01 12:40 UTC, TonyRL commented on lib/routes/universities/sjtu/jwc.js
> +                const pubDate = new Date(date.getTime() - 60 * 60 * 1000 * (8 + date.getTimezoneOffset() / 60)).toUTCString();
Please use parseDate()
docs: https://docs.rsshub.app/joinus/pub-date.html

2022-02-01 12:40 UTC, TonyRL commented on lib/routes/universities/sjtu/jwc.js
> +    const type = ctx.params.type || 'all';
```suggestion
    const type = ctx.params.type ?? 'all';
```

2022-02-02 11:40 UTC, merged