feat: add cookie to nga forum route
DIYgod/RSSHub pull request #7174
Opened 2021-03-12 21:15 UTC by lonelykid

## 该 PR 相关 Issue / Involved issue

Close #6775

## 完整路由地址 / Example for the proposed route(s)

```routes
/nga/forum/-7
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [ ] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

获取帖子内容的route之前已经有cookie了，部分板块帖子列表及摘要也需要cookie获取。
😂，不是我想刷屏，这个自动检查模版实在有点不友好，也没法edit。两次都把route填错了位置，填到了注释那里。

2021-03-14 06:33 UTC, NeverBehave commented
- 如果增添了新的配置，config.js和对应文档请一并更新
- PR模版做了一些调整，还是不方便使用吗？

2021-03-14 06:33 UTC, NeverBehave requested changes

2021-03-14 06:33 UTC, NeverBehave commented on lib/routes/nga/forum.js
> +    if (config.nga.uid && config.nga.cid) {
这个配置是已经存在文档中的吗？

2021-03-14 07:34 UTC, lonelykid commented on lib/routes/nga/forum.js
> +    if (config.nga.uid && config.nga.cid) {
https://docs.rsshub.app/install/#pei-zhi-bu-fen-rss-mo-kuai-pei-zhi  已经有了，不是新增加的配置项。
容易把route误填到注释里面去。

2021-03-26 21:54 UTC, merged

2021-03-27 11:53 UTC, lonelykid commented
怎么这些fork的人自己pull的时候还要@commit的人？被@好多次...