fix(docs): 修改用 docker-compose 更新 rsshub 的文案，对新手更友好
DIYgod/RSSHub pull request #7192
Opened 2021-03-14 09:03 UTC by Crayon-ShinChan

在 docker-compose 更新操作的指示中加入拉取新镜像的操作提示，对新手更友好。否则新手直接 docker-compose up -d 可能导致没有更新镜像。

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
NOROUTE
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [x] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-03-14 21:22 UTC, NeverBehave requested changes

2021-03-14 21:22 UTC, NeverBehave commented on docs/en/install/README.md
> +Pull the latest image
在这里多说明一下在什么情况下需要进行这个操作会比较好
将说明部分的内容添加过来就好了

2021-03-15 11:24 UTC, Crayon-ShinChan commented on docs/en/install/README.md
> +Pull the latest image
修改好了，说明了如果之前下载过镜像，但是 RSSHub 有所更新，则需要进行这一步操作

2021-03-15 22:39 UTC, NeverBehave requested changes

2021-03-15 22:39 UTC, NeverBehave commented on docs/install/README.md
> +如果你之前安装下载了旧镜像，[RSSHub](https://github.com/DIYgod/RSSHub) 现在已经有所更新，那么拉取最新镜像
```suggestion
如果之前已经下载/使用过镜像，下方命令可以帮助你获取最新版本：这可能可以解决一些问题。
```

2021-03-15 22:39 UTC, NeverBehave commented on docs/en/install/README.md
> +Pull the latest image if [RSSHub](https://github.com/DIYgod/RSSHub) has been updated and you downloaded the older image previously
```suggestion
re-Pull the latest image if you have downloaded the image before. It is helpful to resolve some issues.
```

2021-03-28 14:58 UTC, Crayon-ShinChan commented
还有哪里需要改的吗？我不是很明白

2021-03-30 20:06 UTC, merged