chroe: Docker build 缩小 image size 更新github action
DIYgod/RSSHub pull request #7197
Opened 2021-03-14 12:39 UTC by fengkx

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
NOROUTE
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [ ] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [x] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

1. 使用[@vercel/nft](https://www.npmjs.com/package/@vercel/nft)删除用不到的JS文件。Vercel 在它的Function中就是使用这个东西去删除无用文件的。所以应该vercel能跑起来的，删完之后docker也能跑起来。
1. 使用multi-stage build, 缩小image 体积。避免编译的以来进入最终docker image。 把长命令分开成一个个RUN,可以更好的利用docker的layer缓存
1. 更新github action 为 https://github.com/docker/build-push-action 其实就是现在用的这个action的v2

Question: 是否可以考虑统一Dockerfile里的npm,yarn。并在容器内提供lock file使用`yarn`或者`npm ci`这样安装依赖起来会快些。 （我觉得用选npm好些，yarn1 “frozen” 了

可能拆分几个pr更好, 但是测试action和docker build的时间着实久。。。所以不分了

![docker-images](https://user-images.githubusercontent.com/16515468/111068763-16df5d80-8505-11eb-82fd-61190641ee7d.png)

2021-03-14 21:15 UTC, NeverBehave commented
- 需要测试一下puppetter，这个问题比较多，vercel不能正确处理动态增加binary的操作
- yarn的问题是什么？freeze在哪里？我更建议yarn是因为有lockfile
- 引入QEMU是为什么什么？以前的xbuild有问题吗？

2021-03-15 01:12 UTC, fengkx commented
> 需要测试一下puppetter，api，这个问题比较多，vercel不能正确处理动态增加binary的操作

本地测试过不会删除安装的chromium。puppetter的路由和`/api/routes/`都能正常用。`docker build --build-arg PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false -t rsshub-my-puppeteer .` build 的docker也都能正常使用

>     * 如果这样就不需要手动clean-nm.sh，可以测试直接替换掉吗？

有些`.travis.yml, .eslintrc.json`之类的还是需要clean-nm去清

> yarn的问题是什么？freeze在哪里？我更建议yarn是因为有lockfile

https://github.com/yarnpkg/yarn yarn1 facebook已经不再更新了。yarn2 也就是 berry 默认的pnp模式没有`node_mousles`文件夹，兼容性很差。npm 也有lockfile。npmv7的package-lock.json v2 比yarn.lock记录的东西更全面。而且我使用的时候觉得npm v7比yarn更快。

yarn 有时还会出现网络问题，我本地和GitHub action 都出现了。 https://github.com/fengkx/RSSHub/runs/2106260153?check_suite_focus=true#step:5:2077 用npm就没有。


> 引入QEMU是为什么什么？以前的xbuild有问题吗？

https://github.com/fengkx/RSSHub/runs/2106115538?check_suite_focus=true
docker buildx 会调用QEMU的，set-up qemu 耗时也就几秒。

2021-03-15 11:01 UTC, fengkx commented
c360853 修了一下在Docker中安pupptter chromium的情况。`docker build --build-arg PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=0 -t rsshub-my-puppeteer .` build的docker实测是能访问用到headless chrome的路由的。

https://github.com/puppeteer/puppeteer/blob/5f24f608194fd4252da7b288461427cabc9dabb3/install.js#L37 `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=0` 不会安装Chromium,所以加了个`unset`。 因为`export/unset`只对当前layer生效，所以把`npm install`放在了同一layer。这个参数应该坏了有一段时间了。。。

后面装的一堆东西是从[这里](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker)来的。

2021-03-15 22:26 UTC, NeverBehave commented on .github/workflows/docker-release.yml
> -            uses: crazy-max/ghaction-docker-buildx@v1
crazy-max/ghaction-docker-buildx 这个不在维护了，确实需要更新

2021-03-15 22:31 UTC, NeverBehave requested changes
- 我不建议使用vercel那一套压缩是因为他们那个很容易产生奇怪的问题。我不是很清楚新版的做法但是如果只是包含了需要的文件的话，为什么.yml 文件还是会被包含？
- 如果继续使用npm没有问题，我确实没有特别留意目前yarn的状态……目前项目我没看错是没有npm的lockfile的，如果可以的话请顺便包含一下可用的版本？

2021-03-15 22:31 UTC, NeverBehave commented on .github/workflows/docker-test.yml
> -        if: github.repository == 'DIYgod/RSSHub'
这里是为什么？我没记错的话如果删掉可能会导致所有fork也会运行测试

2021-03-15 22:31 UTC, NeverBehave commented on Dockerfile
> -ENV NODE_ENV production
时区设定也需要删除吗？

2021-03-15 22:31 UTC, NeverBehave commented on tools/minify-docker.js
> +const fs = require('fs/promises');
这个文件是为了删除额外的文件吗？clean-nm.sh是被这个取代吗？

2021-03-16 02:34 UTC, fengkx commented on .github/workflows/docker-test.yml
> -        if: github.repository == 'DIYgod/RSSHub'
fork 不会跑除非commit

2021-03-16 02:35 UTC, fengkx commented on Dockerfile
> -ENV NODE_ENV production
这是dep-builder

2021-03-16 02:35 UTC, fengkx commented on tools/minify-docker.js
> +const fs = require('fs/promises');
154ec56 clean-nm删了

2021-03-16 02:38 UTC, fengkx commented
不建议同时保留package-lock.json 和 yarn.lock。 因为这俩稍不注意就会不同步。 npmv7 支持从yarn.lock 读数据 https://blog.npmjs.org/post/621733939456933888/npm-v7-series-why-keep-package-lockjson

2021-03-21 19:41 UTC, NeverBehave commented
npmv7我看只使用yarn.lock似乎功能不全？有必要在文档中全部换成npmv7吗？

2021-03-21 19:49 UTC, SukkaW commented
> npmv7我看只使用yarn.lock似乎功能不全？有必要在文档中全部换成npmv7吗？

应该是 npm@7 支持 yarn.lock 所有的特性——Yarn 能安装和运行的程序、npm@7 按照 yarn.lock 安装依赖后也可以运行。但是没有必要说因此抛弃 package.json。而且我不喜欢 PnP、所以我不使用 Yarn，所以我 Vote No。

我们应该扔掉 yarn.lock 而不是扔掉 package.json。

2021-03-23 00:36 UTC, NeverBehave commented
我的意思也是说抛弃yarn.lock，如果这样的话当前commit准备好了吗？
我可以后面抽时间过一下文档

2021-03-23 13:43 UTC, fengkx commented
> 我的意思也是说抛弃yarn.lock，如果这样的话当前commit准备好了吗？

去掉了yarn.lock, 换package-lock.json了

2021-03-31 01:09 UTC, NeverBehave commented
nice，顺便可以修订一下文档吗？比如说
https://github.com/DIYgod/RSSHub/blob/506bcf04f11cede81d952cc6df889bf71f737e23/docs/install/README.md

2021-03-31 01:43 UTC, fengkx commented
安装方式没有变化呀。那文档要改什么？

2021-07-17 09:30 UTC, NeverBehave commented
可以处理一下冲突吗，感觉差不多可以合并了

2021-07-17 12:34 UTC, fengkx commented
处理完liao

2021-08-12 06:01 UTC, NeverBehave approved these changes

2021-08-12 06:01 UTC, merged

2021-08-12 19:24 UTC, yan12125 commented
The newly introduced `minify-docker.js` seems problematic - no files are left in `node_modules`.
```
$ podman run --rm docker.io/diygod/rsshub

> rsshub@1.0.0 start /app
> node lib/index.js

internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'module-alias'
Require stack:
- /app/lib/app.js
- /app/lib/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/app/lib/app.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/lib/app.js', '/app/lib/index.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rsshub@1.0.0 start: `node lib/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rsshub@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-12T19_22_02_693Z-debug.log

$ podman run --rm -it docker.io/diygod/rsshub sh -c "ls -al /app/node_modules"
total 8
drwxr-xr-x 2 root root 4096 Aug 12 17:33 .
drwxr-xr-x 9 root root 4096 Aug 12 17:33 ..
```