feat(route): add World Happiness Report
DIYgod/RSSHub pull request #7223
Opened 2021-03-21 00:15 UTC by nczitzk

## 该 PR 相关 Issue / Involved issue

Close #7218

## 完整路由地址 / Example for the proposed route(s)

```routes
/worldhappiness/blog
/worldhappiness/archive
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [x] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [x] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-06-10 18:46 UTC, NeverBehave requested changes

2021-07-26 00:34 UTC, SettingDust requested changes

2021-07-26 00:34 UTC, SettingDust commented on lib/routes/worldhappiness/archive.js
> +                    item.pubDate = parseDate(`${item.link.split('/').pop()}-01-01`, 'YYYY-MM-DD');
日期不对，结果里没有，而且可以不带 MM DD 解析吧？

2021-07-26 01:18 UTC, nczitzk commented on lib/routes/worldhappiness/archive.js
> +                    item.pubDate = parseDate(`${item.link.split('/').pop()}-01-01`, 'YYYY-MM-DD');
感谢 review 🤝

2021-07-28 07:23 UTC, SettingDust requested changes

2021-07-28 07:23 UTC, SettingDust commented on lib/routes/worldhappiness/blog.js
> +        .slice(0, 10)
无副作用的情况下尽可能多

2021-07-28 07:23 UTC, SettingDust commented on lib/routes/worldhappiness/archive.js
> +        .slice(0, 10)
同下

2021-07-28 07:27 UTC, SettingDust requested changes

2021-07-28 07:27 UTC, SettingDust commented on lib/routes/worldhappiness/blog.js
> +        title: $('title').text(),
附加了时间，不对吧

2021-07-28 07:27 UTC, SettingDust commented on lib/routes/worldhappiness/archive.js
> +                link: `${rootUrl}${item.attr('href')}`,
附加一个年份作为时间吧？

2021-07-28 11:05 UTC, nczitzk commented on lib/routes/worldhappiness/archive.js
> +                link: `${rootUrl}${item.attr('href')}`,
其实这算是源站没有提供时间吧 😂

2021-07-28 16:09 UTC, SettingDust requested changes

2021-07-28 16:09 UTC, SettingDust commented on lib/routes/worldhappiness/archive.js
> +                    item.description = content('.report-meta').html() + content('.report-body').html();
正文有标题，源站没有，怎么会抓到的

2021-07-29 00:04 UTC, nczitzk commented on lib/routes/worldhappiness/archive.js
> +                    item.description = content('.report-meta').html() + content('.report-body').html();
看上去是源站有一个隐藏的 h1 标题，已移除 🤝

2021-07-29 03:27 UTC, SettingDust approved these changes

2021-08-12 08:13 UTC, NeverBehave approved these changes

2021-08-12 08:14 UTC, merged