8kcos
DIYgod/RSSHub pull request #7237
Opened 2021-03-22 16:09 UTC by KotoriK

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/8kcos/tag/cosplay
/8kcos/cat/
/8kcos/
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [x] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-05-08 22:02 UTC, NeverBehave commented
我们近期对日期工具类进行了调整，请参考 https://docs.rsshub.app/joinus/pub-date.html

2021-08-23 03:20 UTC, SettingDust requested changes

2021-08-23 03:20 UTC, SettingDust commented on lib/routes/8kcos/latest.js
> +                    .slice(0, 10)
无副作用前提下尽可能多获取
```suggestion
```

2021-08-23 03:20 UTC, SettingDust commented on lib/routes/8kcos/tag.js
> +            .slice(0, 10)
```suggestion
```

2021-08-23 03:20 UTC, SettingDust commented on lib/routes/8kcos/cat.js
> +            .slice(0, 10)
```suggestion
```

2021-08-23 03:20 UTC, SettingDust commented on lib/routes/8kcos/article.js
> +    const entry_children = article('div.entry-content').children();
小驼峰命名

2021-08-23 03:20 UTC, SettingDust commented on lib/routes/8kcos/article.js
> +        title:article('.entry-title').text(),
冒号后无空格，本地跑一下 lint 任务再 commit

2021-08-23 04:18 UTC, KotoriK commented on lib/routes/8kcos/latest.js
> +                    .slice(0, 10)
主要是Vercel部署时函数最长只能运行十秒

2021-08-23 04:35 UTC, KotoriK commented on lib/routes/8kcos/latest.js
> +                    .slice(0, 10)
那可以使用limit query作为限制？

2021-08-23 04:42 UTC, SettingDust commented on lib/routes/8kcos/latest.js
> +                    .slice(0, 10)
这是自动的，如果来源没有数量限制的方法就不需要自己处理长度，limit 会自动限制结果数量

2021-08-23 06:02 UTC, KotoriK commented on lib/routes/8kcos/latest.js
> +                    .slice(0, 10)
我看到了相关代码，是在路由的脚本运行完后对```ctx.state.data.item```slice
然而这种做法达不到节省运算资源的目的，因为这时最耗时的HTTP请求已经完成。
现在上传的新commit已经去除了默认的数量限制，改为从query中读取。
如果中间件那边的逻辑不做改变的话，目前这种方法可能是最好的。

2022-02-01 12:48 UTC, TonyRL requested changes
v2 script standard #8236
Please resolve merge conflict on `docs/picture.md`

2022-02-25 00:59 UTC, merged