feat: add 澎湃号
DIYgod/RSSHub pull request #7278
Opened 2021-03-26 09:05 UTC by WenhuWee

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/thepaper/user/5221402
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [x] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-03-26 15:01 UTC, queensferryme commented on lib/routes/thepaper/user.js
> +            const pubDate = new Date(content('.news_about').find('p').text().trim().split('来源：')[0].trim() + ' GMT+8').toUTCString();
推荐使用官方工具 `@/utils/data` 来处理时间，可以参考 [lib/routes/yicai/brief.js](https://github.com/DIYgod/RSSHub/blob/e6734345eebefae795ca91924661c139b454fc22/lib/routes/yicai/brief.js)。

2021-03-26 15:01 UTC, queensferryme commented on lib/routes/thepaper/user.js
> +    }
可以简化成 `let name = items[0].author || id;`

2021-05-25 13:20 UTC, NeverBehave requested changes
We are sorry for any inconvenience here, please update usage of date utils

2021-05-25 13:20 UTC, NeverBehave commented on lib/routes/thepaper/user.js
> +const date = require('@/utils/date');
date is deprecated, see https://docs.rsshub.app/joinus/pub-date.html

2021-09-26 09:00 UTC, NeverBehave commented
由于 #8236
旧版本的新路由请求将会被关闭，请按照新版路由规范修改后重新开启，谢谢！
需要帮助请在讨论下留言，我们可以协助迁移

2021-09-26 09:00 UTC, closed without merging