豆瓣小组反爬变严格，会封禁IP，改为puppeteer形式
DIYgod/RSSHub pull request #7290
Opened 2021-03-28 07:41 UTC by theowenyoung

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/douban/group/698716
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [ ] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

豆瓣小组策略变严格，改为headless形式。

IP封禁后，豆瓣小组页面显示：

> 检测到有异常请求从你的 IP 发出，请 登录 使用豆瓣。

2021-05-08 22:02 UTC, NeverBehave commented
我们近期对日期工具类进行了调整，请参考 https://docs.rsshub.app/joinus/pub-date.html

2021-05-12 04:32 UTC, NeverBehave requested changes
可以提供更多信息吗？是目前的方法会导致封禁所以换至puppetter，还是当前方法已经不可以使用？

2021-05-12 09:45 UTC, theowenyoung commented
这边本地测试发现直接request的请求几次之后会封禁ip，换用puppeteer模拟请求后正常。

2021-05-12 19:12 UTC, NeverBehave commented
> 这边本地测试发现直接request的请求几次之后会封禁ip，换用puppeteer模拟请求后正常。

可以先开启相关issue吗？我们需要更多数据点判断相关情况

2021-05-25 07:05 UTC, ruleroller commented
![image](https://user-images.githubusercontent.com/3047708/119453950-89bd4e00-bd6a-11eb-86a9-3f6cff5068eb.png)

我自建3个小组的路由，大约15分钟抓取一次，很快就404了，应该是被屏蔽了吧。

2021-05-28 16:28 UTC, theowenyoung commented
感觉你可能是puppeteer没装成功？ 试试 `npm i puppeteer`? @ruleroller

2022-02-01 13:19 UTC, TonyRL commented
<details>
<summary>Screenshot</summary>

![screenshot](https://user-images.githubusercontent.com/11386903/151975508-355e277b-cadf-4cbe-86fe-bde9d23c04a0.png)
</details>

Only one feed item has description, is it intended behaviour?

2023-03-19 20:50 UTC, DIYgod commented
我自己自建的一直没遇到问题，而且 puppeteer 理论上也很难解决频率过高被反爬的问题，应该谨慎使用 puppeteer，pr 时间过长，所以本 pr 将先被关闭，如果还有疑问可以随时在下面继续讨论

2023-03-19 20:50 UTC, closed without merging