feat(route): EU Disinfo Lab publications
DIYgod/RSSHub pull request #7294
Opened 2021-03-29 05:39 UTC by nczitzk

## 该 PR 相关 Issue / Involved issue

Close #7281

## 完整路由地址 / Example for the proposed route(s)

```routes
/disinfo/publications
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [x] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [x] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-05-25 13:21 UTC, NeverBehave requested changes

2021-05-25 13:21 UTC, NeverBehave commented on lib/routes/disinfo/publications.js
> +const date = require('@/utils/date');
https://docs.rsshub.app/joinus/pub-date.html

2021-08-05 00:19 UTC, SettingDust requested changes

2021-08-05 00:19 UTC, SettingDust commented on lib/routes/disinfo/publications.js
> +        .slice(0, 10)
截断？

2021-08-05 00:23 UTC, SettingDust requested changes

2021-08-05 00:23 UTC, SettingDust commented on lib/routes/disinfo/publications.js
> +                    item.description = content('.elementor-widget-theme-post-content').html();
有lazyload 的图

2021-08-05 00:34 UTC, SettingDust approved these changes

2021-08-12 08:34 UTC, NeverBehave requested changes
处理一下冲突

2022-02-01 13:21 UTC, TonyRL commented
v2 script standard #8236

2022-02-01 13:21 UTC, TonyRL requested changes
v2 script standard #8236

2022-02-19 10:52 UTC, merged