feat: add nippon.com
DIYgod/RSSHub pull request #7312
Opened 2021-04-01 12:48 UTC by laampui

## 该 PR 相关 Issue / Involved issue

Close #7306 

## 完整路由地址 / Example for the proposed route(s)

```routes
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [ ] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-04-01 12:53 UTC, laampui commented
@NeverBehave 帮我 reopen 一下

2021-06-10 18:48 UTC, NeverBehave approved these changes

2021-06-10 18:49 UTC, NeverBehave requested changes
`/nippon/Science,Technology` 这个路由是什么问题？

2021-06-12 00:05 UTC, laampui commented
> `/nippon/Science,Technology` 这个路由是什么问题？

已修复

2021-07-27 02:44 UTC, RekiDunois commented
这个 pr 还有什么地方没办法合并吗？我看前面的 Changes requested 已经修复了

2022-01-18 02:34 UTC, RekiDunois commented
@NeverBehave 这个 pr 还有什么地方没办法合并吗？我看前面的 Changes requested 已经修复了

2022-01-18 02:44 UTC, NeverBehave commented
@RekiDunois 新路由目前只接受v2版本的

2022-01-23 15:32 UTC, laampui commented
@RekiDunois @NeverBehave 更到v2了

2022-01-23 15:50 UTC, TonyRL requested changes

2022-01-23 15:50 UTC, TonyRL commented on lib/v2/nippon/radar.js
> +                docs: 'http://localhost:8080/travel.html#zou-jin-ri-ben',
```suggestion
                docs: 'https://docs.rsshub.app/travel.html#zou-jin-ri-ben',
```

2022-01-23 16:01 UTC, TonyRL commented on lib/v2/nippon/index.js
> +                })
Unnecessary async/await keyword
```suggestion
        list.slice(0, 10).map((item) =>
                ctx.cache.tryGet(item.link, async () => {
                    const res = await got.get(item.link);
                    const $ = cheerio.load(res.data);
                    item.description = $('.editArea').html();
                    return item;
                })
```

2022-01-31 16:12 UTC, TonyRL commented on lib/v2/nippon/index.js
> +    const category = ctx.params.category || 'Politics';
```suggestion
    const category = ctx.params.category ?? 'Politics';
```

2022-01-31 17:04 UTC, merged