中国政府信息搜索：增加发表日期
DIYgod/RSSHub pull request #7334
Opened 2021-04-06 09:45 UTC by drgnchan

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
NOROUTE
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [ ] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

修复没有pubDate的问题

2021-05-12 19:37 UTC, NeverBehave requested changes

2021-05-12 19:37 UTC, NeverBehave commented on lib/routes/gov/zhengce/govall.js
> +                        pubDate: date(dateString.text())
我们近期对日期工具类进行了调整，请参考这个指南调整PR https://docs.rsshub.app/joinus/pub-date.html

2021-07-10 23:40 UTC, SettingDust requested changes

2021-07-10 23:40 UTC, SettingDust commented on lib/routes/gov/cac/more.js
> +        .slice(0, 10)
限制大小有 limit 来做，不需要路由限制到这么低的数量，原因是什么

2021-07-10 23:40 UTC, SettingDust commented on lib/routes/zhihu/posts.js
> +                pubDate: new Date(item.updated * 1000).toUTCString(),
不在 pr 范围内 请清理

2021-07-10 23:40 UTC, SettingDust commented on package.json
> +    "puppeteer": "^9.1.1",
原因？

2021-10-05 09:38 UTC, NeverBehave commented
Close due to staled

2021-10-05 09:38 UTC, closed without merging