feat(route): add 四川农业大学招生就业
DIYgod/RSSHub pull request #7350
Opened 2021-04-09 12:55 UTC by nczitzk

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/sicau/zsjy/yjszs
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [x] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-05-12 19:31 UTC, NeverBehave requested changes

2021-05-12 19:31 UTC, NeverBehave commented on lib/routes/universities/sicau/zsjy.js
> +const date = require('@/utils/date');
我们近期对日期工具类进行了调整，请参考这个指南调整PR https://docs.rsshub.app/joinus/pub-date.html

2021-07-20 02:10 UTC, SettingDust requested changes

2021-07-20 02:10 UTC, SettingDust commented on lib/routes/universities/sicau/zsjy.js
> +        .slice(0, 10)
没必要截断

2021-07-20 02:10 UTC, SettingDust commented on lib/routes/universities/sicau/zsjy.js
> +                pubDate: timezone(parseDate(item.prev().text(), 'YYYY-MM-DD'), +8),
没有时间，没必要时区

2021-07-20 02:10 UTC, SettingDust commented on lib/routes/universities/sicau/zsjy.js
> +                    item.description = content('.v_news_content').html();
处理正文中标题![Screenshot_2021_0720_100721.jpg](https://user-images.githubusercontent.com/19922286/126251584-6b96c6a4-1847-4cbe-94d5-e5b7dcdade39.jpg)

2021-07-20 07:44 UTC, nczitzk commented on lib/routes/universities/sicau/zsjy.js
> +        .slice(0, 10)
👌

2021-07-20 07:44 UTC, nczitzk commented on lib/routes/universities/sicau/zsjy.js
> +                pubDate: timezone(parseDate(item.prev().text(), 'YYYY-MM-DD'), +8),
👌

2021-07-20 07:44 UTC, nczitzk commented on lib/routes/universities/sicau/zsjy.js
> +                    item.description = content('.v_news_content').html();
👌

2021-10-05 09:29 UTC, NeverBehave commented
由于 #8236
旧版本的新路由请求将会被关闭，请按照新版路由规范修改后重新开启，谢谢！
需要帮助请在讨论下留言，我们可以协助迁移

2021-10-05 09:29 UTC, closed without merging