feat(route): 恩山无线论坛板块
DIYgod/RSSHub pull request #7365
Opened 2021-04-11 11:43 UTC by nczitzk

## 该 PR 相关 Issue / Involved issue

Close #7363

## 完整路由地址 / Example for the proposed route(s)

```routes
/right/forum
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [x] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-05-12 19:35 UTC, NeverBehave requested changes

2021-05-12 19:35 UTC, NeverBehave commented on lib/routes/right/forum.js
> +const date = require('@/utils/date');
我们近期对日期工具类进行了调整，请参考这个指南调整PR https://docs.rsshub.app/joinus/pub-date.html

2021-07-20 02:37 UTC, SettingDust requested changes

2021-07-20 02:37 UTC, SettingDust commented on lib/routes/right/forum.js
> +                                .replace('发表于 ', '')
parseDate 可以不用 replace，建议

2021-07-20 02:37 UTC, SettingDust commented on lib/routes/right/forum.js
> +        .slice(0, 10)
截断

2021-07-20 08:27 UTC, SettingDust approved these changes

2021-08-12 06:42 UTC, NeverBehave approved these changes

2021-08-12 06:47 UTC, merged