feat(route): add Fermilab News
DIYgod/RSSHub pull request #7371
Opened 2021-04-12 01:04 UTC by nczitzk

## 该 PR 相关 Issue / Involved issue

Close #7368

## 完整路由地址 / Example for the proposed route(s)

```routes
/fnal/news
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [x] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [x] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-05-12 19:36 UTC, NeverBehave requested changes

2021-07-20 02:30 UTC, SettingDust requested changes

2021-07-20 02:30 UTC, SettingDust commented on lib/routes/fnal/news.js
> +        .slice(0, 10)
截断

2021-07-20 02:30 UTC, SettingDust commented on lib/routes/fnal/news.js
> +                    item.pubDate = content('span[datetime]').length > 0 ? Date.parse(content('span[datetime]').attr('datetime')) : parseDate(content('.teaser-date').text(), 'MM/DD/YY');
<meta property="article:published_time" content="2021-07-16T12:49:44+00:00

2021-07-20 08:25 UTC, SettingDust approved these changes

2021-08-12 06:43 UTC, NeverBehave approved these changes

2021-08-12 06:59 UTC, NeverBehave approved these changes

2021-08-12 07:39 UTC, merged