fix: facebook fetch error
DIYgod/RSSHub pull request #7377
Opened 2021-04-12 17:49 UTC by aa900031

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/facebook/page/ykohmk
/facebook/page/FGOwarehouse
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [ ] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

主要修改兩個方向：
- HTML 結構
- Cookie 策略

### HTML 結構
因 FB 更改結構了，所以現有的查不到東西

### Cookie 策略
FB 對於頁面需要有 Cookie 讓他們識別才允許查看內容，不然就會導入登入頁
這邊的解法如下：
1. 每次 router 進來後先打一次 fb 首頁，並由 response.header.Set-Cookie 取得 cookie 值
2. 把 cookie 帶入每個 request 裡

2021-06-09 03:41 UTC, NeverBehave requested changes

2021-06-09 03:41 UTC, NeverBehave commented on lib/routes/facebook/page.js
> +    const cookie = await fetchCookie();
Cookie是每一次访问都需要重新生成吗？如果可以复用的话可以加入缓存

2021-06-09 06:37 UTC, aa900031 commented on lib/routes/facebook/page.js
> +    const cookie = await fetchCookie();
已加入 cache

2021-07-10 22:45 UTC, SettingDust commented
生成结果都是空的？

2021-07-11 12:35 UTC, aa900031 commented
@SettingDust 單純看 vercel preview 會是空的，但 local 無法重現，感覺是 vercel 發請求然後被 facebook 擋下來
我 local 這邊跑起來的樣子是這樣：
<img width="1584" alt="截圖 2021-07-11 下午8 33 44" src="https://user-images.githubusercontent.com/1111538/125195238-681b1600-e287-11eb-80dc-24cc944122b1.png">

2021-07-12 01:41 UTC, SettingDust commented
> @SettingDust 單純看 vercel preview 會是空的，但 local 無法重現，感覺因為從 vercel 主機發送請求然後被 facebook 擋下來
> 
> 實際上 local 這邊跑起來的樣子是這樣：
> <img width="1584" alt="截圖 2021-07-11 下午8 33 44" src="https://user-images.githubusercontent.com/1111538/125195238-681b1600-e287-11eb-80dc-24cc944122b1.png">

如果抓取出问题，请给出相应错误提示

2022-02-01 14:35 UTC, TonyRL commented
Resolved merge conflict for you but it is indeed outputting empty title/description on my local setup.
Please double check.

<details>

<summary> Screenshot </summary>

![Screenshot](https://user-images.githubusercontent.com/11386903/151987845-27bdfc9d-622f-4391-9978-531f5766a66c.png)

</details>

2022-02-01 14:38 UTC, TonyRL requested changes

2022-02-01 14:38 UTC, TonyRL commented on lib/routes/facebook/page.js
> +    cache.tryGet(cacheKey, async () => {
The value here from tryGet is ignored. Probably missing a `return`.

2023-03-19 20:58 UTC, DIYgod commented
pr 时间过长，将先被关闭，如果还有疑问可以随时在下面继续讨论

2023-03-19 20:58 UTC, closed without merging