feat(route): add 网易新闻人间
DIYgod/RSSHub pull request #7391
Opened 2021-04-15 00:31 UTC by nczitzk

## 该 PR 相关 Issue / Involved issue

Close #7388

## 完整路由地址 / Example for the proposed route(s)

```routes
/netease/renjian/texie
/netease/renjian/jishi
/netease/renjian/daxie
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [x] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-04-27 02:37 UTC, pplps commented
感谢nczitzk和rsshub，已经可以使用特写和记事的rss了，我看有一个测试failed，不知道影响不影响
https://rsshub-do-not-use-itoofpd9l-diy.vercel.app/netease/renjian/daxie - **Failed**

2021-04-28 02:29 UTC, nczitzk commented
> 感谢nczitzk和rsshub，已经可以使用特写和记事的rss了，我看有一个测试failed，不知道影响不影响
> https://rsshub-do-not-use-itoofpd9l-diy.vercel.app/netease/renjian/daxie - **Failed**

修复了大写 😃

2021-05-12 19:21 UTC, NeverBehave requested changes

2021-05-12 19:21 UTC, NeverBehave commented on lib/routes/netease/renjian.js
> +const date = require('@/utils/date');
我们近期对日期工具类进行了调整，请参考这个指南调整PR https://docs.rsshub.app/joinus/pub-date.html

2021-09-07 07:27 UTC, curryxiong commented
啥也看不懂🌝🌝

2021-09-08 04:11 UTC, SettingDust requested changes

2021-09-08 04:11 UTC, SettingDust commented on lib/routes/netease/renjian.js
> +    const category = ctx.params.category || 'texie';
```suggestion
    const category = ctx.params.category ?? 'texie';
```

2021-09-08 04:11 UTC, SettingDust commented on lib/routes/netease/renjian.js
> +                await ctx.cache.tryGet(item.link, async () => {
提交前 lint
```suggestion
            (item) =>
                ctx.cache.tryGet(item.link, async () => {
```

2021-09-08 04:11 UTC, SettingDust commented on lib/routes/netease/renjian.js
> +                    item.pubDate = Date.parse(content('.pub_time').text() || content('.post_info').text().split('来源:')[0].trim());
```suggestion
                    item.pubDate = Date.parse(content('.pub_time').text() ?? content('.post_info').text().split('来源:')[0].trim());
```

2021-09-08 04:11 UTC, SettingDust commented on lib/routes/netease/renjian.js
> +                    item.description = content('#endText').html() || content('#content').html();
```suggestion
                    item.description = content('#endText').html() ?? content('#content').html();
```

2021-09-08 04:11 UTC, SettingDust commented on lib/routes/netease/renjian.js
> +            .slice(0, 15)
这两个 slice 的目的是？

2021-09-08 16:11 UTC, SettingDust approved these changes

2021-09-08 16:11 UTC, SettingDust commented on docs/new-media.md
> +
这是？

2021-09-08 23:12 UTC, nczitzk commented on docs/new-media.md
> +
合并文档冲突出错了 😂

2021-09-23 05:13 UTC, NeverBehave commented
由于 #8236
旧版本的新路由请求将会被关闭，请按照新版路由规范修改后重新开启，谢谢！
需要帮助请在讨论下留言，我们可以协助迁移

2021-09-23 05:13 UTC, closed without merging