feat(route): add 时事一点通资讯
DIYgod/RSSHub pull request #7462
Opened 2021-05-02 08:34 UTC by nczitzk

## 该 PR 相关 Issue / Involved issue

Close #7457

## 完整路由地址 / Example for the proposed route(s)

```routes
/ssydt/article
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [x] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-05-06 07:27 UTC, SettingDust requested changes

2021-05-06 07:27 UTC, SettingDust commented on lib/routes/ssydt/article.js
> +        link: `${rootUrl}/article/${item.id}`,
**建议**使用 id 作为 guid
```suggestion
        link: `${rootUrl}/article/${item.id}`,
        guid: item.id,
```

2021-05-06 07:27 UTC, SettingDust commented on lib/routes/ssydt/article.js
> +        pubDate: date(item.gmtCreate),
忽略了来源的秒，等 #7438 合并后需要再检查

2021-05-06 07:27 UTC, SettingDust commented on lib/routes/ssydt/article.js
> +    const response = await got({
_可以使用 got(url) 发出 get 请求_

2021-05-12 04:35 UTC, NeverBehave requested changes
我们近期对日期工具类进行了调整，请参考这个指南调整PR https://docs.rsshub.app/joinus/pub-date.html

2021-07-22 08:09 UTC, Zayia commented
大佬们，求继续匹配啊

2021-07-25 02:29 UTC, SettingDust approved these changes

2021-07-25 04:20 UTC, Zayia commented
大佬们，能分类显示文章不

2021-07-25 04:30 UTC, SettingDust commented
> 大佬们，能分类显示文章不

你有需求就去开 issue，这里不是地方，需求也描述清楚，别让人猜

2021-08-12 07:47 UTC, NeverBehave approved these changes

2021-08-12 07:57 UTC, merged