fix(route): changba user
DIYgod/RSSHub pull request #7538
Opened 2021-05-16 12:11 UTC by xizeyoupan

## 该 PR 相关 Issue / Involved issue

Close #7470

## 完整路由地址 / Example for the proposed route(s)

```routes
/changba/skp6hhF59n48R-UpqO3izw
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 目标是否有提供日期？ Is there a date in the source?
  - [ ] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [ ] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-09-02 13:29 UTC, SettingDust requested changes

2021-09-02 13:29 UTC, SettingDust commented on lib/routes/changba/user.js
> +const headers = { 'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1' };
使用默认 ua 无法访问？

2021-09-02 13:29 UTC, SettingDust commented on lib/routes/changba/user.js
> +                        method: 'get',
写两个 get？
```suggestion
                    const result = await got({
                        method: 'get',
```

2021-09-02 13:29 UTC, SettingDust commented on lib/routes/changba/user.js
> +                60 * 60 * 24
不使用默认过期时间的原因是？

2021-09-02 13:29 UTC, SettingDust commented on lib/routes/changba/user.js
>              return Promise.resolve(single);
这种写法应该过不了 lint 吧？

```suggestion
            return {
                title: $('.work-title').text(),
                description,
                link,
                author,
                itunes_item_image,
                enclosure_url: mp3,
                enclosure_type: 'audio/mpeg',
            };
```

2021-09-02 14:57 UTC, xizeyoupan commented on lib/routes/changba/user.js
> +const headers = { 'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1' };
确实

2021-09-02 14:57 UTC, xizeyoupan commented on lib/routes/changba/user.js
> +                        method: 'get',
typo😳

2021-09-02 14:58 UTC, xizeyoupan commented on lib/routes/changba/user.js
> +                60 * 60 * 24
获取歌曲id，理论上不会更新

2021-09-02 15:07 UTC, xizeyoupan commented on lib/routes/changba/user.js
>              return Promise.resolve(single);
远古 PR 了属于是，lint 已经改了好多次了。
![image](https://user-images.githubusercontent.com/44920131/131868765-5c5a9b2d-f8e1-4f5f-ad9c-bb8ced91ef9b.png)

2022-01-28 09:16 UTC, xizeyoupan commented
@DIYgod 您好！~~由于总是先处理最新的，~~ 这个远古PR当年不知道为什么迷失在了时间乱流中，现在我已经迁移到了v2，如果没问题的话，斗胆@您有空merge一下。

2022-01-28 11:03 UTC, TonyRL requested changes

2022-01-28 11:03 UTC, TonyRL commented on lib/v2/changba/user.js
> +const headers = { 'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1' };
RSSHub's UA can also be changed via envs.
https://github.com/DIYgod/RSSHub/blob/bdb0e125d28ee4048418ded3ccd083feedbb326e/lib/config.js#L40

Consider using that value if envs.UA is set.

2022-01-28 11:09 UTC, TonyRL requested changes

2022-01-28 11:09 UTC, TonyRL commented on lib/v2/changba/radar.js
> +                target: `/changba/:id`,
```suggestion
                docs: 'https://docs.rsshub.app/social-media.html#chang-ba',
                source: ['/s/:userid'],
                target: `/changba/:userid`,
```

2022-01-28 11:09 UTC, TonyRL commented on lib/v2/changba/user.js
> +const headers = { 'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1' };
RSSHub's UA can also be changed via envs.
https://github.com/DIYgod/RSSHub/blob/bdb0e125d28ee4048418ded3ccd083feedbb326e/lib/config.js#L40
Consider using that value if `envs.UA` is set.

2022-01-28 11:09 UTC, TonyRL commented on lib/v2/changba/user.js
> +            const mp3 = `http://upscuw.changba.com/${songid}.mp3`;
```suggestion
            const mp3 = `https://upscuw.changba.com/${songid}.mp3`;
```
HTTPS is prefered

2022-01-28 11:09 UTC, TonyRL commented on lib/v2/changba/user.js
> +            return Promise.resolve(single);
See https://github.com/DIYgod/RSSHub/pull/7538#discussion_r701082982

2022-02-01 15:41 UTC, merged