fix: category filters for i-CABLE
DIYgod/RSSHub pull request #7557
Opened 2021-05-21 05:58 UTC by tpnonthealps

## 该 PR 相关 Issue / Involved issue

Close #7263

## 完整路由地址 / Example for the proposed route(s)

```routes
/icable/local
/icable/international
/icable/china
/icable/sports
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [ ] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 目标是否有提供日期？ Is there a date in the source?
  - [ ] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [ ] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

The `finance` filter has been deprecated. The document has also been updated.

不再提供 `finance` 分類。文件亦已更新。

2021-06-26 19:27 UTC, tpnonthealps reviewed
Works well.
運作暢順。

2021-07-20 08:53 UTC, SettingDust requested changes
日期需要按照标准处理

2021-08-03 22:37 UTC, tpnonthealps commented
> 日期需要按照标准处理

已規範化。

2021-08-05 00:00 UTC, SettingDust commented on lib/routes/icable/category.js
> +            btext = `${ptext.substring(0, 100)}…`;
没有裁剪的理由吧？

2021-08-05 12:45 UTC, tpnonthealps commented on lib/routes/icable/category.js
> +            btext = `${ptext.substring(0, 100)}…`;
輸出簡訊（brief）所以剪100字，預設默認的option是全文。

2021-08-12 08:31 UTC, NeverBehave commented on lib/routes/icable/category.js
> +            btext = `${ptext.substring(0, 100)}…`;
https://docs.rsshub.app/traditional-media.html#i-cable-you-xian-xin-wen 文档里面两项都是全文输出，并没有简讯选项

2021-08-12 08:32 UTC, NeverBehave requested changes
默认请提供全文

2021-08-15 15:32 UTC, tpnonthealps commented on lib/routes/icable/category.js
> +            btext = `${ptext.substring(0, 100)}…`;
docs已添加

2021-08-15 15:33 UTC, tpnonthealps commented
> 默认请提供全文

現時默認是提供含圖全文，純文字全文以及簡訊是可選項。

2021-08-21 04:03 UTC, NeverBehave requested changes

2021-08-21 04:03 UTC, NeverBehave commented on lib/routes/icable/category.js
> +        // pubDate: `${item.created_at} +0800`, // 文章发布时间
清理无用注释

2021-08-21 04:03 UTC, NeverBehave commented on lib/routes/icable/category.js
> +            btext = `${ptext.substring(0, 100)}…`;
简讯是网站提供的还是因为自己需要所以写的？如果是后者能在其他相关路由找到例子吗？

2021-08-21 04:29 UTC, tpnonthealps commented
簡訊是自己需求，其他路由不清楚，但我之後修 https://github.com/DIYgod/RSSHub/pull/7564 應該也會做一個簡訊option。

2021-08-21 07:43 UTC, NeverBehave commented
如果有多个需求，请尝试做成中间件，这种选项不建议作为url一部分

2021-09-24 03:37 UTC, NeverBehave approved these changes

2021-09-24 03:38 UTC, merged