feat(route): add Font Story (DynaC TW)
DIYgod/RSSHub pull request #7565
Opened 2021-05-23 03:48 UTC by tpnonthealps

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/fontstory
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [x] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [x] 目标是否有提供日期？ Is there a date in the source?
  - [x] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [x] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-06-27 07:45 UTC, tpnonthealps reviewed
Resolved conflicts.
已解決合併衝突。

2021-07-20 08:47 UTC, SettingDust commented
> Resolved conflicts.
> 已解決合併衝突。

修改一下错误

2021-08-03 20:47 UTC, tpnonthealps commented
> > Resolved conflicts.
> > 已解決合併衝突。
> 
> 修改一下错误

重新遞交了一次commit，已經通過所有測試。自動測試有時會無故失敗，重新遞交又通過。

2021-08-05 00:04 UTC, SettingDust requested changes

2021-08-05 12:47 UTC, tpnonthealps commented on lib/routes/fontstory/tw.js
> +                    pubDate: timezone(new Date(parseDate($('div.date-txt.col-xs-4.tc-gray.text-right').text(), 'YYYY年MM月DD日')), +8),
謝，已修復。

2021-08-05 12:59 UTC, SettingDust requested changes

2021-08-05 12:59 UTC, SettingDust commented on lib/routes/fontstory/tw.js
> +            await ctx.cache.tryGet(line, async () => {
```suggestion
        (line) =>
            ctx.cache.tryGet(line, async () => {
```

2021-08-05 12:59 UTC, SettingDust commented on lib/routes/fontstory/tw.js
> +    return await Promise.all(now);
```suggestion
    return Promise.all(now);
```

2021-08-05 12:59 UTC, SettingDust commented on lib/routes/fontstory/tw.js
> +async function getArticle(ctx, list) {
```suggestion
function getArticle(ctx, list) {
```

2021-08-05 12:59 UTC, SettingDust commented on lib/routes/fontstory/tw.js
> +    const rss = await getArticle(ctx, list.slice(0, 5));
无副作用的情况下，不要限制抓取数量
```suggestion
    const rss = await getArticle(ctx, list);
```

2021-08-05 14:25 UTC, tpnonthealps commented on lib/routes/fontstory/tw.js
> +    const rss = await getArticle(ctx, list.slice(0, 5));
那樣會被判定為超時，請看 https://github.com/DIYgod/RSSHub/pull/7565#issuecomment-846497163 和 https://github.com/DIYgod/RSSHub/pull/7565#issuecomment-846497962

2021-08-05 14:44 UTC, SettingDust requested changes

2021-08-05 14:44 UTC, SettingDust commented on lib/routes/fontstory/tw.js
> +                description: desc,
![image](https://user-images.githubusercontent.com/19922286/128369712-7682d9f2-75f0-4cc0-bc74-d72129b680a3.png)
![image](https://user-images.githubusercontent.com/19922286/128369722-7c79dd05-6668-4a08-bdca-e052cfba82af.png)
内容抓到了些奇怪的东西

2021-08-12 08:35 UTC, tpnonthealps commented on lib/routes/fontstory/tw.js
> +                description: desc,
已解決

2021-08-12 08:35 UTC, tpnonthealps commented
Vercel部署壞了，沒法驗證一次抓10篇會否timeout。

2021-08-15 10:09 UTC, tpnonthealps commented
部署未現timeout，可安心合併。

2021-08-21 04:00 UTC, NeverBehave requested changes

2021-08-21 04:00 UTC, NeverBehave commented on lib/routes/fontstory/tw.js
> +            // time
清理一下无用注释

2021-08-21 04:21 UTC, SettingDust commented
无法访问？

2021-08-21 04:22 UTC, tpnonthealps commented
> 无法访问？

現在Vercel慢到抓10篇都超時…

2021-08-21 07:44 UTC, NeverBehave approved these changes

2021-08-21 07:44 UTC, merged