增加小宇宙播客支持
DIYgod/RSSHub pull request #7592
Opened 2021-05-27 07:04 UTC by hondajojo

## 该 PR 相关 Issue / Involved issue

Close #6941

## 完整路由地址 / Example for the proposed route(s)

```routes
/xiaoyuzhou/podcast/6021f949a789fca4eff4492c
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [x] 目标是否有提供日期？ Is there a date in the source?
  - [ ] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [ ] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note
有些播客只host在小宇宙上，并不提供rss

2021-06-25 00:48 UTC, fengkx approved these changes

2021-11-27 07:19 UTC, DIYgod approved these changes

2021-12-09 05:51 UTC, hxgdzyuyi commented
episodes 如果不存在图片的时候 image 这个属性会不存在。比如以下这个case

https://www.xiaoyuzhoufm.com/podcast/61083da160cf26c1a67e81f5

这时候可能需要使用 上面 podcast 属性的 image 来做替代。 cc @hondajojo

2021-12-15 11:14 UTC, lfkdsk commented
使用 web 页面 api 抓取的 podcast 集数是有限的，可能还是需要利用 token 请求 api。

2022-02-01 15:58 UTC, TonyRL requested changes
v2 script standard https://github.com/DIYgod/RSSHub/discussions/8236

Please resolve merge conflicts

2022-02-20 18:58 UTC, TonyRL commented
Superseded by https://github.com/DIYgod/RSSHub/pull/9160

2022-02-20 18:58 UTC, closed without merging