feat(route): 公众号（Telegram 频道来源）增加筛选
DIYgod/RSSHub pull request #7648
Opened 2021-06-04 22:16 UTC by Rongronggg9

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/wechat/tgchannel/lifeweek
/wechat/tgchannel/darhcenssr
/wechat/tgchannel/darhcenssr/东方财富Choice数据
/wechat/tgchannel/darhcenssr/Python之禅
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [ ] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 目标是否有提供日期？ Is there a date in the source?
  - [ ] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [ ] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

公众号（Telegram 频道来源）原先需要筛选公众号时只能通过 RSSHub 通用参数筛选作者实现，这主要带来了两个问题：
* feed title 永远是频道名
* post title 永远含有公众号名

这在只需要筛选一个公众号时，将会带来并不美观的结果。然而，考虑到 Telegram 的公开频道/群组配额是高度有限的，将多个公众号绑定到同一个频道，是常见的做法；在订阅时，希望各公众号能分开订阅，也是常见的需求。

基于此，这个 PR 的主要改进有：
* 增加可选参数 mpName 用于筛选，解决以上问题
* 顺手修复公众号名带空格时会被截断的 bug（暂无示例路由提供）
* 增大了对消息列表的切片大小（因许多公众号推送的时间都固定在某几个整点，切片太小很可能遗漏）

2021-07-16 01:36 UTC, SettingDust commented
格式的标准是怎么确定的？

2021-08-30 10:07 UTC, Rongronggg9 commented
@SettingDust 不好意思这么久才回复。我没能理解您的意思，可否请您详细说明一下呢？

2021-12-02 21:22 UTC, SukkaW commented on lib/routes/tencent/wechat/tgchannel.js
> +        title: mpName ? mpName : $('.tgme_channel_info_header_title').text(),
```suggestion
        title: mpName || $('.tgme_channel_info_header_title').text(),
```

2021-12-02 21:34 UTC, Rongronggg9 commented on lib/routes/tencent/wechat/tgchannel.js
> +        title: mpName ? mpName : $('.tgme_channel_info_header_title').text(),
fixed.

2021-12-03 03:15 UTC, SettingDust requested changes
https://github.com/DIYgod/RSSHub/blob/bad819cac844c237e82103dccfe6a09dfb226810/lib/routes/tencent/wechat/tgchannel.js#L61

也一样需要修改，不要 Promise.resolve

2021-12-03 03:15 UTC, SettingDust commented on lib/routes/tencent/wechat/tgchannel.js
> +    const mpName = ctx.params.mpName || '';
```suggestion
    const mpName = ctx.params.mpName ?? '';
```

新语法好些？

2021-12-03 03:15 UTC, SettingDust commented on lib/routes/tencent/wechat/tgchannel.js
>                  let title = item.find('.tgme_widget_message_text > a:nth-child(5)').text() || item.find('.tgme_widget_message_text > a:nth-child(2)').text();
```suggestion
                let title = item.find('.tgme_widget_message_text > a:nth-child(5)').text() ?? item.find('.tgme_widget_message_text > a:nth-child(2)').text();
```

2021-12-03 03:15 UTC, SettingDust commented on lib/routes/tencent/wechat/tgchannel.js
> +                        return Promise.resolve(null);
```suggestion
                        return;
```

这里 return null 有什么标准吗？
async 的返回值就是 promise，为什么包裹一层

2021-12-03 03:15 UTC, SettingDust commented on lib/routes/tencent/wechat/tgchannel.js
> +        title: mpName || $('.tgme_channel_info_header_title').text(),
```suggestion
        title: mpName ?? $('.tgme_channel_info_header_title').text(),
```

2021-12-03 03:20 UTC, SettingDust commented
> @SettingDust 不好意思这么久才回复。我没能理解您的意思，可否请您详细说明一下呢？

来自于 TG 频道的公众号转发信息的格式的标准在哪里

2021-12-03 18:48 UTC, Rongronggg9 commented on lib/routes/tencent/wechat/tgchannel.js
> +                        return Promise.resolve(null);
在路由填入 `mpName` 开启了公众号名筛选时，就会判断 `author`（在消息中提取的公众号名）是不是与 `mpName` 的一致，不一致就 return，不再继续后面的流程；在输出时会被 filter 掉，就达到了筛选的效果。

2021-12-03 18:54 UTC, Rongronggg9 commented
@SettingDust 
> 来自于 TG 频道的公众号转发信息的格式的标准在哪里

格式的 parse 原本并非是我写的，这个主要是根据剖析 efb 输出的格式在 channel preview 里如何展现来确定的。我在注释里写上了格式的构成，并稍微改进了一下 parse，请查阅。

2021-12-04 01:34 UTC, SettingDust commented
> @SettingDust
> 
> > 来自于 TG 频道的公众号转发信息的格式的标准在哪里
> 
> parse 部分原本并非是我写的，这个主要是根据剖析 efb 输出的格式在 channel preview 里如何展现来确定的。我在注释里写上了格式的构成，并稍微改进了一下 parse 部分，请查阅。
> 
> efb 长期以来没有变更过输出格式，可以认为输出格式是稳定的。
> 
> 如果用户不用 pypi 上的包而是直接使用自行修改过的源代码，确实可能导致格式的变更（主要是 emoji 数目的变化），但这不是常见行为。对此我也做了一些预防性规避。 获取文章链接: `a:nth-child(5)` | `a:nth-child(2)` ---> `a:nth-of-type(2)` 获取公众号名: 完整文本里找半角空格和半角冒号夹着的文字 ---> 第一个换行前面的裸文本里找半角空格和半角冒号夹着的文字

最好在文档中注明或链接到规范页面

2021-12-04 02:06 UTC, Rongronggg9 commented
> > @SettingDust
> > 
> > > 来自于 TG 频道的公众号转发信息的格式的标准在哪里
> > 
> > parse 部分原本并非是我写的，这个主要是根据剖析 efb 输出的格式在 channel preview 里如何展现来确定的。我在注释里写上了格式的构成，并稍微改进了一下 parse 部分，请查阅。
> > 
> > efb 长期以来没有变更过输出格式，可以认为输出格式是稳定的。
> > 
> > 如果用户不用 pypi 上的包而是直接使用自行修改过的源代码，确实可能导致格式的变更（主要是 emoji 数目的变化），但这不是常见行为。对此我也做了一些预防性规避。 获取文章链接: `a:nth-child(5)` | `a:nth-child(2)` ---> `a:nth-of-type(2)` 获取公众号名: 完整文本里找半角空格和半角冒号夹着的文字 ---> 第一个换行前面的裸文本里找半角空格和半角冒号夹着的文字
> 
> 最好在文档中注明或链接到规范页面

文档中本来就有注明 [该路由必须使用 efb 绑定的频道](https://github.com/DIYgod/RSSHub/blame/47fe822f657abae5c37f8220cbd91114a9b60fe7/docs/new-media.md#L2767) 。从历史上来讲，这个路由从一开始就是专为 efb 量身定制的。
efb 没有给出输出的规范，因此没有规范页面可附上。

2022-01-22 19:03 UTC, merged

2022-02-22 19:45 UTC, vlcheng commented
当前路由注释的格式说明和我用**ETM v2.2.4**生成的公众号文章格式有出入：

> // 若频道订阅多于一个公众号：
// 第 1 个元素: \<i>\<b>${emoji(标注消息来源于什么 slave，这里是表示微信的对话气泡)}</b></i>
// 第 2 个元素: \<i>\<b>${emoji(标注对话类型，这里是表示私聊的半身人像)</b></i>
**// 第 3 个元素: \<a href="${?q=%23url-encoded公众号名}">"${#公众号名}"</a>**  ~~// 裸文本: (半角空格)${公众号名}(半角冒号)~~  
**// 裸文本: (半角冒号)**  ~~// 第 3 个元素: \<br />~~  
// 第 **4**  ~~3~~ 个元素: \<br>
// 第 **5**  ~~4~~ 个元素: \<a href="${用于 link priview 的预览图 url}">\<i>\<b>${emoji(链接)}</b></i></a>
// 第 **6**  ~~5~~ 个元素: \<a href="${文章 url}">${文章标题}</a>
// (余下是文章简介，一般是裸文本，这里用不到)

区别在于公众号名称的位置和格式，在我这里是`<i...></i><i...></i><a href="?q=%2336%E6%B0%AA">#36氪</a>:<br><a...></a><a...></a>`，因此这个路由对我来说处于不可用状态。

由于只会一点野生js，只能尝试将代码作出修改来适配了我这个格式：
```
let author;
const reg = /\?q=%23/
const a_node = item.find('.tgme_widget_message_text > a:nth-of-type(1)'); // 获取第一个a标签
if (reg.test(a_node.attr('href'))) {
    // 如果第一个a标签包含了hashtag，说明这个频道订阅了多个公众号
    author = a_node.text().slice(1);  // 去掉#号提取公众号名
    if (mpName && author !== mpName) {
        // 指定了要筛选的公众号名，且该文章不是该公众号发的
        return; // 丢弃
    }
    title_elem = item.find('.tgme_widget_message_text > a:nth-of-type(3)');  // 一对多绑定，标题在第三个a标签
} else if (a_node.children().hasClass('emoji')){
    // 绑定了一个公众号
    if (mpName) { author = mpName; }  // 其实好像没什么用，因为一对一绑定不会显示公众号名称
    title_elem = item.find('.tgme_widget_message_text > a:nth-of-type(2)');  // 一对一绑定，标题在第二个a标签
}
if (title_elem.length === 0) {
    // a标签的数量小于2，这可能是公众号发的服务消息，丢弃它
    return;
}
const title = title_elem.text();
const link = title_elem.attr('href');
```
**另外还有一个关于mpName存在意义的讨论：**
- 在一对一绑定的频道中，efb转发消息并不会显示公众号名称，所以mpName没有存在的意义。并且author建议使用频道的title，而不是尝试从消息里面获取。
- 在一对多绑定的频道中，由于Telegram只会直接返回最多20条消息，可能遇到一些公众号一次性发7、8篇文章而淹没其他账号近期推送的尴尬情况，把mpName用于请求url中可以有效避免这种尴尬：
```
const { data } = await got.get(`https://t.me/s/${id}${mpName ? `?q=%23${mpName}` : ''}`);
```
不过有一个缺点，受到Telegram目前不支持同时搜索多个hashtag的限制，如果想要在一个订阅地址中包含多个公众号，就只能用会`filter_author`参数并且忍受上边提到的尴尬（尽管可以通过单开一个频道来解决，但是不够优雅 :(

2022-02-22 20:07 UTC, Rongronggg9 commented
@vlcheng
> 区别在于公众号名称的位置和格式，在我这里是`<i...></i><i...></i><a href="?q=%2336%E6%B0%AA">#36氪</a>:<br><a...></a><a...></a>`，因此这个路由对我来说处于不可用状态。

你使用了 efb-patch-middleware，它导致了输出格式的变化。作一些修改可以使两种输出格式均可被接受，有时间的时候我再提个 PR。

> 把mpName用于请求url中可以有效避免这种尴尬：

efb-patch-middleware 只是简单地在公众号名前加 `#`，并不考虑这样的 hashtag 是否合法，是否不会在中间被截断，因此可能并非所有公众号名都可使用 hashtag 查询。
好消息是，如果不使用 efb-patch-middleware，由于 efb 一定会在公众号名后面加换行，因此搜索公众号名不受 Telegram 分词依赖空字符的影响，是可行的。
坏消息是，如果使用 efb-patch-middleware，加上去的 `#`会影响后面的字符的搜索，因此关键字必须带上 `#`。
显然，这两种情况下，搜索关键字各自不同，共存有难度。

2022-02-22 21:29 UTC, vlcheng commented
> 你使用了 efb-patch-middleware，它导致了输出格式的变化。在我的使用中，它有个致命的问题：有几率漏掉一些消息的发送者标头。作一些修改可以使两种输出格式均可被接受，有时间的时候我再提个 PR。

2022-02-22 21:31 UTC, vlcheng commented
> 你使用了 efb-patch-middleware，它导致了输出格式的变化。在我的使用中，它有个致命的问题：有几率漏掉一些消息的发送者标头。作一些修改可以使两种输出格式均可被接受，有时间的时候我再提个 PR。

原来如此！但是 efb-patch-middleware 诸如自动已读等功能又很实用，实在是难以放弃使用。

2022-02-25 02:09 UTC, Rongronggg9 commented
@vlcheng 
#9183

2022-03-08 08:33 UTC, fhyoga commented
hello，有聚合的公众号tg channel分享吗？手里两个微信号都不能web登录。。自建不了这套路由，可以付费使用