fix(route):天天基金
DIYgod/RSSHub pull request #7651
Opened 2021-06-05 19:38 UTC by zidekuls

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/eastmoney/ttjj/user/4009385504694174
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [ ] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 目标是否有提供日期？ Is there a date in the source?
  - [ ] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [ ] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

修复之前路由失效的问题

2021-06-10 19:19 UTC, NeverBehave requested changes
路由失效为什么突然调整了路由？

2021-06-10 22:55 UTC, zidekuls commented
> 路由失效为什么突然调整了路由？

因为觉得原来的分类有点问题，天天基金是东方财富下面的一个分支，觉得再加一层会比较好

2021-06-23 03:14 UTC, zidekuls commented
@NeverBehave Hi，请问还有什么需要修改的吗？

2021-07-01 01:58 UTC, ryuzheng commented
@NeverBehave @zidekuls 抱歉打扰两位了，我建议在文档中将名字更改成“东方财富/天天基金”或者“东方财富（天天基金）”，然后route就保持为eastmoney这一层就好了；

因为我查找文档时找的“东方财富”没找到，而查“天天财富”才发现这个路由，因为我在网页上是看到东方财富的，所以先查的东方财富。

![CleanShot 2021-07-01 at 09 56 52@2x](https://user-images.githubusercontent.com/5512323/124053419-c871b280-da52-11eb-8477-adb77026be81.png)


希望尽快修复这个路由，感谢！！！

2021-07-02 07:01 UTC, NeverBehave requested changes

2021-07-02 07:01 UTC, NeverBehave commented on lib/routes/eastmoney/ttjj/user.js
> +                    pubDate: item.post_display_time,
传入的对象应当是date object, 与服务器时间保持一致（定义时区）
参阅：https://docs.rsshub.app/joinus/pub-date.html

2021-07-02 07:03 UTC, NeverBehave requested changes

2021-07-02 07:03 UTC, NeverBehave commented on docs/finance.md
应当使用网站名字作为首要标题，板块作为附属标题

2021-07-02 08:27 UTC, zidekuls commented on lib/routes/eastmoney/ttjj/user.js
> +                    pubDate: item.post_display_time,
了解

2021-07-02 08:33 UTC, zidekuls commented on docs/finance.md
还有两个问题：
1. 这句的意思是，我在finance文档中用“东方财富”作为首要标题，“天天基金”作为附属标题吗？
2. 此pr中的代码文件夹结构是否保持不变？

2021-07-02 22:46 UTC, NeverBehave commented on docs/finance.md
对，只是文档标题问题

2021-07-03 12:22 UTC, zidekuls commented
@NeverBehave done

2021-10-05 09:42 UTC, NeverBehave requested changes
由于路由冲突，可以选择参照 #8236 更新到新版
或者处理冲突后可以合并

2022-02-01 16:30 UTC, TonyRL requested changes
v2 script standard https://github.com/DIYgod/RSSHub/discussions/8236

2022-02-21 21:02 UTC, merged