fix: infzm timezone
DIYgod/RSSHub pull request #7695
Opened 2021-06-14 14:51 UTC by SeanChao

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/infzm/5
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [ ] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [x] 目标是否有提供日期？ Is there a date in the source?
  - [x] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [x] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

This commit fixed the previously unhandled timezone issue.

2021-06-22 07:22 UTC, SettingDust requested changes

2021-06-22 07:22 UTC, SettingDust commented on lib/routes/infzm/news.js
> +            const date = parseDate(`${publish_time}+0800`, 'YYYY-MM-DD HH:mm:SSZZ');
这个日期格式化的行为是不是不太对啊？如果你想解析时区，推荐用 https://docs.rsshub.app/joinus/pub-date.html#shi-yong-gong-ju-lei-timezone

2021-06-22 08:24 UTC, SeanChao commented on lib/routes/infzm/news.js
> +            const date = parseDate(`${publish_time}+0800`, 'YYYY-MM-DD HH:mm:SSZZ');
我参考过这个链接，因为网站上显示的时间一定是东八区的，我按照 dayjs 提供的格式硬设为东八区了。不这样处理可能会因为服务器时区的不同产生错误的时间

2021-07-21 07:23 UTC, SettingDust approved these changes

2021-08-12 07:43 UTC, NeverBehave commented on lib/routes/infzm/news.js
> +            const date = parseDate(`${publish_time}+0800`, 'YYYY-MM-DD HH:mm:SSZZ');
那使用工具类会产生错误的结果吗？

2021-08-12 09:53 UTC, SeanChao commented on lib/routes/infzm/news.js
> +            const date = parseDate(`${publish_time}+0800`, 'YYYY-MM-DD HH:mm:SSZZ');
这样处理后就没问题了

2021-08-13 22:34 UTC, SettingDust commented on lib/routes/infzm/news.js
> +            const date = parseDate(`${publish_time}+0800`, 'YYYY-MM-DD HH:mm:SSZZ');
工具类一样可以设置时区

2021-08-14 02:51 UTC, SeanChao commented on lib/routes/infzm/news.js
> +            const date = parseDate(`${publish_time}+0800`, 'YYYY-MM-DD HH:mm:SSZZ');
你们是说用 `timezone` 来设置时区吗？我当时只看了 dayjs 所以没有用，我可以试一下

2021-08-14 03:08 UTC, SeanChao commented on lib/routes/infzm/news.js
> +            const date = parseDate(`${publish_time}+0800`, 'YYYY-MM-DD HH:mm:SSZZ');
之前没仔细看链接的 anchor，抱歉了

2021-11-27 07:28 UTC, merged