fix(radar)(route): Pixiv search & Radar rules
DIYgod/RSSHub pull request #7700
Opened 2021-06-15 03:21 UTC by yindaheng98

## 该 PR 相关 Issue / Involved issue

Close #7699

并修改了排行榜和搜索的路由使之兼容新的Radar rules

## 完整路由地址 / Example for the proposed route(s)

```routes
/pixiv/ranking/daily
/pixiv/ranking/male
/pixiv/ranking/female
/pixiv/ranking/original
/pixiv/ranking/rookie
/pixiv/search/fgo
/pixiv/search/fgo/date
/pixiv/search/fgo/null/r18
/pixiv/search/fgo/null/safe
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [x] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 目标是否有提供日期？ Is there a date in the source?
  - [ ] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [ ] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-06-22 07:16 UTC, SettingDust requested changes

2021-06-22 07:16 UTC, SettingDust commented on docs/en/social-media.md
> +<RouteEn author="DIYgod" example="/pixiv/search/麻衣/popular/2" path="/pixiv/search/:keyword/:order?/:mode?" :paramsDesc="['keyword', 'rank mode, empty or other for time order, popular for popular orde
`empty or other o no filter` o? to?

empty or others to disable filter

2021-06-22 07:16 UTC, SettingDust commented on docs/social-media.md
> +<Route author="DIYgod" example="/pixiv/search/麻衣/popular/2" path="/pixiv/search/:keyword/:order?/:mode?" :paramsDesc="['关键词', '排序方式，popular 按热门度排序，空或其他任意值按时间排序', '过滤 R18 内容，safe 或 1 为只看非 R18 内容，r18 或
`空其他任意值为不过滤`
留空或其他值将不过滤

另外，这里和上面的英文文档建议把这两个（空不需要）做成表格，并且只保留 safe, r18, empty 在文档中，没必要在文档中保留0, 1, 2

2021-06-22 07:16 UTC, SettingDust commented on lib/routes/pixiv/ranking.js
> +    female: 'female',
male 和 female 行为不一致？

2021-06-22 10:02 UTC, yindaheng98 commented on lib/routes/pixiv/ranking.js
> +    female: 'female',
是bug，已修复

2021-06-25 02:45 UTC, yindaheng98 reviewed
reviewed

2021-06-25 02:47 UTC, SettingDust approved these changes

2021-06-27 00:02 UTC, merged