Add tag for docker build release
DIYgod/RSSHub pull request #7722
Opened 2021-06-17 12:26 UTC by stilleshan

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
NOROUTE
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [ ] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 目标是否有提供日期？ Is there a date in the source?
  - [ ] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [ ] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-06-17 23:06 UTC, NeverBehave requested changes
请同时更新文档，说明规则和使用方式

2021-06-18 01:38 UTC, stilleshan commented
> 请同时更新文档，说明规则和使用方式

由于这两年使用过程中,遇到过几次使用 watchtower 自动更新 latest 镜像,结果当时版本有bug,导致没有历史镜像可以回滚.

所以建议在 GitHub Action 的 workflows 里, docker 构建镜像时,同时多构建一个带有当天日期 tag 的镜像,方便于 docker 用户使用或回滚至指定稳定版本.

2021-06-18 06:03 UTC, NeverBehave commented
> > 请同时更新文档，说明规则和使用方式
> 
> 由于这两年使用过程中,遇到过几次使用 watchtower 自动更新 latest 镜像,结果当时版本有bug,导致没有历史镜像可以回滚.
> 所以建议在 GitHub Action 的 workflows 里, docker 构建镜像时,同时多构建一个带有当天日期 tag 的镜像,方便于 docker 用户使用或回滚至指定稳定版本.

没有问题，可以的话在文档内说明规则和使用方式，方便其他使用者参考

2021-06-18 06:06 UTC, stilleshan commented
> > > 请同时更新文档，说明规则和使用方式
> > 
> > 
> > 由于这两年使用过程中,遇到过几次使用 watchtower 自动更新 latest 镜像,结果当时版本有bug,导致没有历史镜像可以回滚.
> > 所以建议在 GitHub Action 的 workflows 里, docker 构建镜像时,同时多构建一个带有当天日期 tag 的镜像,方便于 docker 用户使用或回滚至指定稳定版本.
> 
> 没有问题，可以的话在文档内说明规则和使用方式，方便其他使用者参考

这个对使用者没有意义,所以无需文档,仅针对本仓库发布 docker 镜像时有用.

2021-06-18 09:21 UTC, NeverBehave commented
> > > > 请同时更新文档，说明规则和使用方式
> > > 
> > > 
> > > 由于这两年使用过程中,遇到过几次使用 watchtower 自动更新 latest 镜像,结果当时版本有bug,导致没有历史镜像可以回滚.
> > > 所以建议在 GitHub Action 的 workflows 里, docker 构建镜像时,同时多构建一个带有当天日期 tag 的镜像,方便于 docker 用户使用或回滚至指定稳定版本.
> > 
> > 
> > 没有问题，可以的话在文档内说明规则和使用方式，方便其他使用者参考
> 
> 这个对使用者没有意义,所以无需文档,仅针对本仓库发布 docker 镜像时有用.

意思是使用者不需要知道如何回滚和选择镜像吗？

2021-06-18 09:31 UTC, stilleshan commented
> > > > > 请同时更新文档，说明规则和使用方式
> > > > 
> > > > 
> > > > 由于这两年使用过程中,遇到过几次使用 watchtower 自动更新 latest 镜像,结果当时版本有bug,导致没有历史镜像可以回滚.
> > > > 所以建议在 GitHub Action 的 workflows 里, docker 构建镜像时,同时多构建一个带有当天日期 tag 的镜像,方便于 docker 用户使用或回滚至指定稳定版本.
> > > 
> > > 
> > > 没有问题，可以的话在文档内说明规则和使用方式，方便其他使用者参考
> > 
> > 
> > 这个对使用者没有意义,所以无需文档,仅针对本仓库发布 docker 镜像时有用.
> 
> 意思是使用者不需要知道如何回滚，选择镜像，以及编号意义吗？

是的,使用者一般都会,这也只是作为临时解决方案.如果非要添加文档,我只能再次提交一个新的 pr 来修改 docs/install 内的文档.是否需要再次提交 pr?

2021-06-18 09:35 UTC, NeverBehave commented
1 一般使用者只会复制指令
2 不需要新的pr，fork依然存在：直接推送你的fork的master分支，pr会自动更新

2021-06-18 09:46 UTC, stilleshan commented
> 1 一般使用者只会复制指令
> 2 不需要新的pr，fork依然存在：直接推送到你的fork的master分支，pr会自动更新

已更新文档

2021-06-18 17:58 UTC, NeverBehave requested changes
缺失英文文档

2021-06-18 17:58 UTC, NeverBehave commented on docs/install/README.md
> +### 镜像版本
相同内容出现了两次，在Docker相关部署处处开头直接说明相关规则即可

2021-06-19 01:54 UTC, stilleshan commented on docs/install/README.md
> +### 镜像版本
已更新

2021-06-19 05:26 UTC, NeverBehave approved these changes

2021-06-19 05:26 UTC, merged

2021-06-19 05:27 UTC, NeverBehave commented
Nicely done, thank you!