add 湖北软协，武汉东湖高新，武汉科技局
DIYgod/RSSHub pull request #7728
Opened 2021-06-18 06:43 UTC by tudou027

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/gov/hubei/hbsia/zxzx
/gov/wuhan/wehdz/tz
/gov/wuhan/wjj/tzgg
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [ ] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 目标是否有提供日期？ Is there a date in the source?
  - [ ] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [ ] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-06-22 06:58 UTC, SettingDust requested changes

2021-06-22 06:58 UTC, SettingDust commented on lib/routes/gov/hubei/hbsia.js
> +                    item.description = content('div.text').html();
![image](https://user-images.githubusercontent.com/19922286/122878347-3d196280-d36a-11eb-9de9-6a9fefbc5c4e.png)
过滤一下标题

2021-06-22 06:58 UTC, SettingDust commented on lib/routes/gov/wuhan/kjj.js
> +                    item.description = content('div.news_point').html();
过滤一下标题

2021-07-23 06:10 UTC, SettingDust requested changes

2021-07-23 06:10 UTC, SettingDust commented on lib/routes/gov/hubei/hbsia.js
> +        .slice(0, 10)
保留元素太少了

2021-07-23 06:10 UTC, SettingDust commented on lib/routes/gov/hubei/hbsia.js
> +                pubDate: span.text(),
正确格式化日期，参考文档

2021-07-23 06:10 UTC, SettingDust commented on lib/routes/gov/wuhan/kjj.js
> +                pubDate: span.text(),
正确格式化日期

2021-07-23 06:10 UTC, SettingDust commented on lib/routes/gov/wuhan/kjj.js
> +        .slice(0, 10)
保留太少，20 以上

2021-07-23 06:10 UTC, SettingDust commented on lib/routes/gov/wuhan/wehdz.js
> +        .slice(0, 10)
如上

2021-07-23 06:10 UTC, SettingDust commented on lib/routes/gov/wuhan/wehdz.js
> +                pubDate: span.text(),
如上

2021-07-23 08:27 UTC, SettingDust requested changes

2021-07-23 08:27 UTC, SettingDust commented on lib/routes/gov/hubei/hbsia.js
> +                pubDate: timezone(parseDate(span.text(), 'YYYY-MM-DD'), +8),
只有日期就不用处理时区了，对准确度没有帮助

2021-07-23 13:55 UTC, SettingDust approved these changes

2021-08-03 02:51 UTC, tudou027 commented
已处理所有问题

2021-08-12 07:45 UTC, NeverBehave approved these changes

2021-08-12 07:49 UTC, merged

2021-08-12 07:49 UTC, NeverBehave commented
Nice, thanks for your contribution!