feat(route) Twitter用户时间线和用户媒体时间线不再需要开发者账户
DIYgod/RSSHub pull request #7739
Opened 2021-06-20 04:10 UTC by yindaheng98

## 该 PR 相关 Issue / Involved issue

Close https://github.com/DIYgod/RSSHub/issues/4561#issuecomment-668645387
Close #7548

## 完整路由地址 / Example for the proposed route(s)

```routes
/twitter/user/DIYgod
/twitter/user/DIYgod/exclude_rts
/twitter/user/DIYgod/exclude_replies
/twitter/user/DIYgod/exclude_rts_replies
/twitter/user/DIYgod/exclude_replies_rts
/twitter/media/DIYgod
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [x] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [x] 目标是否有提供日期？ Is there a date in the source?
  - [x] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [x] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason

## 说明 / Note

  - 目前绑定过中国大陆地区手机号的Twitter账户基本已经无法申请到新的Twitter开发者账户。原有的基于API的数据获取方式在没有Twitter开发者账户的API Key和API Secret的情况下无法运行，因此添加了基于Twitter网页版API的数据获取方式

2021-06-22 06:10 UTC, NeverBehave requested changes
我看到原本的检查被关闭了，测试过不会影响原本API的功能吗？

2021-06-22 06:10 UTC, NeverBehave commented on lib/routes/twitter/media.js
> +    // // 留待申请到了Twitter Developer的好心人实现
如果功能不完善，直接在调用时报错并在文档内说明

2021-06-22 06:10 UTC, NeverBehave commented on lib/routes/twitter/twitter-api.js
> +    authorization: 'Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA',
这里硬编码的部分可以的话留一些注释文档

2021-06-22 06:10 UTC, NeverBehave commented on lib/routes/twitter/twitter-api.js
> +    // TODO: OAuth2Session
可以多解释一下todo吗？

2021-06-22 06:11 UTC, NeverBehave requested changes

2021-06-22 06:11 UTC, NeverBehave commented on docs/social-media.md
>  <Route author="DIYgod" example="/twitter/user/DIYgod" path="/twitter/user/:id/:routeParams?" :paramsDesc="['用户名', '额外参数；请参阅上面的说明和表格；特别地，当 `routeParams=exclude_replies`时去除回复，`routeParams=exclude_rts`去
如果不强制要求参数了，请更新文档

2021-06-22 06:16 UTC, SettingDust requested changes

2021-06-22 06:16 UTC, SettingDust commented on docs/en/social-media.md
> +<RouteEn author="yindaheng98" path="/twitter/media/:id/:routeParams?" example="/twitter/user/DIYgod" :paramsDesc="['user id', 'extra parameters, see the table above.']" radar="1" rssbud="1"/>
示例路由写错路径了吧？

2021-06-22 06:16 UTC, SettingDust commented on lib/routes/twitter/twitter-api.js
> +    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36 Edg/91.0.864.48',
RSSHub 本身有一个可配置的 UA，直接合并 header 不需要这个参数吧？
https://github.com/DIYgod/RSSHub/blob/master/lib/utils/got.js#L34

2021-06-22 06:16 UTC, SettingDust commented on lib/routes/twitter/twitter-api.js
> +    authorization: 'Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA',
我觉得应该可以配置，这个作为默认值

2021-06-22 06:41 UTC, yindaheng98 commented on lib/routes/twitter/media.js
> +    // // 留待申请到了Twitter Developer的好心人实现
“原本的检查”是指 user.js路由 原本的代码里 检查 是否设置了Twitter Developer API访问凭据 的那一步吗？

这个检查没有关闭，只是 没有设置Twitter Developer API访问凭据 时的动作从 直接报错 变成了 使用Twitter Web API获取数据 而已

如果设置了Twitter Developer API访问凭据，那还是会使用原来的基于Twitter Developer API的方式获取数据

2021-06-22 06:48 UTC, yindaheng98 commented on lib/routes/twitter/media.js
> +    // // 留待申请到了Twitter Developer的好心人实现
另外，media.js是新加的路由，我申请不到Twitter Developer API只能完成使用Twitter Web API获取数据的代码，对Twitter Developer API相关的功能也无法测试

这里说的“在调用时报错”是指 设置了Twitter Developer API访问凭据时 让media.js报错（没有实现基于Twitter Developer API的数据获取方式） 吗？

如果是的话，那情况就是 没设置Twitter Developer API访问凭据时user.js路由报错，设置了Twitter Developer API访问凭据时media.js路由报错，感觉不太好，所以我把media.js里的这个检查打上了注释

2021-06-22 07:03 UTC, yindaheng98 commented on lib/routes/twitter/twitter-api.js
> +    // TODO: OAuth2Session
`OAuth2Session`似乎是某种通过Cookie登录Twitter的方法，登录之后可以从Twitter Web API中获取用户关注列表和喜欢列表等更多的信息，不登录的话只能获取用户时间线和媒体时间线

相关信息参考自[mikf/gallery-dl](https://github.com/mikf/gallery-dl)，twitter-api.js代码里的twitter cookie相关的操作就是参考自此repo，`OAuth2Session`来自于这一部分：[mikf/gallery-dl/extractor/twitter.py#L599](https://github.com/mikf/gallery-dl/blob/master/gallery_dl/extractor/twitter.py#L599)

本人小白一枚，`OAuth2Session`的具体情况看了很久还是未能理解，故留下此TODO，留待大佬们有缘实现

2021-06-22 07:11 UTC, SettingDust commented on lib/routes/twitter/twitter-api.js
> +    // TODO: OAuth2Session
建议在这里引入 https://github.com/DIYgod/RSSHub/pull/7739#discussion_r655932602，以参考

2021-06-22 09:34 UTC, yindaheng98 commented on docs/social-media.md
>  <Route author="DIYgod" example="/twitter/user/DIYgod" path="/twitter/user/:id/:routeParams?" :paramsDesc="['用户名', '额外参数；请参阅上面的说明和表格；特别地，当 `routeParams=exclude_replies`时去除回复，`routeParams=exclude_rts`去
`routeParams`参数仍然需要，之前是我疏忽了，已修改

2021-06-22 09:34 UTC, yindaheng98 commented on lib/routes/twitter/twitter-api.js
> +    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36 Edg/91.0.864.48',
确实不需要，已修改

2021-06-22 09:35 UTC, yindaheng98 commented on lib/routes/twitter/twitter-api.js
> +    authorization: 'Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA',
已放入config.js并以此作为默认值

2021-06-22 09:36 UTC, yindaheng98 commented on lib/routes/twitter/twitter-api.js
> +    authorization: 'Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA',
已修改并添加注释

2021-06-22 09:42 UTC, yindaheng98 commented on docs/en/social-media.md
> +<RouteEn author="yindaheng98" path="/twitter/media/:id/:routeParams?" example="/twitter/user/DIYgod" :paramsDesc="['user id', 'extra parameters, see the table above.']" radar="1" rssbud="1"/>
已改正

2021-06-25 02:44 UTC, yindaheng98 reviewed
reviewed

2021-06-25 07:18 UTC, SettingDust commented on lib/routes/twitter/twitter-api.js
> +    const guest_token = response.data.guest_token;
为什么有的是 Snake 有的是  Camel 命名？

2021-06-25 07:19 UTC, NeverBehave requested changes

2021-06-25 07:19 UTC, NeverBehave commented on lib/routes/twitter/media.js
> +    // // 留待申请到了Twitter Developer的好心人实现
如果现在只有一种获取方式，则不要考虑API获取方式。建议做法是获取不要变更原来的API处理方式，twitter web api单独开一个文件，入口文件仅用于判断配置并调用相关操作
方便后面开发者修订

2021-06-25 15:27 UTC, yindaheng98 commented on lib/routes/twitter/twitter-api.js
> +    const guest_token = response.data.guest_token;
抱歉是我的疏忽，这是从python翻译过来的，变量名忘了统一
已修改

2021-06-25 15:29 UTC, yindaheng98 commented on lib/routes/twitter/media.js
> +    // // 留待申请到了Twitter Developer的好心人实现
That's a good idea
已将user.js路由的两种实现方式拆成两个单独文件

2021-06-26 11:27 UTC, joyous-coder commented
这个是意味着不用自己在搞twitter的token，就可以实现订阅了么？？

2021-06-26 13:46 UTC, yindaheng98 commented
> 这个是意味着不用自己在搞twitter的token，就可以实现订阅了么？？

是的。但只有用户时间线和用户媒体时间线可以获取到
其他的Twitter Web API必须要登录才能用，现在还没做

2021-06-27 09:54 UTC, joyous-coder commented
> > 这个是意味着不用自己在搞twitter的token，就可以实现订阅了么？？
> 
> 是的。但只有用户时间线和用户媒体时间线可以获取到
> 其他的Twitter Web API必须要登录才能用，现在还没做

👍 👍

2021-06-29 05:48 UTC, NeverBehave approved these changes
应该没有什么问题了，但是请等待一下合并，感谢！

2021-06-29 12:19 UTC, yindaheng98 commented
在长时间运行测试中发现csrf-token多次使用后会403 Forbidden
故增加了更新csrf-token的代码

2021-06-30 16:25 UTC, yindaheng98 reviewed
reviewed

2021-08-19 17:04 UTC, SukkaW reviewed
Why is `package-lock.json` being deleted?

2021-08-24 07:53 UTC, SettingDust reviewed
这种大量拼接输出的生成建议使用 art 引擎方便维护

2021-08-24 07:53 UTC, SettingDust commented on assets/radar-rules.js
> +                    if (params.id !== 'home' && params.id !== 'explore' && params.id !== 'notifications' && params.id !== 'messages' && params.id !== 'explore' && params.id !== 'search') {
做成数组吧？

2021-08-24 07:53 UTC, SettingDust commented on lib/routes/twitter/developer-api/search.js
> +        count: 50,
数量根据 limit 参数决定吧

2021-08-25 08:52 UTC, yindaheng98 commented on assets/radar-rules.js
> +                    if (params.id !== 'home' && params.id !== 'explore' && params.id !== 'notifications' && params.id !== 'messages' && params.id !== 'explore' && params.id !== 'search') {
已修改

2021-08-25 08:56 UTC, yindaheng98 commented on lib/routes/twitter/developer-api/search.js
> +        count: 50,
已修改

2021-08-25 13:56 UTC, yindaheng98 commented
> 这种大量拼接输出的生成建议使用 art 引擎方便维护

这个utils.js里的代码大部分来自原作者和 #6051 ，看着挺复杂的，模板化还是等大佬们来吧

2021-10-05 09:40 UTC, merged

2021-10-05 09:40 UTC, NeverBehave commented
我们已经有初步的缓存了，暂时先合并一下