fix: undefined error when no magnet & torrent
DIYgod/RSSHub pull request #7745
Opened 2021-06-21 16:04 UTC by junfengP

## 该 PR 相关 Issue / Involved issue

Close #7726 

## 完整路由地址 / Example for the proposed route(s)

```routes
/dsndsht23
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [ ] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 目标是否有提供日期？ Is there a date in the source?
  - [ ] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [ ] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-06-22 01:24 UTC, Bimyooo commented
现有版本会将 enclosure url 替换成 host。请问能否将其替换成 down.php?module=forum&attachment 的链接。

2021-06-22 06:47 UTC, SettingDust requested changes

2021-06-22 06:47 UTC, SettingDust commented on lib/routes/dsndsht23/index.js
> +            const enclosureUrl = isMag ? magnet : url.resolve(host, torrent ? torrent : "");
这里既然可能为空，就在下方检查一下，如果为空就不要添加 enclosureUrl 到 item 了

2021-06-22 14:44 UTC, junfengP commented
> 现有版本会将没有 magnet 的项目中的 enclosure url 替换成 host。请问能否将其替换成 down.php?module=forum&attachment 的链接。

用浏览器访问了一下，`down.php?module=forum&attachment`,返回404

2021-06-23 13:58 UTC, junfengP commented on lib/routes/dsndsht23/index.js
> +            const enclosureUrl = isMag ? magnet : url.resolve(host, torrent ? torrent : "");
done

2021-07-20 09:05 UTC, SettingDust approved these changes

2021-08-09 05:10 UTC, ly012 commented
还是有些问题，这种有2个磁力的帖子。rss直接把2个磁力合并到一起了。
https://sehuatang.net/forum.php?mod=viewthread&tid=574614
`<enclosure url="magnet:?xt=urn:btih:IKINKAPVAHOJ2SDYMAG5LZ7HOO6HLTTVmagnet:?xt=urn:btih:UYFQ4M2DSJ3YSMSEYL4B325LLPVKEGKC" type="application/x-bittorrent"/>`

2021-08-12 07:30 UTC, NeverBehave commented
这个可以合并了吗？

2021-08-15 07:42 UTC, junfengP commented
@NeverBehave 先合了吧

@ly012 最近没有时间修，先搁置着

2021-11-27 07:28 UTC, merged