add route dut/teach
DIYgod/RSSHub pull request #7765
Opened 2021-06-24 08:24 UTC by BeautyYuYanli

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/dut/teach/zytg
/dut/teach/jiaoxuewenjian
/dut/teach/qitawenjian
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 目标是否有提供日期？ Is there a date in the source?
  - [ ] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [ ] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-06-25 01:55 UTC, SettingDust reviewed
自动部署 `dut/teach/jiaoxuewenjian` 是空的？

2021-06-25 01:55 UTC, SettingDust commented on lib/routes/universities/dut/dutdice/index.js
> +            const cache = await ctx.cache.get(entryUrl);
用 `ctx.cache.tryGet` 方便些 :D

2021-06-25 01:55 UTC, SettingDust commented on lib/routes/universities/dut/tycgzx/index.js
> +            const cache = await ctx.cache.get(entryUrl);
同

2021-06-25 01:55 UTC, SettingDust commented on lib/routes/universities/dut/teach/index.js
> +            const cache = await ctx.cache.get(entryUrl);
同

2021-06-25 02:41 UTC, BeautyYuYanli commented
> 自动部署 `dut/teach/jiaoxuewenjian` 是空的？

可能 bot 测试时 vercel 还没完全部署好？那个链接点进去没问题 本地调试也没问题

2021-06-25 03:06 UTC, SettingDust commented on lib/routes/universities/dut/teach/index.js
> +            const description = $('form[name="_newscontent_fromname"]').html();
![image](https://user-images.githubusercontent.com/19922286/123363494-3fb3cc00-d5a5-11eb-829f-66ec18eccba0.png)
建议处理一下，以及附件似乎没有正确附带链接

2021-06-25 06:17 UTC, BeautyYuYanli commented on lib/routes/universities/dut/teach/index.js
> +            const description = $('form[name="_newscontent_fromname"]').html();
关于附件链接: 这似乎取决于 rss 阅读器? 我使用 Inoreader 和 Newsboat 都能正确处理链接. 我不确定应该怎样修改使其更普适

2021-06-25 06:46 UTC, SettingDust commented on lib/routes/universities/dut/teach/index.js
> +            const description = $('form[name="_newscontent_fromname"]').html();
可能是 bug，确实有 a href

2021-06-25 06:46 UTC, SettingDust approved these changes

2021-06-25 07:05 UTC, NeverBehave requested changes

2021-06-25 07:05 UTC, NeverBehave commented on lib/routes/universities/dut/tycgzx/index.js
> +                pubDate: timezone(parseDate(item.find('span').text(), 'YYYY/MM/DD'), +8),
处理的流程看起来都是一样的？如果可以的话稍微合并一下路由？

2021-06-25 10:39 UTC, BeautyYuYanli commented on lib/routes/universities/dut/tycgzx/index.js
> +                pubDate: timezone(parseDate(item.find('span').text(), 'YYYY/MM/DD'), +8),
已合并

2021-06-26 04:19 UTC, SettingDust requested changes

2021-06-26 04:19 UTC, SettingDust commented on lib/routes/universities/dut/subsite.js
> +    attachment = (attachment ? attachment : '').replaceAll('<li>', '<li><p>').replaceAll('</li>', '</p></li>');
replaceAll => replace

2021-06-27 00:10 UTC, NeverBehave approved these changes

2021-06-27 00:10 UTC, merged

2021-06-27 00:11 UTC, NeverBehave commented
You made it! Thanks for your contribution :P