add route&docs  全民K歌
DIYgod/RSSHub pull request #7768
Opened 2021-06-25 04:03 UTC by zhangxiang012

## 该 PR 相关 Issue / Involved issue

Close #3971

## 完整路由地址 / Example for the proposed route(s)

```routes
/kge/639a9a86272c308e33 
/kge/reply/OhXHMdO1VxLWQOOm
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [x] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [x] 目标是否有提供日期？ Is there a date in the source?
  - [x] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [x] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-06-25 07:41 UTC, SettingDust requested changes

2021-06-25 07:41 UTC, SettingDust commented on docs/social-media.md
> +<Route author="zhangxiang012" example="/kge/reply/OhXHMdO1VxLWQOOm" path="/kge/reply/:playId" :paramsDesc="['playId即音频页id, 可在对应页面的 URL 中找到']" />
英文和中文怎么一会儿空格一会儿不空……，都空着吧

2021-06-25 07:41 UTC, SettingDust commented on lib/routes/kge/cache.js
> +                    'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1',
使用内置 UA 无法访问？

2021-06-25 07:41 UTC, SettingDust commented on lib/routes/kge/user.js
> +                pubDate: new Date(item.ctime * 1000).toUTCString(),
建议使用 parseDate，而且测试实例中日期是无效的

2021-06-25 07:41 UTC, SettingDust commented on lib/routes/kge/user.js
> +                title: $('a .mod_playlist__work').text(),
实例中标题为空？

2021-06-25 07:41 UTC, SettingDust commented on docs/social-media.md
> +### 评论动态
什么的评论动态，描述一下

2021-06-25 07:41 UTC, SettingDust commented on docs/social-media.md
> +### 用户
用户的什么，描述一下

2021-06-25 07:41 UTC, SettingDust commented on lib/routes/kge/reply.js
> +    const url = `https://node.kg.qq.com/play?s=${playid}&g_f=personal&appsource=`;
后面没必要的 query 参数是？

2021-06-25 10:10 UTC, SettingDust requested changes

2021-06-25 10:10 UTC, SettingDust commented on lib/routes/kge/reply.js
> +            link: url,
link 都一样会导致 guid 都一致，guid 必须不一致

2021-06-25 10:10 UTC, SettingDust commented on lib/routes/kge/reply.js
> +            description: `${item.nick} : ${item.content}`,
没有 description 可以不写，保留 title 就可以

2021-06-25 10:13 UTC, SettingDust commented
改好的自己标一下 reslove :)

2021-06-25 10:35 UTC, SettingDust commented
没改的就不要标= =

2021-06-25 11:48 UTC, SettingDust commented
https://github.com/DIYgod/RSSHub/pull/7768#discussion_r658653016

2021-06-28 03:32 UTC, zhangxiang012 commented
由于重复请求页面时分享链接会发生变化，所以原有逻辑里同一作品的 guid 和缓存 key 会重复生成。[
f89a1be](https://github.com/DIYgod/RSSHub/pull/7768/commits/f89a1beae606c83263fb865c8eee953eed2219a5) 进行了修复

2022-07-01 15:10 UTC, merged