fix: 二柄APP
DIYgod/RSSHub pull request #7799
Opened 2021-07-01 13:06 UTC by wushijishan

## 该 PR 相关 Issue / Involved issue
修复二柄APP路由错误
Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/erbingapp/news
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [ ] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 目标是否有提供日期？ Is there a date in the source?
  - [ ] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [ ] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-07-01 13:16 UTC, SettingDust requested changes

2021-07-01 13:16 UTC, SettingDust commented on lib/routes/erbingapp/news.js
> +            } else if (item.acontent.toString().indexOf('104129') !== -1) {
根据 api 的这个返回值，建议 JSON.parse 解析为对象操作，而不是正则，这地方正则明显没有处理好，原来的正则并不适用
```
"acontent": "{\"imgs\": \"https://erbingeditor.diershoubing.com/VlqH8yfL4hqOuxJiy9SWGHOo/2021/07/01/1827140428.PNG,https://erbingeditor.diershoubing.com/VlqH8yfL4hqOuxJiy9SWGHOo/2021/07/01/1827345068.jpg,https://erbingeditor.diershoubing.com/VlqH8yfL4hqOuxJiy9SWGHOo/2021/07/01/1828332883.jpg,https://erbingeditor.diershoubing.com/VlqH8yfL4hqOuxJiy9SWGHOo/2021/07/01/1829325572.jpg,https://erbingeditor.diershoubing.com/VlqH8yfL4hqOuxJiy9SWGHOo/2021/07/01/1830149169.jpg,https://erbingeditor.diershoubing.com/VlqH8yfL4hqOuxJiy9SWGHOo/2021/07/01/1830465462.jpg,https://erbingeditor.diershoubing.com/VlqH8yfL4hqOuxJiy9SWGHOo/2021/07/01/1831226440.jpg,https://erbingeditor.diershoubing.com/VlqH8yfL4hqOuxJiy9SWGHOo/2021/07/01/1831579841.jpg\", \"article_id\": 39764}",
```

2021-07-01 14:12 UTC, wushijishan commented on lib/routes/erbingapp/news.js
> +            } else if (item.acontent.toString().indexOf('104129') !== -1) {
谢谢指正，水平很业余，主要目的是写一个凑合着自己用，以后再研究研究，或者由其他爱好者来完善

2021-07-13 12:23 UTC, SettingDust commented
预览无法访问

2021-07-13 12:41 UTC, wushijishan commented
之前我自己的修改自己测试过，这位仁兄的修改我确认了@auto-bot-ty，可能具体得问他了，我水平很有限@SettingDust

2021-07-13 15:19 UTC, SettingDust approved these changes

2021-07-17 09:10 UTC, NeverBehave approved these changes

2021-07-17 09:11 UTC, merged