fead: add 雪球股票评论
DIYgod/RSSHub pull request #7822
Opened 2021-07-05 14:57 UTC by zytomorrow

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/xueqiu/stock_comments/SZ002626
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [x] 目标是否有提供日期？ Is there a date in the source?
  - [x] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [x] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

demo如下，实时获取最新的20条评论

![image](https://user-images.githubusercontent.com/16175551/119611413-3eb83f00-be2d-11eb-9b01-41d772ad5cbb.png)
![image](https://user-images.githubusercontent.com/16175551/119611488-54c5ff80-be2d-11eb-8c48-8fc909fe6885.png)

2021-07-16 01:05 UTC, SettingDust approved these changes

2021-07-16 01:05 UTC, SettingDust commented on lib/routes/xueqiu/stock_comments.js
> +            let description = '';
这种建议 art 模板，建议

2021-07-17 09:18 UTC, NeverBehave requested changes

2021-07-17 09:18 UTC, NeverBehave commented on lib/routes/xueqiu/stock_comments.js
> +            let description = '';
有路由例子吗？开个教程写一下把，这个问题也很大……

2021-07-17 09:18 UTC, NeverBehave commented on lib/routes/xueqiu/stock_comments.js
> +                pubDate: new Date(item.created_at).toUTCString(),
https://docs.rsshub.app/joinus/pub-date.html

2021-07-19 04:03 UTC, zytomorrow commented on lib/routes/xueqiu/stock_comments.js
> +                pubDate: new Date(item.created_at).toUTCString(),
已调整。

2021-07-19 04:03 UTC, zytomorrow commented on lib/routes/xueqiu/stock_comments.js
> +            let description = '';
已使用art模板调整description

2021-07-20 01:33 UTC, SettingDust approved these changes

2021-07-20 01:33 UTC, SettingDust commented on lib/routes/xueqiu/stock_comments.js
> +const description_template = `
棒棒，虽然我想说的是独立一个 art 文件，不过棒棒

2021-07-20 02:24 UTC, zytomorrow commented on lib/routes/xueqiu/stock_comments.js
> +const description_template = `
😂内容有点少,就索性放一个文件 了

2021-08-12 05:59 UTC, merged