fix: 风之动漫域名更换
DIYgod/RSSHub pull request #7828
Opened 2021-07-05 15:48 UTC by zytomorrow

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/fzdm/manhua/2
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [x] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 目标是否有提供日期？ Is there a date in the source?
  - [ ] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [ ] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

风之动漫官网域名更新，进行适配

2021-07-16 00:32 UTC, SettingDust requested changes
只抓取第一个项目，项目没有 link
路由质量有些差了，增加一下

2021-07-16 00:32 UTC, SettingDust commented on lib/routes/fzdm/manhua.js
>                      'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36',
配置里的ua不可用？

2021-07-18 16:13 UTC, zytomorrow commented on lib/routes/fzdm/manhua.js
>                      'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36',
已测试，删除此处的ua配置

2021-07-18 16:15 UTC, zytomorrow commented
> 只抓取第一个项目，项目没有 link
> 路由质量有些差了，增加一下

1. 项目抓取数量由最后一个可选参数确定，默认为1。原路由有文档说明了该使用方式，兼容之前的订阅不修改该方式。
2. link由于抓取页面结构变化，适配遗漏了。现已补齐

2021-07-20 01:49 UTC, SettingDust commented
> > 只抓取第一个项目，项目没有 link
> > 路由质量有些差了，增加一下
> 
> 1. 项目抓取数量由最后一个可选参数确定，默认为1。原路由有文档说明了该使用方式，兼容之前的订阅不修改该方式。
> 2. link由于抓取页面结构变化，适配遗漏了。现已补齐

我觉得不合理，其实抓取 20 个也一样不会影响原来的路由，只要 guid 不变，反而限制数量会丢项目

2021-07-20 02:37 UTC, zytomorrow commented
> > > 只抓取第一个项目，项目没有 link
> > > 路由质量有些差了，增加一下
> > 
> > 
> > 
> > 1. 项目抓取数量由最后一个可选参数确定，默认为1。原路由有文档说明了该使用方式，兼容之前的订阅不修改该方式。
> > 2. link由于抓取页面结构变化，适配遗漏了。现已补齐
> 
> 我觉得不合理，其实抓取 20 个也一样不会影响原来的路由，只要 guid 不变，反而限制数量会丢项目

漫画话数是在一个页面上,不限制数量的话首次抓取某个漫画会抓取所有内容,后续还得一页一页的抓取漫画内容,对rsshub服务器和漫画服务器压力都有点大.数量还是得限制一下,只是限制多少这是个问题🤣🤣🤣.之前不抓取漫画内容的是不限制数量的,后面考虑到抓取漫画实际内容的方式有点消耗资源,就加了限制.内容一般是周更或者月更,丢内容的情况很难出现
![image](https://user-images.githubusercontent.com/16175551/126253051-2b5238d7-f2b6-4781-b0e4-d9ee37578015.png)

2021-07-20 02:45 UTC, SettingDust commented
实际上全文都是一页一页抓的 做好缓存就可以了

2021-07-20 05:50 UTC, zytomorrow commented
ok. 去掉了限制,没有缓存的话,首次部署项目,访问路由实在有些费时间.🤣以海贼王为例,首次访问耗时6分钟+
![image](https://user-images.githubusercontent.com/16175551/126267813-6d56d993-d73b-4128-bbf0-b85e6bf2d95e.png)

2021-07-20 06:01 UTC, zytomorrow commented
Vercel 有10s超时限制,router test检测无法通过

2021-07-20 06:54 UTC, SettingDust commented
> Vercel 有10s超时限制,router test检测无法通过

限制数量是有中间件的，你可以读取 query 参数来判断，没必要单独的 path param

2021-07-20 07:25 UTC, zytomorrow commented
> > Vercel 有10s超时限制,router test检测无法通过
> 
> 限制数量是有中间件的，你可以读取 query 参数来判断，没必要单独的 path param

抱歉,没注意到还有通用参数😂.已使用通用参数控制数量

2021-07-20 08:31 UTC, SettingDust commented
> > > Vercel 有10s超时限制,router test检测无法通过
> > 
> > 限制数量是有中间件的，你可以读取 query 参数来判断，没必要单独的 path param
> 
> 抱歉,没注意到还有通用参数😂.已使用通用参数控制数量

我指的是你可以通过 limit 只抓取前几个，因为 limit 的行为是结果里截取的，会有无效缓存

2021-07-20 08:57 UTC, zytomorrow commented
如果只对最后的结果用limit控制,那压力还是大,首次访问的路由耗时太长了.
以海贼王那一页为例,不在获取详细内容时控制数量,首次访问该路由会请求1000多话的所有漫画页,漫画图片页是依次获取的,瞬时压力太大了,很容易触发反爬.

你说的是不控制爬取数量,只在最后结果使用limit控制?我理解的是这种还是会有上述的高压力出现,获取了所有内容,只是只展示了需要的数量.不知道我理解是否正确,有错误请指正.
![image](https://user-images.githubusercontent.com/16175551/126292583-6485150c-7f9b-44d9-b7cc-047dbdfdd308.png)

2021-07-20 09:13 UTC, SettingDust commented
没事，我看错代码了

2021-07-20 09:14 UTC, SettingDust approved these changes

2021-08-12 07:29 UTC, merged