feat(route): add MacWk
DIYgod/RSSHub pull request #7833
Opened 2021-07-06 22:13 UTC by f48vj

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/macwk/soft/sublime-text
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [x] 目标是否有提供日期？ Is there a date in the source?
  - [x] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [x] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-07-11 00:07 UTC, SettingDust requested changes

2021-07-11 00:07 UTC, SettingDust commented on lib/routes/macwk/soft.js
> +        link: `https://macwk.com/soft/${name}`,
link 一致就需要指定 guid 否则阅读器无法识别

2021-07-13 06:02 UTC, f48vj commented on lib/routes/macwk/soft.js
> +        link: `https://macwk.com/soft/${name}`,
搞定

2021-07-13 07:36 UTC, SettingDust approved these changes

2021-07-13 07:39 UTC, SettingDust approved these changes

2021-07-17 08:57 UTC, NeverBehave requested changes

2021-07-17 08:57 UTC, NeverBehave commented on lib/routes/macwk/soft.js
> +        pubDate: item.created_on,
https://docs.rsshub.app/joinus/pub-date.html
请按照日期处理规范实现

2021-07-17 09:52 UTC, f48vj commented on lib/routes/macwk/soft.js
> +        pubDate: item.created_on,
修改了 但是实测没有差别 @NeverBehave

2021-07-23 05:06 UTC, f48vj commented
@NeverBehave  啥时候才能 merge 呀 这么多天了

2021-07-23 05:52 UTC, SettingDust commented on lib/routes/macwk/soft.js
> +        pubDate: item.created_on,
> 修改了 但是实测没有差别 @NeverBehave 

是规范，而不是“有差别”

2021-07-23 05:53 UTC, SettingDust commented
> @NeverBehave  啥时候才能 merge 呀 这么多天了

等，这不是职业，你可以帮助审查其他 pr 的问题

2021-07-31 22:13 UTC, f48vj commented
@NeverBehave can you review this PR

2021-07-31 22:20 UTC, f48vj commented
@NeverBehave  I know this is not your job, but you still block the process

2021-08-01 00:22 UTC, SettingDust commented
> @NeverBehave  I know this is not your job, but you still block the process

所谓的 block 的是你的 process，他有他的事，你觉得他不行可以去找 DIY 申请审核权限，找他没用，又不是说有事是逗你玩的

2021-08-01 04:35 UTC, f48vj commented
@SettingDust 你在这搞什么事情？对，他忙，但我看你闲的很呀

2021-08-01 04:37 UTC, SettingDust commented
所以呢

2021-08-01 04:44 UTC, f48vj commented
所以这个PR 有什么问题吗？如果没有要修改的可以Merge了吗

2021-08-01 04:45 UTC, SettingDust commented
> 所以这个PR 有什么问题吗？如果没有要修改的可以Merge了吗

可以了

2021-08-01 04:51 UTC, SettingDust requested changes

2021-08-01 04:51 UTC, SettingDust commented on lib/routes/macwk/soft.js
> +        pubDate: parseDate(item.created_on, 'YYYY/MM/DD HH:mm:ss'),
时区是怎么验证的

2021-08-12 06:03 UTC, NeverBehave approved these changes

2021-08-12 06:03 UTC, merged

2021-08-12 06:04 UTC, NeverBehave commented
Sorry for the delay and thanks for your contribution