fix(route): 纽约时报 - 新闻简报   图片缺失
DIYgod/RSSHub pull request #7841
Opened 2021-07-07 18:50 UTC by auto-bot-ty

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/nytimes/daily_briefing_chinese
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [ ] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 目标是否有提供日期？ Is there a date in the source?
  - [ ] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [ ] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-07-11 00:00 UTC, SettingDust requested changes

2021-07-11 00:00 UTC, SettingDust commented on lib/routes/nytimes/daily_briefing_chinese.js
>                      item.pubDate = parseDate(date);
日期好像不太对 
https://www.nytimes.com/zh-hans/2021/06/29/world/asia/china-hong-kong-security-law-anniversary.html

2021-07-13 01:02 UTC, SettingDust approved these changes
```
<span aria-hidden="true" class="css-16f3y1r e13ogyst0">Didi started trading last week on the New York Stock Exchange.</span><span class="css-cnj6d5 e1z0qqy90"><span class="css-1ly73wi e1tej78p0">Credit...</span><span>Brendan Mcdermid/Reuters</span>
```
@![Screenshot_2021_0713_090102.jpg](https://user-images.githubusercontent.com/19922286/125374193-18d50280-e3b9-11eb-9cae-a080646423c2.jpg)


图片题注可以改成center small 之类的，只是建议，已经可以合并了

2021-07-13 07:40 UTC, SettingDust commented
嗯，不然题注和正文分辨不便

2021-07-17 08:55 UTC, NeverBehave approved these changes

2021-07-17 08:56 UTC, merged