fix(route): 修复语雀源无效的问题
DIYgod/RSSHub pull request #7851
Opened 2021-07-10 06:02 UTC by ltaoo

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/yuque/ruanyf/weekly
/yuque/ruanyf/weekly?content=1
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [x] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [x] 目标是否有提供日期？ Is there a date in the source?
  - [x] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [ ] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

发现 `yuque` 现在的配置方式无法抓取页面了，即使提供了 `TOKEN` 仍提示 `401`，猜测之前语雀是客户端渲染所以暴露了接口，现在是将页面数据渲染到 `window.appData` 上，之前的接口都不再对外使用。

所以改为了获取页面内的 `window.appData` 的方式。

在文档中没看到怎么对之前的路由做废弃标志的方式，直接删除还是保留不变，还是做已废弃说明，引导使用新的配置方式？
这里的做法是引导使用新的配置方式了。

2021-07-10 23:15 UTC, SettingDust requested changes

2021-07-10 23:15 UTC, SettingDust commented on lib/routes/yuque/name/book.js
> +                    pubDate: doc.published_at,
传入 date 对象，参阅文档日期处理

2021-07-10 23:15 UTC, SettingDust commented on lib/routes/yuque/name/book.js
> +                    return Promise.resolve(item);
这里似乎直接 return 就可以

2021-07-10 23:15 UTC, SettingDust commented on lib/routes/yuque/name/book.js
> +                item.cover = partialDoc.doc.cover || partialDoc.doc.custom_cover;
cover 这个属性不在 rss 规范中

2021-07-10 23:15 UTC, SettingDust commented on lib/routes/yuque/name/book.js
> +                    ctx.cache.set(key, item.description);
既然上面也设置缓存了，那把这句和上面的都拿到return前即可

2021-07-10 23:15 UTC, SettingDust commented on lib/routes/yuque/name/book.js
> +                    ctx.cache.set(key, item.description);
既然上面也设置缓存了，那把这句和上面的都拿到return前即可，也就是合并成一句

2021-07-10 23:15 UTC, SettingDust commented on lib/routes/yuque/name/book.js
> +                    ctx.cache.set(key, item.description);
既然上面也设置缓存了，那把这句和上面的都拿到return前即可，也就是合并成一句

2021-07-10 23:15 UTC, SettingDust commented on lib/routes/yuque/name/book.js
> +        result.description = 'Parse global data failed.';
请直接抛出报错信息

2021-07-11 05:38 UTC, SettingDust approved these changes

2021-07-11 05:38 UTC, SettingDust commented on lib/routes/yuque/name/book.js
> +        throw err;
最好有相应消息解释一下

2021-07-11 05:40 UTC, ltaoo commented on lib/routes/yuque/name/book.js
> +        throw err;
错误处理有例子可以参考下吗

2021-07-11 05:41 UTC, SettingDust requested changes

2021-07-11 05:41 UTC, SettingDust commented on lib/routes/yuque/name/book.js
> +                const { data: { data: docDetail } } = await fetchData(articleUrl(doc.slug, id));
全文似乎没有正确抓取？在示例中还是无全文，似乎是缓存的原因，没有分开缓存，手机不太确定

2021-07-11 05:46 UTC, ltaoo commented on lib/routes/yuque/name/book.js
> +                const { data: { data: docDetail } } = await fetchData(articleUrl(doc.slug, id));
https://rsshub-do-not-use-14ygbl3ve-diy.vercel.app/yuque/u7327/issues?content=1   这个示例数据量比较少，我看了是有的。

如果不加 content=1 参数访问过，缓存了，在加 content 参数肯定是没有的对吧，因为命中缓存了。

2021-07-16 01:25 UTC, SettingDust commented on lib/routes/yuque/name/book.js
> +                const { data: { data: docDetail } } = await fetchData(articleUrl(doc.slug, id));
加了 content 应该单独缓存

2021-07-17 12:45 UTC, ltaoo commented on lib/routes/yuque/name/book.js
> +                const { data: { data: docDetail } } = await fetchData(articleUrl(doc.slug, id));
发现分开缓存没用，在 `cache` 中间件这里是根据 `path` 做了缓存，所以我的 `yuque/:name/:book` 是视为了一个缓存，导致 `?content=1` 有没有缓存结果是一样的，最终实现是直接取全文。

2021-07-17 13:01 UTC, SettingDust commented on lib/routes/yuque/name/book.js
> +                const { data: { data: docDetail } } = await fetchData(articleUrl(doc.slug, id));
= =，非全文不要你缓存

2021-09-14 11:05 UTC, closed without merging