[Feat] Add gitlab releases and allow different gitlab instances
DIYgod/RSSHub pull request #7873
Opened 2021-07-14 10:52 UTC by zoenglinghou

## 该 PR 相关 Issue / Involved issue

N/A

## 完整路由地址 / Example for the proposed route(s)

```routes
/gitlab/explore/all/gitlab.com
/gitlab/release/pleroma/pleroma/git.pleroma.social
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [x] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [x] 目标是否有提供日期？ Is there a date in the source?
  - [x] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [x] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

- 增加了订阅 Gitlab release 的特性
- 为现有的 Gitlab 路由加入使用不同 Gitlab 服务器的选择

2021-07-14 14:42 UTC, SettingDust requested changes
https://gitlab.com/rluna-open-source/file-management/owncloud/android

不能抓取这种仓库的 release？

2021-07-14 14:42 UTC, SettingDust commented on docs/programming.md
> +<Route author="imlonghao" example="/gitlab/explore/trending" path="/gitlab/explore/:type/:host?" :paramsDesc="['分类', '服务器地址，缺省为 gitlab.com']">
作者可以多个 空格分割

2021-07-14 14:42 UTC, SettingDust commented on lib/routes/gitlab/release.js
> +            pubDate: new Date(item.released_at),
时区好像不一定对，示例里的 release 时间不对劲

2021-07-14 15:01 UTC, zoenglinghou commented on lib/routes/gitlab/release.js
> +            pubDate: new Date(item.released_at),
好吧，时区的话我看 Gitlab 似乎返回的是 ISO 8601 时间 🤔 似乎默认是 UTC？我看置顶的 Issue 还是跟服务器时区有关？我搞不太懂

2021-07-14 15:04 UTC, zoenglinghou commented on docs/programming.md
> +<Route author="imlonghao" example="/gitlab/explore/trending" path="/gitlab/explore/:type/:host?" :paramsDesc="['分类', '服务器地址，缺省为 gitlab.com']">
:ok_hand:

2021-07-14 15:08 UTC, zoenglinghou commented
@SettingDust 你列的这个仓库只有 tag，没有 release 唉...看起来需要一个新的路由...

https://docs.gitlab.com/ee/api/tags.html

2021-07-14 16:05 UTC, zoenglinghou commented on lib/routes/gitlab/release.js
> +            pubDate: new Date(item.released_at),
我现在用了新的 `parseDate` 应该是对的
UTC 时间错不了吧...?

2021-07-14 23:50 UTC, SettingDust commented
这个多层嵌套的报错 wrong path。

时间问题
![Screenshot_2021_0715_074652.jpg](https://user-images.githubusercontent.com/19922286/125706721-2639ed7e-4986-4071-9f95-43874eaa03b1.jpg)
![Screenshot_2021_0715_074636.jpg](https://user-images.githubusercontent.com/19922286/125706733-bd748ceb-d2b8-4a1a-877f-c873367b978b.jpg)

如上图，页面显示的是+0800的时间，而rss的时间对不上号

2021-07-15 10:15 UTC, zoenglinghou commented
多层嵌套这个我没发现有问题耶？可以详细说一下你遇到的错误吗？

2021-07-15 12:19 UTC, SettingDust commented
> 多层嵌套这个我没发现有问题耶？可以详细说一下你遇到的错误吗？

示例

2021-07-16 07:58 UTC, zoenglinghou commented
你说示例中 owncloud 这个链接吗？我看 vercel 的这个链接也没问题啊

2021-07-16 08:34 UTC, SettingDust commented
> 你说示例中 owncloud 这个链接吗？我看 vercel 的这个链接也没问题啊

没问题，Github 手机客户端把 %2f 解码了，网页ok

2021-07-16 08:35 UTC, SettingDust approved these changes
![Screenshot_20210716_163424](https://user-images.githubusercontent.com/19922286/125918381-e0c306fb-6559-4d74-ad72-78bd7f4d10e9.jpg)
现在都打不开这个 pr 了xd

2021-07-16 08:48 UTC, zoenglinghou commented
😂
ok 谢谢你的 Review！

2021-07-17 09:24 UTC, NeverBehave approved these changes

2021-07-17 09:25 UTC, merged

2021-07-29 23:38 UTC, SettingDust commented
> 😂
> ok 谢谢你的 Review！

看一下 #7796

2021-07-30 06:51 UTC, zoenglinghou commented
ok我关注一下进展🤔 希望不会破坏现有的路径

2021-07-30 07:11 UTC, SettingDust commented
> ok我关注一下进展🤔 希望不会破坏现有的路径

这是一直有的特性，而不是新的，这两个只是用做参考，可以不需要 url 解码 `/`