fix/thu-career
DIYgod/RSSHub pull request #7894
Opened 2021-07-18 05:12 UTC by DylanXie123

## 该 PR 相关 Issue / Involved issue

Close #7767

## 完整路由地址 / Example for the proposed route(s)

```routes
/thu/career
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [x] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [x] 目标是否有提供日期？ Is there a date in the source?
  - [x] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [x] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-07-18 23:09 UTC, nczitzk approved these changes

2021-07-20 01:45 UTC, SettingDust requested changes

2021-07-20 01:45 UTC, SettingDust commented on lib/routes/universities/thu/career.js
> +        .slice(0, 10)
截断的原因？

2021-07-20 01:45 UTC, SettingDust commented on lib/routes/universities/thu/career.js
> +                pubDate: timezone(date, +8),
这种没时间的没必要加时区，只会更不准确

2021-07-20 07:54 UTC, DylanXie123 commented on lib/routes/universities/thu/career.js
> +        .slice(0, 10)
看到之前的路由会进行截断，以为是出于性能的考虑，就照着弄了。这里一次会拿到20条，不截断应该也行

2021-07-20 07:54 UTC, DylanXie123 commented on lib/routes/universities/thu/career.js
> +                pubDate: timezone(date, +8),
👌

2021-07-20 09:12 UTC, SettingDust requested changes

2021-07-20 09:12 UTC, SettingDust commented on lib/routes/universities/thu/career.js
> +                        item.description = content("div[class='sideleft left'], div[class='content teacher']").html();
少用 attr 选择器，这地方如果两个同时存在那 html 只能拿到第一个，如果确认两个不会同时存在就没问题

```suggestion
                        item.description = content("div.sideleft.left, div.content.teacher").html();
```

2021-07-20 10:04 UTC, DylanXie123 commented on lib/routes/universities/thu/career.js
> +                        item.description = content("div[class='sideleft left'], div[class='content teacher']").html();
感谢你的建议😁

2021-07-20 11:08 UTC, SettingDust approved these changes

2021-08-12 06:21 UTC, NeverBehave approved these changes

2021-08-12 06:34 UTC, merged