feat(route): add 拷贝漫画
DIYgod/RSSHub pull request #7896
Opened 2021-07-18 12:20 UTC by btdwv

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/copymanga/comic/zhandoupohuaixueyuandangerous
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 目标是否有提供日期？ Is there a date in the source?
  - [ ] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [ ] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [x] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

拷贝漫画加密了列表，不使用Puppeteer得不到解密后的数据

2021-07-18 23:25 UTC, nczitzk approved these changes

2021-07-18 23:28 UTC, nczitzk commented
生成测试路由失败，故附上本地测试路由结果：

![image](https://user-images.githubusercontent.com/42264778/126085282-2e77bd16-b350-4930-bec5-dd881d1c8504.png)

2021-07-20 01:40 UTC, SettingDust requested changes

2021-07-20 01:40 UTC, SettingDust commented on lib/routes/copymanga/comic.js
> +    const browser = await require('@/utils/puppeteer')();
什么加密？
https://api.copymanga.com/api/v3/comic/zhandoupohuaixueyuandangerous/group/default/chapters?limit=100&offset=0

2021-07-24 06:07 UTC, btdwv commented on lib/routes/copymanga/comic.js
> +    const browser = await require('@/utils/puppeteer')();
直接使用got获取前端页面，返回的是aes加密后的漫画列表。

感谢你提供的接口。

2021-07-24 07:14 UTC, SettingDust requested changes

2021-07-24 07:14 UTC, SettingDust commented on lib/routes/copymanga/comic.js
> +            <h1>${chapter.num}p</h1>
没内容感觉可以把这两个放到标题，不要描述

2021-08-01 06:05 UTC, btdwv commented on lib/routes/copymanga/comic.js
> +            <h1>${chapter.num}p</h1>
不太想这么改
不想在标题的字段里放其他的信息

2021-08-01 07:19 UTC, SettingDust approved these changes

2021-08-12 08:57 UTC, NeverBehave requested changes
清理一下注释，不使用的代码不用保留

2021-08-21 02:02 UTC, btdwv commented
> 清理一下注释，不使用的代码不用保留

删掉了

2021-08-23 06:40 UTC, SettingDust requested changes

2021-08-23 06:40 UTC, SettingDust commented on lib/routes/copymanga/comic.js
> +    } while (bHasNextPage === true);
```suggestion
    } while (bHasNextPage);
```

2021-08-23 06:40 UTC, SettingDust commented on lib/routes/copymanga/comic.js
> +    chapterArray.reverse();
```suggestion
    chapterArray = chapterArray.map(({ comic_path_word, uuid, name, size, datetime_created, index }) => ({
        link: 'https://copymanga.com/comic/' + comic_path_word + '/chapter/' + uuid,
        title: name,
        num: size,
        updateTime: datetime_created,
        index,
    })).reverse();
```

2021-08-23 06:40 UTC, SettingDust commented on lib/routes/copymanga/comic.js
> +    const iReqLimit = 100;
```suggestion
    const iReqLimit = ctx.queries && ctx.queries.limit || 100;    const iReqLimit = ctx.queries && ctx.queries.limit || 100;
```

2021-08-23 06:40 UTC, SettingDust commented on lib/routes/copymanga/comic.js
> +    const bookIntro = $('.intro').text();
```suggestion
    const { bookTitle, bookIntro } = ctx.cache.tryGet(`https://copymanga.com/comic/${id}`, async () => {
        const { data } = await got.get(`https://copymanga.com/comic/${id}`);
        const $ = cheerio.load(data);
        return {
            bookTitle: $('.comicParticulars-title-right > ul > li > h6').text(),
            bookIntro: $('.intro').text(),
        };
    });
```

2021-08-23 06:40 UTC, SettingDust commented on lib/routes/copymanga/comic.js
> +};
```suggestion
```

2021-08-23 06:40 UTC, SettingDust commented on lib/routes/copymanga/comic.js
> +        const chaptersObj = JSON.parse(data.body);
```suggestion
        const { data } = await got.get(strBaseUrl + 'limit=' + iReqLimit + '&offset=' + iReqOffSet);
        const { code, results } = data;
```

2021-08-23 06:40 UTC, SettingDust commented on lib/routes/copymanga/comic.js
> +        chapterArray = chapterArray.concat(chaptersObj.results.list);
```suggestion
        if (code !== 200) {
            break;
        }

        if (results.limit + results.offset < results.total) {
            bHasNextPage = true;
        }
        iReqOffSet += iReqLimit;

        chapterArray = chapterArray.concat(results.list);
```

2021-08-23 16:15 UTC, btdwv commented
PR route test / testRoute失败了，提示
Error: API rate limit exceeded for installation ID 5316000.

2021-09-09 08:33 UTC, NeverBehave approved these changes

2021-11-27 07:49 UTC, merged