feat(route): add 生物探索
DIYgod/RSSHub pull request #7897
Opened 2021-07-18 17:26 UTC by aidistan

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/biodiscover
/biodiscover/research
/biodiscover/industry
/biodiscover/financing
/biodiscover/politics
/biodiscover/celebrity
/biodiscover/company
/biodiscover/product
/biodiscover/activity
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [x] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [x] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [x] 目标是否有提供日期？ Is there a date in the source?
  - [x] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [x] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-07-18 23:31 UTC, nczitzk commented on lib/routes/biodiscover/index.js
> +                        const re = /(\d+)天前/.exec(date);
可以使用文档中 [日期处理](https://docs.rsshub.app/joinus/pub-date.html) 中提到的 `parseRelativeDate` 解析相对日期 😃

2021-07-19 01:59 UTC, aidistan commented on lib/routes/biodiscover/index.js
> +                        const re = /(\d+)天前/.exec(date);
收到！已更新 PR，感谢 review 😄

2021-07-19 12:03 UTC, nczitzk commented on lib/routes/biodiscover/index.js
> +                        const re = /(\d+)天前/.exec(date);
😄🤝

2021-07-20 01:30 UTC, SettingDust requested changes

2021-07-20 01:30 UTC, SettingDust commented on lib/routes/biodiscover/index.js
> +                            description: $('.article').html(),
![Screenshot_2021_0720_092324.jpg](https://user-images.githubusercontent.com/19922286/126248121-55867456-9e69-4689-b80b-5f3daed8142a.jpg)
![Screenshot_2021_0720_092307.jpg](https://user-images.githubusercontent.com/19922286/126248132-cb92cb18-853d-4bdb-b1d4-a6127faa069d.jpg)
顶部底部垃圾信息处理下

2021-07-20 02:14 UTC, aidistan commented on lib/routes/biodiscover/index.js
> +                            description: $('.article').html(),
已处理，感谢建议

2021-07-20 02:25 UTC, SettingDust commented on lib/routes/biodiscover/index.js
> +                            description: $('.article').html(),
![Screenshot_2021_0720_102457.jpg](https://user-images.githubusercontent.com/19922286/126252675-6a075a85-c0e9-4283-b05a-d5532aead99f.jpg)
二重标题

2021-07-20 07:56 UTC, aidistan commented on lib/routes/biodiscover/index.js
> +                            description: $('.article').html(),
ok，我原以为需要保留，已在 https://github.com/aidistan/backup-RSSHub/commit/c89b57f5730e5ff249f652596b685e15e93a5a3d 中处理

2021-07-20 08:16 UTC, SettingDust approved these changes

2021-08-10 23:53 UTC, aidistan commented
请问什么时候可以 merge 一波呀？

2021-08-12 06:18 UTC, NeverBehave approved these changes

2021-08-12 06:20 UTC, merged