feat(route): add 北京大学学生就业指导服务中心
DIYgod/RSSHub pull request #7904
Opened 2021-07-20 11:28 UTC by DylanXie123

## 该 PR 相关 Issue / Involved issue

Close #7767

## 完整路由地址 / Example for the proposed route(s)

```routes
/pku/scc/recruit
/pku/scc/recruit/xwrd
/pku/scc/recruit/tzgg
/pku/scc/recruit/zpxx
/pku/scc/recruit/gfjgxx
/pku/scc/recruit/sxxx
/pku/scc/recruit/cyxx
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [x] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [x] 目标是否有提供日期？ Is there a date in the source?
  - [x] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [x] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-07-20 23:37 UTC, SettingDust requested changes

2021-07-20 23:37 UTC, SettingDust commented on lib/routes/universities/pku/scc/recruit.js
> +        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
ua 无法使用配置中的 ua？

2021-07-20 23:37 UTC, SettingDust commented on lib/routes/universities/pku/scc/recruit.js
> +    const sorted = list.sort((a, b) => b.pubDate.getTime() - a.pubDate.getTime()).slice(0, 10);
排序原因是？

2021-07-20 23:37 UTC, SettingDust commented on lib/routes/universities/pku/scc/recruit.js
> +                        const content_route = script.match(/\$\("#content-div"\).load\("(\S+)"\)/)[1];
示例报错？

2021-07-20 23:37 UTC, SettingDust commented on lib/routes/universities/pku/scc/recruit.js
> +        link: baseUrl,
给出对应分类的 link

2021-07-21 01:45 UTC, DylanXie123 commented on lib/routes/universities/pku/scc/recruit.js
> +    const sorted = list.sort((a, b) => b.pubDate.getTime() - a.pubDate.getTime()).slice(0, 10);
get 请求一次会拿到1000多条数据，其中前几条是置顶信息，之后的按时间顺序排列。因此需要重新按时间排序，过滤一下置顶信息。

2021-07-21 01:48 UTC, DylanXie123 commented on lib/routes/universities/pku/scc/recruit.js
> +                        const content_route = script.match(/\$\("#content-div"\).load\("(\S+)"\)/)[1];
本地没能复现这个问题，自己部署了一下，发现每次部署完后第一次请求会报错，之后的请求正常，可能和请求header有关，我再看一看。

2021-07-21 01:48 UTC, DylanXie123 commented on lib/routes/universities/pku/scc/recruit.js
> +        link: baseUrl,
👌

2021-07-24 03:05 UTC, DylanXie123 commented on lib/routes/universities/pku/scc/recruit.js
> +    await wait(500);
试了很多次，发现只有这样先请求一次，延迟一段时间后再请求才行

2021-07-25 07:23 UTC, SettingDust commented on lib/routes/universities/pku/scc/recruit.js
> +    await wait(500);
不能接受这个方法，不认为这是正确的答案

2022-02-01 16:42 UTC, TonyRL requested changes
v2 script standard https://github.com/DIYgod/RSSHub/discussions/8236

2022-04-24 15:14 UTC, merged