Feat/sjtu job
DIYgod/RSSHub pull request #7914
Opened 2021-07-24 08:04 UTC by DylanXie123

## 该 PR 相关 Issue / Involved issue

Close #7767

## 完整路由地址 / Example for the proposed route(s)

```routes
/sjtu/job/zpfw/zprd
/sjtu/job/zpfw/zpxx
/sjtu/job/zpfw/zpxx/new
/sjtu/job/zpfw/zpxx/allqy
/sjtu/job/zpfw/zpxx/gyqy
/sjtu/job/zpfw/zpxx/myqy
/sjtu/job/zpfw/zpxx/wzqy
/sjtu/job/zpfw/zpxx/qtqy
/sjtu/job/zpfw/zpxx/alldw
/sjtu/job/zpfw/zpxx/sxjz
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [x] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [x] 目标是否有提供日期？ Is there a date in the source?
  - [x] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [x] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-07-25 00:26 UTC, nczitzk approved these changes

2021-07-25 03:34 UTC, SettingDust requested changes

2021-07-25 03:34 UTC, SettingDust commented on lib/routes/universities/sjtu/job/zpfw.js
> +                        item.description = content('div#divnr').html();
最底部一个奇怪的table是干什么的？
过滤一下文内标题

2021-07-25 06:01 UTC, DylanXie123 commented on lib/routes/universities/sjtu/job/zpfw.js
> +                        item.description = content('div#divnr').html();
- 部分公告底部的附件信息会在table里
- 每个公告的文内标题格式都不统一，过滤会非常不方便

2021-07-25 07:21 UTC, SettingDust commented on lib/routes/universities/sjtu/job/zpfw.js
> +                        item.description = content('div#divnr').html();
> - 部分公告底部的附件信息会在table里

可以 text 判断是否为空

> - 每个公告的文内标题格式都不统一，过滤会非常不方便

可以 text() 比对

2021-09-26 09:01 UTC, NeverBehave commented
由于 #8236
旧版本的新路由请求将会被关闭，请按照新版路由规范修改后重新开启，谢谢！
需要帮助请在讨论下留言，我们可以协助迁移

2021-09-26 09:01 UTC, closed without merging