Nanjing Normal University(RSS)
DIYgod/RSSHub pull request #7932
Opened 2021-07-26 14:35 UTC by Shujakuinkuraudo

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/nnu/ceai/xygg
/nnu/ceai/xyxw
/nnu/ceai/xszx
/nnu/jwc/jstz
/nnu/jwc/xwdt
/nnu/jwc/xstz
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [x] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [x] 目标是否有提供日期？ Is there a date in the source?
  - [x] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [ ] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  ## 说明 / Note

2021-07-27 00:46 UTC, SettingDust requested changes

2021-07-27 00:46 UTC, SettingDust commented on lib/routes/universities/nnu/ceai/utils.js
> +            return Promise.resolve(Object.assign({}, single, other));
```suggestion
            return {...single, ...other};
```

2021-07-27 00:46 UTC, SettingDust commented on lib/routes/universities/nnu/jwc/utils.js
> +            return Promise.resolve(Object.assign({}, single, other));
```suggestion
            return {...single, ...other};
```

2021-07-27 00:46 UTC, SettingDust commented on lib/routes/universities/nnu/ceai/utils.js
> +    const pubDate = new Date(date.getTime() - 60 * 60 * 1000 * (timeZone + serverOffset)).toUTCString();
- [ ] https://docs.rsshub.app/joinus/pub-date.html
- [ ] 没有时间不需要处理时区

2021-07-27 00:46 UTC, SettingDust commented on lib/routes/universities/nnu/jwc/utils.js
> +    const pubDate = new Date(date.getTime() - 60 * 60 * 1000 * (timeZone + serverOffset)).toUTCString();
- [ ] https://docs.rsshub.app/joinus/pub-date.html
- [ ] 没有时间不需要处理时区

2021-07-27 00:49 UTC, SettingDust requested changes

2021-07-27 00:49 UTC, SettingDust commented on lib/routes/universities/nnu/ceai/ceai.js
> +    const list = $('span a').slice(0, 20).get();
请在稳定获取的基础上尽可能获取，rsshub会处理限制数量的操作

2021-07-27 00:49 UTC, SettingDust commented on lib/routes/universities/nnu/jwc/jwc.js
> +    const list = $('.list_txt a').slice(0, 16).get();
请在稳定获取的基础上尽可能获取，rsshub会处理限制数量的操作

2021-07-27 08:06 UTC, SettingDust requested changes

2021-07-27 08:06 UTC, SettingDust commented on lib/routes/universities/nnu/ceai/utils.js
> +    ).toUTCString();
https://docs.rsshub.app/joinus/pub-date.html

2021-07-27 08:54 UTC, SettingDust requested changes
force push 清理一下 commit，看这个 commit 信息垃圾 commit 太多了

2021-07-27 08:54 UTC, SettingDust commented on lib/routes/universities/nnu/ceai/utils.js
> +    const pubDate = new Date(date.getTime()).toUTCString();
正确处理日期，参见日期处理文档

2021-07-27 10:06 UTC, Shujakuinkuraudo commented on lib/routes/universities/nnu/ceai/utils.js
> +    const pubDate = new Date(date.getTime()).toUTCString();
请问有案例吗，我已经改懵了。

2021-07-27 10:47 UTC, SettingDust requested changes

2021-07-27 10:47 UTC, SettingDust commented on lib/routes/universities/nnu/ceai/utils.js
> +    const pubDate = new Date(
正确解析日期，参见文档日期处理

2021-07-27 10:47 UTC, SettingDust commented on lib/routes/universities/nnu/jwc/utils.js
> +    const pubDate = new Date($('span+ span').text().match(/\d{4}-\d{2}-\d{2}/)).toUTCString();
正确处理日期，参见文档日期处理

2021-07-27 15:11 UTC, SettingDust requested changes

2021-07-27 15:11 UTC, SettingDust commented on lib/routes/universities/nnu/ceai/utils.js
> +    const pubDate = timezone(date, +8);
只有日期就不要处理时区

2021-07-27 15:11 UTC, SettingDust commented on lib/routes/universities/nnu/jwc/utils.js
> +    const description = $('form > div').html();
只有日期不需要调整时区，只会更不准确

2021-07-28 00:39 UTC, SettingDust requested changes
commit 应该写清你做了什么，而不是无意的词。更改在本地测试后，确实完成了一部分工作后再提交，推送，而不是每个文件的修改都附带一个无含义的信息

2021-07-28 08:48 UTC, Shujakuinkuraudo commented
> commit 应该写清你做了什么，而不是无意的词。更改在本地测试后，确实完成了一部分工作后再提交，推送，而不是每个文件的修改都附带一个无含义的信息

第一次写pr，实在不好意思，给您添麻烦了😥😥😥

2022-02-01 17:26 UTC, TonyRL requested changes
v2 script standard https://github.com/DIYgod/RSSHub/discussions/8236

2022-02-23 18:21 UTC, TonyRL commented
Migrated to v2. `njnu` is not `nnu.`

2022-02-23 18:24 UTC, merged