feat(route): jandan add 煎蛋动物园、煎蛋大杂烩
DIYgod/RSSHub pull request #7935
Opened 2021-07-27 13:37 UTC by 9uanhuo

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/jandan/dzh
/jandan/zoo
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 目标是否有提供日期？ Is there a date in the source?
  - [ ] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [ ] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-07-27 14:17 UTC, 9uanhuo commented
> Successfully generated as following:
> 
> https://rsshub-do-not-use-9oo1nolhe-diy.vercel.app/jandan/dzh - **Failed**

`/jandan/dzh`路由已被移除，故为Failed，github-actions在我二次重新修改PR描述前就已开始重新检验提交运行，故仍旧检查了该路由。

2021-07-27 15:26 UTC, SettingDust requested changes
![Screenshot_20210727_232557](https://user-images.githubusercontent.com/19922286/127182053-35614522-aa3f-40ec-b625-6306deaaa52b.jpg)
页面上有作者、时间，而路由里都没有？

2021-07-28 00:37 UTC, 9uanhuo commented
> 页面上有作者、时间，而路由里都没有？

是的，煎蛋系列路由都没有作者和时间，如`lib\routes\jandan\article.js`第44行所示：

```javascript
const description = `<blockquote><p>${summary}</p></blockquote><img src="${imgUrl}">${fullText}`;
```

2021-07-28 00:41 UTC, SettingDust commented
> > 页面上有作者、时间，而路由里都没有？
> 
> 是的，煎蛋系列路由都没有作者和时间，如`lib\routes\jandan\article.js`第44行所示：
> 
> ```javascript
> const description = `<blockquote><p>${summary}</p></blockquote><img src="${imgUrl}">${fullText}`;
> ```
> 

那就需要增加

2021-07-28 01:13 UTC, 9uanhuo commented
> 那就需要增加，且作者和路由不是写入 description 的

好的，因为我本人对JavaScript并不是很熟悉，所以这个可能会花费相当长的一段时间

2021-08-05 08:05 UTC, 9uanhuo commented
> 那就需要增加，且作者和路由不是写入 description 的

已经完成作者信息以及时间的添加，由于jandan给出的不是标准的时间格式，所以无法计算具体的时间，所以RSS中的时间将是大概时间，具体的计算方式参见pic.js
关于CodeFactor指出的Complex Method问题，我暂时没有什么好的办法。

2021-08-05 08:09 UTC, SettingDust requested changes

2021-08-05 08:09 UTC, SettingDust commented on lib/routes/jandan/pic.js
> +        const [, time_diff, time_interval, ] = time_info.match(/@?(\d*) ?([^ ]+) ?([^ ]+)/);
相对时间参见文档 https://docs.rsshub.app/joinus/pub-date.html#shi-yong-gong-ju-lei-parse-date

2021-08-05 08:18 UTC, SettingDust commented on lib/routes/jandan/pic.js
> +        const [, time_diff, time_interval, ] = time_info.match(/@?(\d*) ?([^ ]+) ?([^ ]+)/);
等我改吧

2021-08-05 08:55 UTC, 9uanhuo commented on lib/routes/jandan/pic.js
> +        const [, time_diff, time_interval, ] = time_info.match(/@?(\d*) ?([^ ]+) ?([^ ]+)/);
我看了一下文档，parseRelativeDate只能处理中文样式的字符串，jandan这个比较奇葩，除了热榜部分的发帖时间格式是”@x小时 ago“，这个可以很轻松处理。但是热榜部分的时间就变成了”x hours ago“，这个需要手动把英语转成中文，才能被parseRelativeDate处理。

2021-08-05 08:58 UTC, 9uanhuo commented on lib/routes/jandan/pic.js
> +        const [, time_diff, time_interval, ] = time_info.match(/@?(\d*) ?([^ ]+) ?([^ ]+)/);
底下的代码是可以实现的，但是总感觉不简洁。
```javascript
        const text = $(item).find('.text p').text() || '';
        const post_author = $(item).find('.author strong').text() || '';
        const time_info =
            $(item)
                .find('.author small')
                .text()
                .replace('minutes', '分钟')
                .replace('hours', '小时')
                .replace('days', '天')
                .replace(/@?(\d*) ?([^ ]+) ?([^ ]+)/, '$1$2前') || '';
        const post_time = parseRelativeDate(time_info);
```

2021-08-05 09:04 UTC, 9uanhuo commented on lib/routes/jandan/pic.js
> +        const [, time_diff, time_interval, ] = time_info.match(/@?(\d*) ?([^ ]+) ?([^ ]+)/);
如果这样的代码是可以接受的话，我就再测试测试各个路由，然后提交，如果这样写不太好的话，那就只能麻烦您了 ; (

2021-08-07 10:35 UTC, SettingDust commented on lib/routes/jandan/pic.js
> +        const [, time_diff, time_interval, ] = time_info.match(/@?(\d*) ?([^ ]+) ?([^ ]+)/);
也可以，我提了一个 pr，不知道有库，那干吗要自己写时间解析啊，好怪

2021-08-07 13:06 UTC, 9uanhuo commented on lib/routes/jandan/pic.js
> +        const [, time_diff, time_interval, ] = time_info.match(/@?(\d*) ?([^ ]+) ?([^ ]+)/);
@SettingDust 不好意思，我刚看到您的pr。
@auto-bot-ty 煎蛋最大的问题是不同的版块使用的时间表示格式不同，并且存在中英混合使用的情况，又包含了分钟、小时、天等度量，所以现在的解决方式如下（参考）：
 * 替换所有中文为英文，并使用chrono解析
 * 替换所有英文为中文，使用`parseRelativeDate`解析
 还有其他的方法吗？希望各位能指出。

2021-08-08 07:32 UTC, 9uanhuo commented
由于commit次数过多，是否需要合并commits？

2021-08-09 02:33 UTC, SettingDust commented
可以

2021-08-15 04:42 UTC, 9uanhuo commented
commit合并完成，PR route test失败似乎是因为vercel方面原因而导致的部署失败，同时期很多的pr也出现了这个问题。

2021-08-25 06:17 UTC, 9uanhuo commented
/verify

2021-09-22 19:45 UTC, NeverBehave commented
修正一下lint，处理一下冲突

2021-09-23 03:35 UTC, 9uanhuo commented
> 修正一下lint，处理一下冲突

处理完毕

2021-09-23 04:18 UTC, merged