fix(route): 重庆大学本科教学信息网 (原重庆大学教务网)
DIYgod/RSSHub pull request #7944
Opened 2021-07-29 10:58 UTC by Hagb

## 该 PR 相关 Issue / Involved issue

无 

## 完整路由地址 / Example for the proposed route(s)

```routes
/cqu/jwc
/cqu/jwc/index/tzgg
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [x] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [x] 目标是否有提供日期？ Is there a date in the source?
  - [x] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [x] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-07-29 12:08 UTC, SettingDust requested changes

2021-07-29 12:08 UTC, SettingDust commented on docs/university.md
> +<Route author="El-Chiang Hagb" example="/cqu/jwc/" path="/cqu/jwc/:category?" :paramsDesc="['分类名']">
分类固定两个path，做成两个参数拼接一下更好，粘贴过来还要转码麻烦

2021-07-29 12:08 UTC, SettingDust commented on lib/routes/universities/cqu/jwc/announcement.js
>              return Promise.resolve(item);
```suggestion
            return item;
```

2021-07-29 12:08 UTC, SettingDust commented on lib/routes/universities/cqu/jwc/announcement.js
> +                date: timezone(parseDate(item.find('span[class=fr]').text(), 'YYYY-MM-DD'), +8),
class 选择器？

源站没有时间，不要处理时区

2021-07-29 12:08 UTC, SettingDust commented on lib/routes/universities/cqu/jwc/announcement.js
> +    const links = $('li[class=pot-r]', 'div[class="page-contner fl"]')
class 选择器

2021-07-29 14:39 UTC, Hagb commented on docs/university.md
> +<Route author="El-Chiang Hagb" example="/cqu/jwc/" path="/cqu/jwc/:category?" :paramsDesc="['分类名']">
> 分类固定两个path，做成两个参数拼接一下更好，粘贴过来还要转码麻烦

考虑到既有二级路径，又有三级路径，能不能改用这样的路由：
``` js
router.get('/cqu/jwc/:path+', require('./routes/universities/cqu/jwc/announcement'));
router.get('/cqu/jwc', require('./routes/universities/cqu/jwc/announcement'));
```

2021-07-29 14:46 UTC, Hagb commented on lib/routes/universities/cqu/jwc/announcement.js
> +                date: timezone(parseDate(item.find('span[class=fr]').text(), 'YYYY-MM-DD'), +8),
> class 选择器？
> 
> 源站没有时间，不要处理时区

不进行处理的话服务器时区还是会影响返回的时间。请问有没有办法让 RSSHub 返回的 rss 只包含日期信息而不包含时间？

2021-07-29 23:45 UTC, SettingDust requested changes

2021-07-29 23:45 UTC, SettingDust commented on lib/routes/universities/cqu/jwc/announcement.js
> +    const baseUrl = `http://jwc.cqu.edu.cn/${category.replace(/[^/]*$/, '')}`;
替换的原因是？

2021-07-29 23:45 UTC, SettingDust commented on lib/routes/universities/cqu/jwc/announcement.js
>              ctx.cache.set(item.link, JSON.stringify(item));
```suggestion
            ctx.cache.set(item.link, item);
```

为什么转换 json

2021-07-29 23:45 UTC, SettingDust commented on lib/routes/universities/cqu/jwc/announcement.js
> +        [...links].map(async ({ date, title, link }) => {
上文中links 本来就是数组吧？

```suggestion
        links.map(async ({ date, title, link }) => {
```

2021-07-30 00:05 UTC, Hagb commented on lib/routes/universities/cqu/jwc/announcement.js
> +    const baseUrl = `http://jwc.cqu.edu.cn/${category.replace(/[^/]*$/, '')}`;
`index/tzgg` 为例，对应的是 `http://jwc.cqu.edu.cn/index/tzgg.htm`，我这里想把 `http://jwc.cqu.edu.cn/index/` 取出来

2021-07-30 00:07 UTC, Hagb commented on lib/routes/universities/cqu/jwc/announcement.js
>              ctx.cache.set(item.link, JSON.stringify(item));
唔…… 写的时候直接在原代码的基础上改了…… 没细看里面的细节……

2021-07-30 03:35 UTC, SettingDust approved these changes

2021-08-12 09:03 UTC, NeverBehave commented on lib/routes/universities/cqu/jwc/announcement.js
> +                date: timezone(parseDate(item.find('span[class=fr]').text(), 'YYYY-MM-DD'), +8),
如果没有时间，日期本身是无法判断具体的时候的，早一天或者晚一天是可以接受的
影响返回的时间是指什么？

2021-08-12 09:03 UTC, NeverBehave approved these changes

2021-08-12 09:05 UTC, merged

2021-08-12 09:05 UTC, NeverBehave commented
Cool! Thanks for your contribution!

2021-08-12 09:53 UTC, Hagb commented on lib/routes/universities/cqu/jwc/announcement.js
> +                date: timezone(parseDate(item.find('span[class=fr]').text(), 'YYYY-MM-DD'), +8),
> 如果没有时间，日期本身是无法判断具体的时候的，早一天或者晚一天是可以接受的
> 影响返回的时间是指什么？

是指不处理时区的话，服务器设成不同时区时会返回的不同的 pubDate，Asia/Shanghai 时区下客户端显示的日期可能会比网页原文中的早一天（像国内大学教务处这类网站，发布者和用户几乎都是 Asia/Shanghai 时区下的）。

---

>> 请问有没有办法让 RSSHub 返回的 rss 只包含日期信息而不包含时间？

这个问题我收回… 刚刚去看了看 [https://www.rssboard.org/rss-specification](rss 规范)，发现 pubDate 不包含时间是不合规范的。