feat(route): add 温州大学新闻
DIYgod/RSSHub pull request #7952
Opened 2021-07-31 16:44 UTC by Chandler-Lu

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/wzu/news
```

## 新RSS检查列表 / New RSS Script Checklist

- x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [ ] 目标是否有提供日期？ Is there a date in the source?
  - [ ] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [ ] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-07-31 17:52 UTC, SettingDust requested changes

2021-07-31 17:52 UTC, SettingDust commented on docs/university.md
> +<Route author="Neutrino3316 MegrezZhu" example="/sysu/sdcs" path="/sysu/sdcs" /></Route>
这是？

2021-07-31 17:52 UTC, SettingDust commented on docs/university.md
> +### 温州大学
两个？

2021-07-31 17:52 UTC, SettingDust commented on docs/university.md
> +<Route author="Chandler-Lu" example="/wzu/news" path="/wzu/news" /></Route>
为什么要加闭标签

2021-07-31 17:52 UTC, SettingDust commented on lib/routes/universities/wzu/news.js
> +                    return { title: item.find('li a').attr('title'), description: item.find('li a').attr('title'), link: item.find('li a').attr('href') };
同样的元素可以存成变量而不是多次寻找
没有时间和描述，源网站有

2021-07-31 17:52 UTC, SettingDust commented on lib/routes/universities/wzu/news.js
> +    const list = $('#News-sidebar-b-nav').find('li').slice(0, 14);
无副作用的前提下获取尽量多

2021-08-01 00:36 UTC, Chandler-Lu commented on docs/university.md
> +<Route author="Chandler-Lu" example="/wzu/news" path="/wzu/news" /></Route>
啊不好意思我理解错了，我以为都要关闭

2021-08-01 01:44 UTC, SettingDust commented on docs/university.md
> +<Route author="Chandler-Lu" example="/wzu/news" path="/wzu/news" /></Route>
可是这已经关闭了

2021-08-01 01:46 UTC, Chandler-Lu commented on docs/university.md
> +<Route author="Chandler-Lu" example="/wzu/news" path="/wzu/news" /></Route>
我已经重新push了，麻烦您再看一下，谢谢

2021-08-01 01:59 UTC, SettingDust requested changes

2021-08-01 01:59 UTC, SettingDust commented on lib/routes/universities/wzu/news.js
> +    const list = $('#News-sidebar-b-nav').find('li').slice(0);
slice 的原因？

2021-08-01 01:59 UTC, SettingDust commented on lib/routes/universities/wzu/news.js
> +                    return { title: a1.attr('title'), description: a1.attr('title'), pubDate: item.find('li samp').text(), link: a1.attr('href') };
日期查看文档正确格式化，以及你这个代码跑过 lint？

2021-08-01 02:22 UTC, Chandler-Lu commented on lib/routes/universities/wzu/news.js
> +    const list = $('#News-sidebar-b-nav').find('li').slice(0);
请问这里不需要slice切成单个数据嘛

2021-08-01 02:23 UTC, Chandler-Lu commented on lib/routes/universities/wzu/news.js
> +                    return { title: a1.attr('title'), description: a1.attr('title'), pubDate: item.find('li samp').text(), link: a1.attr('href') };
请问Parse Date之后需要处理成GMT+8嘛，还是保持原样

2021-08-01 04:25 UTC, SettingDust commented on lib/routes/universities/wzu/news.js
> +    const list = $('#News-sidebar-b-nav').find('li').slice(0);
切成单个数据？

2021-08-01 04:26 UTC, SettingDust commented on lib/routes/universities/wzu/news.js
> +                    return { title: a1.attr('title'), description: a1.attr('title'), pubDate: item.find('li samp').text(), link: a1.attr('href') };
没时间就不处理

2021-08-01 05:13 UTC, Chandler-Lu commented on lib/routes/universities/wzu/news.js
> +                    return { title: a1.attr('title'), description: a1.attr('title'), pubDate: item.find('li samp').text(), link: a1.attr('href') };
已修正

2021-08-01 05:33 UTC, SettingDust approved these changes

2021-08-12 09:03 UTC, NeverBehave approved these changes

2021-08-12 09:07 UTC, NeverBehave approved these changes

2021-08-12 09:10 UTC, merged

2021-08-12 09:11 UTC, NeverBehave commented
🎉Yes! Your contribution has merged.