feat(route): add 西北农林科技大学
DIYgod/RSSHub pull request #7966
Opened 2021-08-04 03:43 UTC by dingyx99

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/nwafu/news
/nwafu/jiaowu
/nwafu/gs
/nwafu/lib
/nwafu/nic
/nwafu/54youth
/nwafu/jcc
/nwafu/yjshy
/nwafu/cie
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [x] 目标是否有提供日期？ Is there a date in the source?
  - [x] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [ ] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-08-05 00:11 UTC, SettingDust requested changes
日期需正确格式，查看文档日期处理

2021-08-05 03:51 UTC, dingyx99 commented
> 日期需正确格式，查看文档日期处理

已经按照要求修正。

2021-08-05 03:57 UTC, SettingDust reviewed
这些都一样不如写到一个文件？

2021-08-05 04:18 UTC, dingyx99 commented
> 这些都一样不如写到一个文件？

各个院系和单位的网站，相应需要提取的区域是有不同的，合并到一个文件后会略有点难处理，如之后想到更好的处理方法之后再考虑合并为一个文件。

2021-08-05 04:56 UTC, SettingDust approved these changes

2021-08-12 08:33 UTC, merged

2021-08-12 08:33 UTC, NeverBehave commented
Good job!