add juejin news
DIYgod/RSSHub pull request #7969
Opened 2021-08-05 11:58 UTC by CancerGary

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/juejin/news
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [x] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [x] 目标是否有提供日期？ Is there a date in the source?
  - [x] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [x] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-08-05 12:53 UTC, SettingDust requested changes

2021-08-05 12:53 UTC, SettingDust commented on lib/routes/juejin/utils.js
> +        pubDate: pubdate.toUTCString(),
正确处理时间

2021-08-05 12:53 UTC, SettingDust commented on lib/routes/juejin/utils.js
> +    const pubdate = new Date(parseInt(item.article_info.ctime) * 1000 - 8 * 60 * 60 * 1000);
正确处理时间

2021-08-05 12:53 UTC, SettingDust commented on lib/routes/juejin/utils.js
> +    const pubdate = new Date(parseInt(item.content_info.ctime) * 1000 - 8 * 60 * 60 * 1000);
正确处理时间

2021-08-05 13:56 UTC, CancerGary commented on lib/routes/juejin/utils.js
> +        pubDate: pubdate.toUTCString(),
migrated to `@/utils/timezone`

2021-08-05 14:03 UTC, SettingDust requested changes
https://github.com/DIYgod/RSSHub/blob/916e83d3ef4b7f8a3597b15c9e905d63a418cbfe/lib/routes/juejin/utils.js#L66-L68
```
 const other = await caches.tryGet(link, () => load(link)); 
 // 合并解析后的结果集作为该篇文章最终的输出结果 
 return { ...single, other }; 
```

2022-02-01 17:38 UTC, TonyRL requested changes
v2 script standard https://github.com/DIYgod/RSSHub/discussions/8236

2022-02-01 17:38 UTC, TonyRL commented on lib/routes/juejin/utils.js
> +    const pubdate = timezone(new Date(parseInt(item.article_info.ctime) * 1000), +8);
Please use parseDate() from `@/utils/parse-date`

2022-02-01 17:38 UTC, TonyRL commented on lib/routes/juejin/utils.js
> +    const pubdate = timezone(new Date(parseInt(item.content_info.ctime) * 1000), +8);
Please use parseDate() from `@/utils/parse-date`

2022-03-11 13:04 UTC, TonyRL requested changes
Please resolve merge conflicts

2022-05-19 17:55 UTC, merged