add 微博新鲜事
DIYgod/RSSHub pull request #7971
Opened 2021-08-06 07:01 UTC by zsh2517

## 该 PR 相关 Issue / Involved issue

Close #7400

## 完整路由地址 / Example for the proposed route(s)

```routes
/weibo/news/7574046780235777_1
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [x] 目标是否有提供日期？ Is there a date in the source?
  - [x] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [ ] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

根据原 issue #7400 判断该功能叫做“微博新鲜事”，因此文档等均叫做这个。对应页面如 [走心句子收纳](https://weibo.com/a/hot/7574046780235777_1.html) 内，微博官方未提供这个叫做什么，而且我个人微博使用不多。

2021-08-06 07:14 UTC, SettingDust commented
你路由写错了？pr 描述里怎么是 new

2021-08-06 07:27 UTC, zsh2517 commented
> 你路由写错了？pr 描述里怎么是 new

已更改。之前用的 news，后来考虑到因为模块命名不确定，就改成了 tag
代码正常工作

2021-08-07 10:29 UTC, SettingDust requested changes

2021-08-07 10:29 UTC, SettingDust commented on lib/routes/weibo/tag.js
> +        if ($(columns[i]).text().indexOf('精选内容') !== -1 || $(columns[i]).text().indexOf('全部微博') !== -1) {
判断存在 includes

2021-08-07 16:02 UTC, zsh2517 commented on lib/routes/weibo/tag.js
> +            'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1',
UA 在实现的时候参考了 `weibo` 路由下其他人的实现。试了一下，默认的 UA 可用

2021-10-05 09:32 UTC, NeverBehave commented
这个路由是一个子集的一部分，处理一下冲突可以合并

2021-10-05 09:32 UTC, NeverBehave requested changes
waiting feedback

2022-02-01 17:45 UTC, TonyRL requested changes
Please also update `docs/install/README.md` about this cookies

2022-02-01 17:45 UTC, TonyRL commented on lib/config.js
> +            cookies: weibo_available_cookies,
Please allow setting cookies via envs

2023-03-19 20:58 UTC, DIYgod commented
pr 时间过长，将先被关闭，如果还有疑问可以随时在下面继续讨论

2023-03-19 20:58 UTC, closed without merging