fix(route): fix pubDate for 新华社新闻
DIYgod/RSSHub pull request #7982
Opened 2021-08-08 07:53 UTC by auto-bot-ty

## 该 PR 相关 Issue / Involved issue

Close #7895

## 完整路由地址 / Example for the proposed route(s)

```routes
/news/whxw
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [ ] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [x] 目标是否有提供日期？ Is there a date in the source?
  - [x] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [x] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason
  

## 说明 / Note

2021-08-19 03:54 UTC, SettingDust commented
附带阅读器截图，xml 截图，一篇文章链接

2021-08-24 09:27 UTC, SettingDust commented
.editor 内内容可以作为作者抓取，从正文删除

2021-09-06 06:47 UTC, SettingDust requested changes

2021-09-08 16:23 UTC, SettingDust commented
实例路由报错，确认一下原因，抛出可读的异常

2021-09-09 04:17 UTC, SettingDust requested changes

2021-09-09 04:17 UTC, SettingDust commented on lib/routes/news/whxw.js
> +        ).filter((e) => e.description !== "")
```suggestion
        ).filter((e) => e.description.length)
```

2021-09-09 07:17 UTC, SettingDust requested changes

2021-09-09 07:17 UTC, SettingDust commented on lib/routes/news/whxw.js
> +                    item.description = '';
没有 description 就抛错吧？不然阅读器会漏 item 的

2021-09-09 07:43 UTC, SettingDust commented on lib/routes/news/whxw.js
> +                    item.description = '';
但是可以访问应该不会被 got 抛错吧？

2021-09-09 07:46 UTC, SettingDust commented on lib/routes/news/whxw.js
> +                    item.description = '';
了解，那可以不对 description 置值

2021-09-09 08:11 UTC, SettingDust requested changes

2021-09-09 08:11 UTC, SettingDust commented on lib/routes/news/whxw.js
> +                    item.pubDate = timezone(parseDate(date, 'YYYYMM/DD HH:mm:ss'), +8);
下面的为什么不放到 try 里？

2021-09-09 08:27 UTC, SettingDust commented on lib/routes/news/whxw.js
> +                    item.pubDate = timezone(parseDate(date, 'YYYYMM/DD HH:mm:ss'), +8);
ok

2021-09-09 08:27 UTC, SettingDust approved these changes

2021-09-23 04:48 UTC, NeverBehave approved these changes

2021-09-23 04:48 UTC, merged