feat: add tid for vsearch of bilibili
DIYgod/RSSHub pull request #8041
Opened 2021-08-17 16:10 UTC by libook

## 该 PR 相关 Issue / Involved issue

无

## 完整路由地址 / Example for the proposed route(s)

```routes
/bilibili/followings/dynamic/:uid/:disableEmbed?
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [ ] Documentation
  - [x] CN
  - [ ] EN
- [ ] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] 日期和时间 date and time
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

不是新RSS也不是新路由，是在原有Bilibili的搜索路由上增加分区参数，由于之前就没有相关英文文档，所以就只补充了中文文档。

2021-08-17 16:12 UTC, libook commented
为了避免产生breaking change，所以把新参数放到了最后。

2021-08-19 08:45 UTC, libook commented
请问我还需要做什么嘛？还是等维护者回复就好了？

2021-08-19 14:54 UTC, libook commented
@auto-bot-ty OK，已经改好了

2021-08-24 08:30 UTC, SettingDust approved these changes

2021-08-30 05:11 UTC, libook commented
请问可以合并了嘛？

2021-08-30 05:13 UTC, SettingDust requested changes

2021-08-30 05:13 UTC, SettingDust commented on docs/social-media.md
> +
注明是什么参数的表

2021-08-30 05:58 UTC, libook commented
@SettingDust 您好，已经补充了说明

2021-09-06 03:54 UTC, libook commented
@SettingDust 请问是否可以合并了呢？

2021-09-06 03:55 UTC, SettingDust approved these changes

2021-09-06 03:58 UTC, SettingDust requested changes

2021-09-06 03:58 UTC, SettingDust commented on lib/routes/bilibili/vsearch.js
> +    const tids = ctx.params.tid ?? 0;
空值合并无法在 node 12运行

2021-09-06 06:34 UTC, libook commented
@SettingDust 您好，已经改成了支持node v12的语法

2021-09-06 06:43 UTC, SettingDust requested changes

2021-09-06 06:43 UTC, SettingDust commented on package.json
> +  },
不应该更改

2021-09-06 06:43 UTC, SettingDust commented on lib/routes/bilibili/vsearch.js
> +    const tids = ctx.params.tid === undefined ? 0 : ctx.params.tid;
确认了一下，可以使用，前段时间刚更改，这个 commit 回退，force-push 掉吧

2021-09-06 06:43 UTC, SettingDust commented on docs/social-media.md
> +
修复了自己标为已解决

2021-09-06 06:44 UTC, SettingDust commented
不要随便 @ 人，不需要你 @ github 一样会通知相关项目的信息

2021-09-06 07:21 UTC, libook commented
我此前不@就好多天没人处理的，所以我不清楚是不是必须要@人。

目前已经按照SettingDust的说法回退commit并force-push了。

2021-09-08 02:24 UTC, libook commented
辛苦有人来看一下，是否还有需要改的地方呢？

2021-09-08 16:21 UTC, SettingDust requested changes
日期格式化安装文档修改，单个变量不要使用文本模板
https://github.com/DIYgod/RSSHub/blob/1d2a07e215d7c2868b46cf0487583c5cc2428ac0/lib/routes/bilibili/vsearch.js#L33-L48

https://github.com/DIYgod/RSSHub/blob/1d2a07e215d7c2868b46cf0487583c5cc2428ac0/lib/routes/bilibili/vsearch.js#L6
也需要 ??

2021-09-09 02:25 UTC, libook commented
@SettingDust 你说的这些都不是我的代码，我只是做了一个仅针对我的feature的精简提交，需要refactor其他代码的话，可以开新PR来做吧？

2021-09-09 04:15 UTC, SettingDust commented
> @SettingDust 你说的这些都不是我的代码，我只是做了一个仅针对我的feature的精简提交，需要refactor其他代码的话，可以开新PR来做吧？
> 请看具体的代码差异：https://github.com/DIYgod/RSSHub/pull/8041/files

日期处理不规范，不予通过

2021-09-09 06:21 UTC, libook commented
@SettingDust 大哥，这是2019年Symty提交的代码，master里就是这么写的，我PR不包含这段代码，为什么要卡我？

2021-09-09 07:05 UTC, SettingDust commented
> 为什么要卡我？

> 日期处理不规范，不予通过

2021-09-09 07:40 UTC, SettingDust requested changes

2021-09-09 07:40 UTC, SettingDust commented on lib/routes/bilibili/vsearch.js
> +                link: item.arcurl,
```suggestion
                link: item.arcurl,
```

2021-09-09 07:40 UTC, SettingDust commented on lib/routes/bilibili/vsearch.js
>                      `Tag: ${item.tag}<br/>` +
rss `category` 是 tag，请将 `item.tag` 传为标签数组到此属性中

2021-09-09 07:51 UTC, libook commented on lib/routes/bilibili/vsearch.js
>                      `Tag: ${item.tag}<br/>` +
上面已经有category了，取的是item.typename，意思是让我把item.typename删掉，替换成item.tag?

2021-09-09 07:52 UTC, libook commented on lib/routes/bilibili/vsearch.js
>                      `Tag: ${item.tag}<br/>` +
这个路由的原作者想的是让视频分区作为视频的category，B站的tags是标签

2021-09-09 07:53 UTC, SettingDust commented on lib/routes/bilibili/vsearch.js
>                      `Tag: ${item.tag}<br/>` +
你可以 merge，而不是替换，`category: [item.typename, ...item.tag]`

2021-09-09 07:55 UTC, libook commented on lib/routes/bilibili/vsearch.js
>                      `Tag: ${item.tag}<br/>` +
我的意思是说，你很确定category必须同时包含typename和tag的值是嘛？或者说你很确定，B站的tag适合这么用是嘛

2021-09-09 07:56 UTC, libook commented on lib/routes/bilibili/vsearch.js
>                      `Tag: ${item.tag}<br/>` +
这是一个主观判断，不是一个客观规定，你要是强制要求的话，我就加上，觉得可能不是那么合适的话我就先不加

2021-09-09 07:59 UTC, SettingDust commented on lib/routes/bilibili/vsearch.js
>                      `Tag: ${item.tag}<br/>` +
do

2021-09-09 08:03 UTC, libook commented
改完了

2021-09-09 08:15 UTC, SettingDust approved these changes

2021-09-09 08:19 UTC, NeverBehave commented on lib/routes/bilibili/vsearch.js
> +                category: [item.typename].concat(item.tag.split(',')),
```suggestion
                category: [...item.tag.split(','), item.typename],
```

2021-09-09 08:19 UTC, NeverBehave commented on lib/routes/bilibili/vsearch.js
>                      `Category: ${item.typename}<br/>` +
```suggestion

```

2021-09-09 08:20 UTC, NeverBehave commented on lib/routes/bilibili/vsearch.js
>                      `Author: ${item.author}    (ID: ${item.mid})<br/>` +
```suggestion
                    `AuthorID: ${item.mid}<br/>` +
```

2021-09-09 08:24 UTC, NeverBehave approved these changes

2021-09-09 08:25 UTC, merged

2021-09-09 08:25 UTC, NeverBehave commented
Awesome! Thank you for your hard work!