fix(route): 站酷发现有视频条目
DIYgod/RSSHub pull request #8044
Opened 2021-08-18 16:12 UTC by nczitzk

## 该 PR 相关 Issue / Involved issue

Close #8034

## 完整路由地址 / Example for the proposed route(s)

```routes
/zcool/discover/home
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [x] Documentation
  - [x] CN
  - [ ] EN
- [x] 全文获取 fulltext
  - [x] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] 日期和时间 date and time
  - [x] 可以解析 Parsed
  - [x] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2021-08-19 04:14 UTC, SettingDust requested changes

2021-08-19 04:14 UTC, SettingDust commented on lib/routes/zcool/discover.js
>                  item.description = item.link.indexOf('article') < 0 ? content('.work-content-wrap').html() : content('.article-content-wraper').html();
```suggestion
                item.description = item.link.includes('article') ? content('.work-content-wrap').html() : content('.article-content-wraper').html();
```

2021-08-19 04:14 UTC, SettingDust commented on lib/routes/zcool/discover.js
> +                    content('.video-content-box').each(function () {
each 我记得有 elem 和 index 参数，引入一个 i 的原因是？

2021-08-20 00:12 UTC, nczitzk commented on lib/routes/zcool/discover.js
> +                    content('.video-content-box').each(function () {
😂

2021-08-20 06:02 UTC, SukkaW approved these changes

2021-08-20 06:02 UTC, merged