fix: add Lofter话题/标签文章分类 & 视频
DIYgod/RSSHub pull request #8054
Opened 2021-08-20 16:20 UTC by nczitzk

## 该 PR 相关 Issue / Involved issue

Close #7996

## 完整路由地址 / Example for the proposed route(s)

```routes
/lofter/tag/摄影/date
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [x] Documentation
  - [x] CN
  - [x] EN
- [x] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] 日期和时间 date and time
  - [x] 可以解析 Parsed
  - [x] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2021-08-23 23:10 UTC, SettingDust requested changes

2021-08-23 23:10 UTC, SettingDust commented on lib/routes/lofter/tag.js
>              });
用 map

2021-08-23 23:10 UTC, SettingDust commented on lib/routes/lofter/tag.js
> +            });
reduce

2021-11-27 07:39 UTC, DIYgod approved these changes

2021-11-27 07:39 UTC, merged