Fix: add pubDate to /matters/* and move /matters/tags to graphql api.
DIYgod/RSSHub pull request #8056
Opened 2021-08-21 07:54 UTC by FledgeXu

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)
```routes
/matters/latest/heat
/matters/tags/:tid
/matters/author/:uid
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [ ] Documentation
  - [ ] CN
  - [ ] EN
- [ ] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] 日期和时间 date and time
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2021-08-21 09:20 UTC, SettingDust commented
路由地址需要填示例地址而不是含参数变量的程序地址

2021-08-21 09:22 UTC, FledgeXu commented
@SettingDust Ok

2021-08-23 23:02 UTC, SettingDust requested changes
源站是有多种语言的，那就请把简体中文文档相应分类部分改成简体中文

2021-08-23 23:37 UTC, FledgeXu commented
@SettingDust 我有点没懂「简体中文文档相应分类部分改成简体中文」是什么意思，是需要把简体中文文档中关于Matters里的内容，从繁体改成简体吗？
我姑且改了一下。

2021-08-24 08:01 UTC, SettingDust approved these changes

2021-09-09 08:44 UTC, NeverBehave approved these changes

2021-09-09 08:45 UTC, merged

2021-09-09 08:46 UTC, NeverBehave commented
You made it! Thank you!