fix: add Lofter用户文章分类 & 视频
DIYgod/RSSHub pull request #8061
Opened 2021-08-21 23:01 UTC by nczitzk

## 该 PR 相关 Issue / Involved issue

Close #8037

## 完整路由地址 / Example for the proposed route(s)

```routes
/lofter/user/i
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [x] Documentation
  - [x] CN
  - [x] EN
- [x] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] 日期和时间 date and time
  - [x] 可以解析 Parsed
  - [x] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2021-08-23 04:48 UTC, SettingDust requested changes

2021-08-23 04:48 UTC, SettingDust commented on lib/routes/lofter/user.js
> +            'User-Agent': 'LOFTER/10.0.0 (iPhone; iOS 15.0; Scale/2.00)',
UA 无法使用配置？

2021-08-23 04:48 UTC, SettingDust commented on lib/routes/lofter/user.js
> +            limit: '50',
设置一个上限读取 limit query 参数好些？

2021-08-26 05:25 UTC, SettingDust requested changes

2022-02-01 18:17 UTC, TonyRL requested changes
v2 script standard https://github.com/DIYgod/RSSHub/discussions/8236

2022-02-23 16:23 UTC, merged