update docs
DIYgod/RSSHub pull request #8063
Opened 2021-08-22 04:01 UTC by ding667

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
NOROUTE
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [ ] Documentation
  - [ ] CN
  - [ ] EN
- [ ] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] 日期和时间 date and time
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note
修改youtube关于api key的描述，
修改社交媒体中对youtube官方rss的描述
Modify the description of youtube about api key.
Modify the description of youtube official rss in social media

2021-08-23 04:25 UTC, SettingDust requested changes

2021-08-23 04:25 UTC, SettingDust commented on docs/social-media.md
> +但并没有内嵌视频，不推荐使用。
```suggestion
注：无内嵌视频
```

2021-08-23 04:25 UTC, SettingDust commented on docs/en/social-media.md
> +However, there is no embedded video and it is not recommended.
```suggestion
Note, there isn't embedded video.
```

2021-08-23 04:25 UTC, SettingDust commented on docs/en/install/README.md
> +-   youtube: [API Key application](https://console.cloud.google.com/apis/api/youtube.googleapis.com/overview?project=mineral-nebula-309007)
为什么包含项目参数？
```suggestion
-   youtube: [API Key application](https://console.cloud.google.com/apis/api/youtube.googleapis.com/overview)
```

2021-08-23 04:25 UTC, SettingDust commented on docs/install/README.md
> +-   youtube 全部路由：[申请地址](https://console.cloud.google.com/apis/api/youtube.googleapis.com/overview?project=mineral-nebula-309007)
```suggestion
-   youtube 全部路由：[申请地址](https://console.cloud.google.com/apis/api/youtube.googleapis.com/overview)
```

2021-08-23 04:25 UTC, SettingDust commented on docs/install/README.md
> +    ![配置示例](https://i.loli.net/2021/08/21/ylpSmNFKOCYPLIh.png)
在我这里图片无法打开

2021-08-24 07:30 UTC, ding667 commented on docs/en/install/README.md
> +-   youtube: [API Key application](https://console.cloud.google.com/apis/api/youtube.googleapis.com/overview?project=mineral-nebula-309007)
抱歉，没注意到

2021-08-24 07:30 UTC, ding667 commented on docs/install/README.md
> +    ![配置示例](https://i.loli.net/2021/08/21/ylpSmNFKOCYPLIh.png)
那请删掉这一段吧，可能会增加部署难度。

2021-08-24 08:17 UTC, SettingDust commented on docs/install/README.md
> +    ![配置示例](https://i.loli.net/2021/08/21/ylpSmNFKOCYPLIh.png)
你可以直接 commit

2021-08-24 09:26 UTC, SettingDust approved these changes

2021-09-09 08:29 UTC, merged