feat(route): add "micmicidol"
DIYgod/RSSHub pull request #8070
Opened 2021-08-22 11:21 UTC by KotoriK

## 该 PR 相关 Issue / Involved issue

## 完整路由地址 / Example for the proposed route(s)

```routes
/micmicidol
/micmicidol/search/Young%20Jump/20
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [X] New Route
- [X] Documentation
  - [X] CN
  - [ ] EN
- [X] 全文获取 fulltext
  - [X] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [X] 日期和时间 date and time
  - [X] 可以解析 Parsed
  - [X] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2021-08-23 03:26 UTC, SettingDust requested changes

2021-08-23 03:26 UTC, SettingDust commented on docs/picture.md
> +<Route author="KotoriK" example="/micmicidol/search/Young%20Jump/20" path="/micmicidol/search/:label/:max?" :paramsDesc="['标签名','最多返回多少条结果']">
返回结果数量由中间件统一控制

2021-08-23 03:26 UTC, SettingDust commented on lib/routes/micmicidol/article.js
> +    const pubDate = parseDate(matchResult + ' +0000', 'MMMM D, YYYY Z');
时区可以使用 timezone 处理

2021-08-23 03:26 UTC, SettingDust commented on lib/routes/micmicidol/article.js
> +        description: $('.post-body.entry-content').html(),
`<br> <a name="more" href="https://www.micmicidol.com/2021/08/undefined"></a><br> <br> <br>`

正文存在奇怪的空白

2021-08-23 03:26 UTC, SettingDust commented on lib/routes/micmicidol/search.js
> +    const { label, max = 10 } = ctx.params;
最大数量可以读取 limit query 参数，给一个默认值在文档中注明即可

2021-08-23 04:35 UTC, KotoriK commented on lib/routes/micmicidol/search.js
> +    const { label, max = 10 } = ctx.params;
路由的文档需要额外注明有这个参数吗

2021-08-23 04:37 UTC, SettingDust commented on lib/routes/micmicidol/search.js
> +    const { label, max = 10 } = ctx.params;
既然包含特殊行为（默认值），那就要注明默认值

2021-08-23 05:18 UTC, KotoriK commented on lib/routes/micmicidol/article.js
> +    const pubDate = parseDate(matchResult + ' +0000', 'MMMM D, YYYY Z');
原文仅提供日期，没有具体时间，所以提供了一个时区以让日期在国内时区显示正确。

2021-08-23 06:06 UTC, SettingDust requested changes

2021-08-23 06:13 UTC, KotoriK commented on lib/routes/micmicidol/article.js
> +    const pubDate = parseDate(matchResult + ' +0000', 'MMMM D, YYYY Z');
在解析阶段可以直接设定时区就没必要再用timezone工具了吧

2021-08-23 06:15 UTC, SettingDust commented on lib/routes/micmicidol/article.js
> +    const pubDate = parseDate(matchResult + ' +0000', 'MMMM D, YYYY Z');
这就是在解析阶段使用的，且只是说“可以用”

2021-08-23 06:16 UTC, KotoriK commented on lib/routes/micmicidol/article.js
> +    const pubDate = parseDate(matchResult + ' +0000', 'MMMM D, YYYY Z');
好的 我理解了

2021-08-23 22:54 UTC, SettingDust approved these changes

2021-09-09 08:30 UTC, NeverBehave approved these changes

2021-11-27 07:47 UTC, DIYgod approved these changes

2021-11-27 07:47 UTC, merged