feat(middleware): `brief` parameter [WIP, don’t merge]
DIYgod/RSSHub pull request #8074
Opened 2021-08-22 16:31 UTC by tpnonthealps

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
NOROUTE
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [ ] Documentation
  - [ ] CN
  - [ ] EN
- [ ] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] 日期和时间 date and time
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2021-09-05 00:49 UTC, SettingDust requested changes

2021-09-05 00:49 UTC, SettingDust commented on lib/middleware/parameter.js
> +                    });
直接抛错，别动 item

2021-09-05 00:49 UTC, SettingDust commented on lib/middleware/parameter.js
> +                        item.description = `<p>${btext}</p>`;
没有 description 的情况下置 description 为 `<p>${btext}</p>`？为什么

2021-09-08 12:41 UTC, tpnonthealps commented on lib/middleware/parameter.js
> +                    });
經測試中間件無法直接拋錯，出錯時會自動忽略而不提醒，故如此處理。

2021-09-08 12:42 UTC, tpnonthealps commented on lib/middleware/parameter.js
> +                        item.description = `<p>${btext}</p>`;
有推薦的處理方法嗎？我之前一直是這樣寫。

2021-09-08 13:05 UTC, SettingDust commented on lib/middleware/parameter.js
> +                        item.description = `<p>${btext}</p>`;
不是有问题，是问这个逻辑是为什么，item 无描述就返回 `<p>${item.description}</p>`

2021-09-08 13:08 UTC, SettingDust commented on lib/middleware/parameter.js
> +                    });
你的测试可能出问题了，建议重测，本函数最上方就在 throw

2021-09-09 07:25 UTC, SettingDust commented on lib/middleware/parameter.js
> +                        item.description = `<p>${btext}</p>`;
所以，为什么 description 是空的，要返回 `<p></p>`

2021-09-09 07:31 UTC, tpnonthealps commented on lib/middleware/parameter.js
> +                        item.description = `<p>${btext}</p>`;
希望返回空的嗎？`<p></p>`？

2021-09-09 07:33 UTC, SettingDust commented on lib/middleware/parameter.js
> +                        item.description = `<p>${btext}</p>`;
不是希望，而是这个逻辑不合理，请改成合理的符合客户端（阅读器）预期的结果

2021-09-09 08:13 UTC, SettingDust requested changes

2021-09-09 08:13 UTC, SettingDust commented on lib/middleware/parameter.js
> +                    throw Error(`<p>Invalid parameter <code>brief=${ctx.query.brief}</code>.</p><p>參數 <code>brief=${ctx.query.brief}</code> 不合規範。</p><p>参数 <code>brief=${ctx.query.brief}</code> 不合规范。<
英文

2021-09-09 08:25 UTC, SettingDust requested changes

2021-09-09 08:25 UTC, SettingDust commented on lib/middleware/parameter.js
> +                    throw Error(`Invalid parameter <code>brief=${ctx.query.brief}</code>.`);
```suggestion
                    throw Error(`Invalid parameter <code>brief=${ctx.query.brief}</code>. Please check the doc https://docs.rsshub.app/parameter.html#shu-chu-jian-xun`);
```

2021-09-09 08:33 UTC, SettingDust approved these changes

2021-09-09 08:35 UTC, NeverBehave approved these changes

2021-09-09 08:37 UTC, merged