fix(route):解决漫画柜和镜像站没有pubDate问题
DIYgod/RSSHub pull request #8076
Opened 2021-08-22 17:11 UTC by marvolo666

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/mhgui/comic/:id
/manhuagui/comic/:id
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [ ] Documentation
  - [ ] CN
  - [ ] EN
- [ ] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] 日期和时间 date and time
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note
调整了pubDate,已解决每次检查都能获取到大量未读(实际已读)的文章

2021-08-23 03:07 UTC, SettingDust requested changes
pr 正文的路由路径是示例路径而不是程序路径

2021-08-23 03:07 UTC, SettingDust commented on lib/routes/manhuagui/comic.js
> +    //增加了pubDate以免每次更新都十几个未读
这是 guid 的问题

2021-08-23 03:07 UTC, SettingDust commented on lib/routes/manhuagui/comic.js
> +            let p_date = new Date('1900-01-01').toUTCString();
小驼峰命名，下面一致

2021-08-23 16:47 UTC, marvolo666 commented
已修改

2021-08-23 22:49 UTC, SettingDust commented
PR 正文路由参考其他 pr 修改

2021-09-08 04:01 UTC, SettingDust commented
pr 正文的路由路径是示例路径而不是程序路径

2021-09-10 13:41 UTC, closed without merging