fix: 网易号（通用）
DIYgod/RSSHub pull request #8077
Opened 2021-08-23 04:40 UTC by mjysci

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/netease/dy2/T1555591616739
/netease/dy2/T1482377048407
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [ ] Documentation
  - [ ] CN
  - [ ] EN
- [ ] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] 日期和时间 date and time
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note
163网页改版，全部采用`utf-8`编码，故无需再判断三级域名并从`gbk`和`utf-8`中选择。
本地测试无误。

2021-08-23 04:50 UTC, SettingDust requested changes
修改不需要重新开启拉取请求

2021-08-23 04:50 UTC, SettingDust commented on lib/routes/netease/dy2.js
> +                    ).data
有运行过 lint 任务吗？

```suggestion
                () => (
                    got.get(item.link, {
                        responseType: 'buffer',
                    })
                ).data
```

https://github.com/DIYgod/RSSHub/pull/8077/files#diff-b51b5a6ac4c00d72e82e8d8577aea2a49610113480620c8546f385c39501deb8R45-R53

```
return {
    title: item.title,
    link: item.link,
    description: content('.post_body').html(),
    pubDate: item.pubDate,
};
```

2021-08-23 04:55 UTC, mjysci commented on lib/routes/netease/dy2.js
> +                    ).data
commit时已自动做过代码检查并通过，无需改动，以免改了之后[测试不通过](https://github.com/DIYgod/RSSHub/pull/8066#issuecomment-903433513)。

2021-08-23 05:04 UTC, SettingDust commented on lib/routes/netease/dy2.js
> +                    ).data
需要改动，以及修改不需要开启另一个 PR。不通过是我代码的问题而不是不需要修改

2021-08-23 05:08 UTC, SettingDust requested changes
https://github.com/DIYgod/RSSHub/blob/8789646b4783233c332fdc8024e9ebaf9c699720/lib/routes/netease/dy2.js#L16

在无副作用的前提下尽可能多的获取，可以采用 limit query 参数来限制长度，定义一个默认值并在文档中注明即可

2021-08-23 05:13 UTC, mjysci commented
> https://github.com/DIYgod/RSSHub/blob/8789646b4783233c332fdc8024e9ebaf9c699720/lib/routes/netease/dy2.js#L16
> 
> 在无副作用的前提下尽可能多的获取，可以采用 limit query 参数来限制长度，定义一个默认值并在文档中注明即可

有副作用，非API方式抓取会触发163反爬，故限制为每次抓取5条，以各个网易号的更新频率而言足够了。

2021-08-23 05:19 UTC, SettingDust commented
https://github.com/DIYgod/RSSHub/pull/8077/files#r693648609

2021-08-23 12:26 UTC, mjysci commented
> https://github.com/DIYgod/RSSHub/pull/8077/files#r693648609

这个项目在commit前会自动运行`npm run format:staged`，没有问题。
手动运行`npm run lint`，没有问题。
手动运行`./node_modules/.bin/eslint lib/routes/netease/dy2.js`，没有问题。
代码在本地测试和[在线测试](https://github.com/DIYgod/RSSHub/pull/8066#issuecomment-903213475)均无报错，通过测试，且功能符合预期。
代码无需修改。

2021-08-23 12:52 UTC, SettingDust commented
> > https://github.com/DIYgod/RSSHub/pull/8077/files#r693648609
> 
> 这个项目在commit前会自动运行`npm run format:staged`，没有问题。
> 手动运行`npm run lint`，没有问题。
> 手动运行`./node_modules/.bin/eslint lib/routes/netease/dy2.js`，没有问题。
> 代码在本地测试和[在线测试](https://github.com/DIYgod/RSSHub/pull/8066#issuecomment-903213475)均无报错，通过测试，且功能符合预期。
> 代码无需修改。

**需要做出相应修改**

2022-02-01 18:25 UTC, TonyRL commented
Superseded by #8083

2022-02-01 18:25 UTC, closed without merging