feat(route): add Netflix Newsroom
DIYgod/RSSHub pull request #8135
Opened 2021-09-03 01:33 UTC by nczitzk

## 该 PR 相关 Issue / Involved issue

Close #8131

## 完整路由地址 / Example for the proposed route(s)

```routes
/netflix/newsroom
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [x] New Route
- [x] Documentation
  - [x] CN
  - [ ] EN
- [x] 全文获取 fulltext
  - [x] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] 日期和时间 date and time
  - [x] 可以解析 Parsed
  - [x] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2021-09-09 08:19 UTC, SettingDust requested changes

2021-09-09 08:19 UTC, SettingDust commented on lib/routes/netflix/newsroom.js
> +    const region = ctx.params.region || 'en';
```suggestion
    const category = ctx.params.category ?? 'all';
    const region = ctx.params.region ?? 'en';
```

2021-09-09 08:40 UTC, SettingDust approved these changes

2021-09-09 08:57 UTC, NeverBehave approved these changes

2021-11-27 07:50 UTC, DIYgod approved these changes

2021-11-27 07:50 UTC, merged