fix(route): dapenti/tugua pubDate and author
DIYgod/RSSHub pull request #8141
Opened 2021-09-03 16:09 UTC by TonyRL

## 该 PR 相关 Issue / Involved issue

Close #7343 

## 完整路由地址 / Example for the proposed route(s)

```routes
/dapenti/tugua
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [ ] Documentation
  - [ ] CN
  - [ ] EN
- [ ] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] 日期和时间 date and time
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2021-09-08 23:46 UTC, SettingDust requested changes
https://github.com/DIYgod/RSSHub/blob/ef73f5e60429d1dfea59b543c801ebd376cd7c93/lib/routes/dapenti/utils.js#L63

不要乱 resolve，返回就行了

2021-09-09 00:12 UTC, TonyRL commented
FYI, I’m not the one who wrote that line, @xyqfer does. (From git blame)
Anyways, the suggested changes will still be pushed.

2021-09-09 07:52 UTC, SettingDust approved these changes

2021-09-09 08:38 UTC, NeverBehave approved these changes

2021-09-09 08:39 UTC, merged