fix(route): 全现在首页
DIYgod/RSSHub pull request #8142
Opened 2021-09-04 02:41 UTC by nczitzk

## 该 PR 相关 Issue / Involved issue

Close #8136

## 完整路由地址 / Example for the proposed route(s)

```routes
/allnow
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [x] Documentation
  - [x] CN
  - [ ] EN
- [x] 全文获取 fulltext
  - [x] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] 日期和时间 date and time
  - [x] 可以解析 Parsed
  - [x] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2021-09-08 23:40 UTC, SettingDust requested changes

2021-09-08 23:40 UTC, SettingDust commented on lib/routes/allnow/utils.js
> +                    item.description = content('#article-content').html() || content('.summary').html() || '';
```suggestion
                    item.description = content('#article-content').html() ?? content('.summary').html() ?? '';
```

2021-09-08 23:40 UTC, SettingDust commented on lib/routes/allnow/utils.js
> +            description: $('.desc').eq(0).text(),
我记得 text/html 函数的默认行为就是取第一个的

2021-09-08 23:40 UTC, SettingDust commented on lib/routes/allnow/utils.js
> +    ProcessItems: async (ctx, currentUrl) => {
```suggestion
    processItems: async (ctx, currentUrl) => {
```

函数小驼峰

2021-09-08 23:49 UTC, nczitzk commented on lib/routes/allnow/utils.js
> +            description: $('.desc').eq(0).text(),
谢谢 review 😊 这个似乎默认是把所有符合的内容都取出来了

2021-09-08 23:49 UTC, SettingDust requested changes

2021-09-08 23:49 UTC, SettingDust commented on lib/routes/allnow/column.js
> +    ctx.state.data = await utils.ProcessItems(ctx, `${utils.rootUrl}/column/${id}`);
调用点~

2021-09-08 23:56 UTC, SettingDust commented on lib/routes/allnow/utils.js
> +            description: $('.desc').eq(0).text(),
确实

2021-09-08 23:57 UTC, SettingDust approved these changes

2021-09-09 08:50 UTC, NeverBehave approved these changes

2021-09-09 08:51 UTC, merged