更新路由 universities/dut
DIYgod/RSSHub pull request #8144
Opened 2021-09-04 14:22 UTC by BeautyYuYanli

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/dut/its/zxdt
/dut/its/zxtz
/dut/its/aqgg
/dut/ee/xbxw
/dut/ee/xbtz
/dut/ee/xskyhd
/dut/ee/bks
/dut/ee/yjs
/dut/eda/tzgg
/dut/eda/xqxw
/dut/ssdut/bkstz
/dut/ssdut/yjstz
/dut/ssdut/xytz
/dut/ssdut/xsdt
/dut/gach/gzdt
/dut/gach/tzgg
/dut/gach/djyd
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [*] New Route
- [*] Documentation
  - [*] CN
  - [ ] EN
- [*] 全文获取 fulltext
  - [*] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [*] 日期和时间 date and time
  - [*] 可以解析 Parsed
  - [*] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

为路由 `universities/dut` 新增了子项, 更改部分页面通过webvpn

2021-09-04 14:33 UTC, BeautyYuYanli commented
> [rsshub-9hwwynzzo-diy.vercel.app/dut/ee/xbxw](https://rsshub-9hwwynzzo-diy.vercel.app/dut/ee/xbxw) - **Failed**
> [rsshub-9hwwynzzo-diy.vercel.app/dut/ee/xbtz](https://rsshub-9hwwynzzo-diy.vercel.app/dut/ee/xbtz) - **Failed**
> [rsshub-9hwwynzzo-diy.vercel.app/dut/ee/xskyhd](https://rsshub-9hwwynzzo-diy.vercel.app/dut/ee/xskyhd) - **Failed**
> [rsshub-9hwwynzzo-diy.vercel.app/dut/ee/bks](https://rsshub-9hwwynzzo-diy.vercel.app/dut/ee/bks) - Success
> [rsshub-9hwwynzzo-diy.vercel.app/dut/ee/yjs](https://rsshub-9hwwynzzo-diy.vercel.app/dut/ee/yjs) - **Failed**

这里有几个 failed, 但我并不能在本地复现...

2021-09-09 08:09 UTC, SettingDust requested changes

2021-09-09 08:09 UTC, SettingDust commented on lib/routes/universities/dut/webvpn/package.json
> +}
这文件是？

2021-09-09 08:09 UTC, SettingDust commented on lib/routes/universities/dut/subsite.js
> +        },
用 parseDate 解析，不要自己文本拼接

2021-09-09 14:05 UTC, BeautyYuYanli commented on lib/routes/universities/dut/webvpn/package.json
> +}
原本是作为一个包的 忘了删掉

2021-09-09 14:30 UTC, SettingDust commented
commit 有好多重复的，reset & force push 清理一下

2021-09-09 14:57 UTC, BeautyYuYanli commented
已经清理了 commits, 但似乎还有些脏历史我记不清了(这些问题来自一次错误的rebase

不过合并 pr 的时候似乎会把 commits 打包成一个再并入, 所以问题应该不大?

2022-02-01 18:38 UTC, TonyRL requested changes
v2 script standard https://github.com/DIYgod/RSSHub/discussions/8236

Please fix https://github.com/DIYgod/RSSHub/pull/8144/files#r705091185

Please fix DeepScan issue

2023-01-02 16:18 UTC, closed without merging