feat(route): add SBS中文
DIYgod/RSSHub pull request #8149
Opened 2021-09-06 07:12 UTC by nczitzk

## 该 PR 相关 Issue / Involved issue

Close #8147

## 完整路由地址 / Example for the proposed route(s)

```routes
/sbs/chinese
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [x] New Route
- [x] Documentation
  - [x] CN
  - [x] EN
- [x] 全文获取 fulltext
  - [x] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] 日期和时间 date and time
  - [x] 可以解析 Parsed
  - [x] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2021-09-08 16:31 UTC, SettingDust requested changes

2021-09-08 16:31 UTC, SettingDust commented on lib/routes/sbs/chinese.js
> +    const language = ctx.params.language || dialect === 'mandarin' ? 'zh-hans' : 'zh-hant';
```suggestion
    const id = ctx.params.id ?? 'news';
    const dialect = ctx.params.dialect ?? 'mandarin';
    const category = ctx.params.category ?? 'news';
    const language = ctx.params.language ?? dialect === 'mandarin' ? 'zh-hans' : 'zh-hant';
```

2021-09-08 16:31 UTC, SettingDust commented on lib/routes/sbs/chinese.js
> +                const image = content('meta[itemprop="image"]') ? content('meta[itemprop="image"]').attr('content').split('/crop/')[0] : '';
```suggestion
                const audio = content('a[download]')?.attr('href') ?? '';
                const image = content('meta[itemprop="image"]')?.attr('content').split('/crop/')[0] ?? '';
```

2021-09-08 23:19 UTC, SettingDust approved these changes

2021-09-09 08:58 UTC, NeverBehave approved these changes

2021-11-27 07:49 UTC, DIYgod approved these changes

2021-11-27 07:50 UTC, merged