fix(route): fzu 适配新版教务处网站
DIYgod/RSSHub pull request #8150
Opened 2021-09-06 07:42 UTC by Lao-Liu233

## 该 PR 相关 Issue / Involved issue

无

## 完整路由地址 / Example for the proposed route(s)

```routes
/fzu/jxtz
/fzu/zjjz
```

## 说明 / Note

适配了新版教务处网站。

2021-09-08 04:04 UTC, SettingDust requested changes

2021-09-08 04:04 UTC, SettingDust commented on lib/routes/universities/fzu/news.js
> +    const data = response.data; // 获取页面 html 数据
```suggestion
    const { data } = response; // 获取页面 html 数据
```

2021-09-08 04:04 UTC, SettingDust commented on lib/routes/universities/fzu/news.js
> +    });
用 map 遍历 list

2021-09-08 04:04 UTC, SettingDust commented on lib/routes/universities/fzu/news_min.js
> +                        pubDate: item.find('span').html(),
根据文档正确格式化日期

2021-09-24 06:00 UTC, Lao-Liu233 commented on lib/routes/universities/fzu/news.js
> +    });
感谢🌝没学过 Node 代码写的是真的烂😇

2021-11-27 08:55 UTC, merged