route: 人民网 — 今日头条一览
DIYgod/RSSHub pull request #8154
Opened 2021-09-06 19:52 UTC by yubinbai

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/people/toutiao
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [x] New Route
- [ ] Documentation
  - [x] CN
  - [ ] EN
- [x] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] 日期和时间 date and time
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2021-09-08 04:28 UTC, SettingDust requested changes

2021-09-08 04:28 UTC, SettingDust commented on lib/routes/people/toutiao.js
> +    const browser = await require('@/utils/puppeteer')();
为什么使用 puppteer？原网页没看到任何反制措施

2021-09-08 23:36 UTC, SettingDust requested changes

2021-09-08 23:36 UTC, SettingDust commented on lib/routes/people/toutiao.js
> +const userAgent = 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1';
默认 ua 无法访问？

2021-09-08 23:36 UTC, SettingDust commented on lib/routes/people/toutiao.js
> +            const link = $(this).find('a').attr('href') || $(this).attr('href');
```suggestion
            const link = $(this).find('a').attr('href') ?? $(this).attr('href');
```

2021-09-08 23:36 UTC, SettingDust commented on lib/routes/people/toutiao.js
> +        .slice(0, 20)
无副作用的情况下尽可能多

2021-09-08 23:36 UTC, SettingDust commented on lib/routes/people/toutiao.js
> +            const cache = await ctx.cache.get(itemUrl);
tryGet

2021-09-09 03:01 UTC, yubinbai commented on lib/routes/people/toutiao.js
> +const userAgent = 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1';
right

2021-09-09 03:06 UTC, yubinbai commented on lib/routes/people/toutiao.js
> +        .slice(0, 20)
at most 20 in the box :)

2021-09-09 04:09 UTC, yubinbai commented
got a 403 during test, still need to use puppeteer

 <!doctype html><html><head><meta charset="utf-8"><title>403 Forbidden</title><style>body{ 	padding:0; 	margin:0; 	font-family:"Microsoft YaHei", 	"Microsoft YaHei UI Light";	font-size:14px;}.page{	height: 446px; 	margin: 0 auto;	padding-right:20px;	margin-top:3%;}.page-top{	width：1200px;	margin: 0 auto;	text-align:center;}.page-bottom{    width:1200px;	margin: 0 auto;}.page-bottom-tip{   text-align:center;   color: #7d7d7d;   padding:16px 0 10px 0;   font-size:16px;}.page-bottom-word{   margin-left:30%;   color:#313131}.page-bottom-word p{  font-weight:unset;  line-height: 22px;  margin: 0;}</style></head><body><div class="page">  	<div class="page-top">		<img src="https://blocksrc.haplat.net/_bot_sbu/sbu-pic.gif" />	</div><div class="page-bottom">	  <div class="page-bottom-tip" langFlag='errorTip'></div>	  <div class="page-bottom-word">	   <p><span>URL</span> <span langFlag='colon'></span> <span>http://politics.people.com.cn/n1/2021/0909/c1001-32221825.html</span></p>
       <p><span langFlag='evenID'></span> <span langFlag='colon'></span> <span>1d0e86ab3c16311604984e419f24</span></p>
       <p><span langFlag='clientIP'></span> <span langFlag='colon'></span> <span>163.114.132.5</span></p>
       <p><span langFlag='cuurentTime'></span> <span langFlag='colon'></span> <span id="time_id"></span ></p>
	  </div>
	</div>
</div>
<script type="text/javascript" src="https://blocksrc.haplat.net/_bot_sbu/sbu-jquery-min.js"></script>
<script>
jQuery(document).ready(function($) {
	$("#time_id").html(toLT(1631160498343));
	winHeight = $(window).height();
	$(".page").stop(true,false).animate({"margin-top":winHeight/2-312},0);
	$(window).resize(function(){
        winHeight = $(window).height();
	    $(".page").stop(true,false).animate({"margin-top":winHeight/2-312},0);
	});
	changePageElem();
});

function toLT(date){
    date = new Date(parseInt(date));
    var utc;
	if (judgeLanguage() == 0)
		utc = date.toLocaleString('zh',{timeZoneName: 'short', hour12: false});
    else
		utc = date.toLocaleString('en',{timeZoneName: 'short', hour12: false});
    return utc;
}
function judgeLanguage(){
   var lang = navigator.language || navigator.userLanguage;
   var langFlag ;
   if(lang=="zh-CN"){
       langFlag=0;
   } else{
       langFlag=1;
   }
   return langFlag;
}
function changePageElem(){
	var langObj={
		'colon':['：',':'],
		'evenID':['事件ID','event-id'],
		'clientIP':['客户端ID','client-ip'],
		'cuurentTime':['当前时间','time'],
		'errorTip':['云安全平台检测到您当前的访问行为存在异常，请稍后重试...','Your current behavior is detected as abnormal, Please try again later...']
	}
	var _index=judgeLanguage();
	var pageElements = $("[langFlag]");
	var lblLen = pageElements.length;
	var _elem,_flag;
	for(i = 0; i < lblLen; i++) {
	    _elem = $(pageElements[i]);
		_flag=_elem.attr("langFlag");
		_elem.text(langObj[_flag][_index]);
	};
}

</script>
</body>
</html>

2021-09-09 04:15 UTC, SettingDust commented
403 与无头浏览器一般无关，请先尝试对比 header ，限制抓取数量等措施

2021-09-09 04:24 UTC, SettingDust commented
另有很多历史 commit，先 soft reset 后再 force push 以清理

2021-09-09 04:33 UTC, yubinbai commented
> 另有很多历史 commit，先 soft reset 后再 force push 以清理

haode

> 403 与无头浏览器一般无关，请先尝试对比 header ，限制抓取数量等措施

                headers: {
                    'User-Agent': userAgent,
                    Referer: 'http://www.people.com.cn/'
                },

试了以后还是不行， 有什么其他header field？

2021-09-09 04:34 UTC, SettingDust commented
> > 另有很多历史 commit，先 soft reset 后再 force push 以清理
> 
> haode
> 
> > 403 与无头浏览器一般无关，请先尝试对比 header ，限制抓取数量等措施
> 
> ```
>             headers: {
>                 'User-Agent': userAgent,
>                 Referer: 'http://www.people.com.cn/'
>             },
> ```
> 
> 试了以后还是不行， 有什么其他header field？

**限制抓取数量等措施**

2021-09-09 04:36 UTC, yubinbai commented
<td style="text-align:center;width:660px;overflow:hidden;" class="indexfont13"><div><a href="http://politics.people.com.cn/n1/2021/0909/c1024-32222447.html" target="_blank">习近平就朝鲜国庆73周年向朝鲜最高领导人金正恩致贺电</a> [09月09日10:47]</div><a href="http://politics.people.com.cn/n1/2021/0909/c1001-32221825.html" target="_blank"><img src="/NMediaFile/2021/0909/MAIN202109090516354832430270094.jpg" border="0" width="660" height="40"></a> <center>[09月09日05:16]</center>
</td>


今天只有两篇，我是不是ip 被封了。。

2021-09-09 04:47 UTC, yubinbai commented
看明白了， 需要加一个cookie header，这个有办法生成么？


                  Cookie: 'wdcid=****; sso_c=0; sfr=1; HMF_CI=*******; wdses=********; HMY_JC=******,; wdlast=1631162401',

2021-09-09 04:48 UTC, SettingDust commented
> 看明白了， 需要加一个cookie header，这个有办法生成么？
> 
> ```
>               Cookie: 'wdcid=****; sso_c=0; sfr=1; HMF_CI=*******; wdses=********; HMY_JC=******,; wdlast=1631162401',
> ```

先自行测试可能的方案，这种信息可以作为可配置信息，但是我不认为不需要验证的站点需要 cookie

2021-09-09 15:45 UTC, closed without merging