feat(route): add Asian to lick
DIYgod/RSSHub pull request #8156
Opened 2021-09-06 23:11 UTC by nczitzk

## 该 PR 相关 Issue / Involved issue

Close #8148

## 完整路由地址 / Example for the proposed route(s)

```routes
/asiantolick
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [x] New Route
- [x] Documentation
  - [x] CN
  - [x] EN
- [x] 全文获取 fulltext
  - [x] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] 日期和时间 date and time
  - [x] 可以解析 Parsed
  - [x] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2021-09-08 04:15 UTC, SettingDust requested changes
测试实例跑不了，带一下 xml 截图，阅读器截图，一篇原文

2021-09-08 04:15 UTC, SettingDust commented on lib/routes/asiantolick/index.js
> +    const currentUrl = `${rootUrl}${category === 'category' ? `/category-${keyword}` : ''}${category === 'tag' ? `/tag-${keyword}` : ''}${category === 'search' ? `/search/${keyword}` : ''}`;
做个 map 吧，添加新的太痛苦了

2021-09-08 04:15 UTC, SettingDust commented on lib/routes/asiantolick/index.js
> +    const keyword = ctx.params.keyword || '';
```suggestion
    const category = ctx.params.category ?? '';
    const keyword = ctx.params.keyword ?? '';
```

2021-09-08 04:16 UTC, SettingDust commented
> 测试实例跑不了，带一下 xml 截图，阅读器截图，一篇原文

啊，跑出来了，有点慢，不用了(这是个什么站啊)

2021-11-27 07:46 UTC, merged

2022-05-30 07:13 UTC, zzz6519003 commented on lib/routes/asiantolick/index.js
> +    const currentUrl = `${rootUrl}${category === 'category' ? `/category-${keyword}` : ''}${category === 'tag' ? `/tag-${keyword}` : ''}${category === 'search' ? `/search/${keyword}` : ''}`;
做个 map?

2022-05-31 20:59 UTC, TonyRL commented on lib/routes/asiantolick/index.js
> +    const currentUrl = `${rootUrl}${category === 'category' ? `/category-${keyword}` : ''}${category === 'tag' ? `/tag-${keyword}` : ''}${category === 'search' ? `/search/${keyword}` : ''}`;
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map