feat(route): add TokenInsight
DIYgod/RSSHub pull request #8165
Opened 2021-09-08 23:14 UTC by nczitzk

## 该 PR 相关 Issue / Involved issue

Close #8152

## 完整路由地址 / Example for the proposed route(s)

```routes
/tokeninsight
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [x] New Route
- [x] Documentation
  - [x] CN
  - [x] EN
- [x] 全文获取 fulltext
  - [x] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] 日期和时间 date and time
  - [x] 可以解析 Parsed
  - [x] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2021-09-09 08:03 UTC, SettingDust requested changes

2021-09-09 08:03 UTC, SettingDust commented on lib/routes/tokeninsight/research.js
> +        category: item.tagList ? item.tagList.map((tag) => tag[`mark_${language}`]) : undefined,
```suggestion
        category: item.tagList?.map((tag) => tag[`mark_${language}`])
```

node 14 可以用这个

2021-09-09 08:03 UTC, SettingDust commented on lib/routes/tokeninsight/research.js
> +        link: item.url || `${rootUrl}${language === 'cn' ? '/zh' : ''}/${category === 'news' ? 'blogs' : category}/${item.id}`,
```suggestion
        link: item.url ?? `${rootUrl}${language === 'cn' ? '/zh' : ''}/${category === 'news' ? 'blogs' : category}/${item.id}`,
```

2021-09-09 08:03 UTC, SettingDust commented
另外 pr 正文的测试路由写错了

2021-09-09 13:17 UTC, nczitzk commented on lib/routes/tokeninsight/research.js
> +        category: item.tagList ? item.tagList.map((tag) => tag[`mark_${language}`]) : undefined,
👍

2021-09-23 04:41 UTC, NeverBehave commented
由于 #8236
旧版本的新路由请求将会被关闭，请按照新版路由规范修改后重新开启，谢谢！
需要帮助请在讨论下留言，我们可以协助迁移

2021-09-23 04:41 UTC, closed without merging