fix(route): update url & fix a typo
DIYgod/RSSHub pull request #8185
Opened 2021-09-12 08:50 UTC by kiusiudeng

## 该 PR 相关 Issue / Involved issue

无

## 完整路由地址 / Example for the proposed route(s)

```routes
/njfu/jwc/tzgg
/njfu/jwc/xjfw
/njfu/jwc/sjfw
/njfu/jwc/xzzq
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [x] Documentation
  - [x] CN
  - [ ] EN
- [ ] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] 日期和时间 date and time
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note
更新源URL，修复文档一处笔误。

2021-09-13 02:22 UTC, SettingDust requested changes

2021-09-13 02:22 UTC, SettingDust commented on lib/routes/universities/njfu/jwc.js
>      const category = map.hasOwnProperty(ctx.params.category) ? ctx.params.category : 'tzgg';
```suggestion
    const category = ctx.params.category ?? 'tzgg';
```

2021-09-13 02:22 UTC, SettingDust commented on lib/routes/universities/njfu/jwc.js
> +                        const cook = cookie.map((c) => c.split(';')[0]).join('; ');
这个操作是为什么？

2021-09-13 02:22 UTC, SettingDust commented on lib/routes/universities/njfu/jwc.js
> +        link: url + category + '/',
```suggestion
        link,
```

link 分情况，是 bug

2021-09-13 02:22 UTC, SettingDust commented on lib/routes/universities/njfu/jwc.js
>          description: '南京林业大学教务处-' + map[category] + 'Rss源',
```suggestion
        description: `南京林业大学教务处-${map[category]}`,
```

2021-09-13 02:22 UTC, SettingDust commented on lib/routes/universities/njfu/jwc.js
> +        link = url + category + '/';
```suggestion
        link = `${url}${category}/`
```

2021-09-13 05:11 UTC, kiusiudeng commented on lib/routes/universities/njfu/jwc.js
> +                        const cook = cookie.map((c) => c.split(';')[0]).join('; ');
数据URL必须携带Cookie访问。空Cookie会无限302至生成Cookie的URL。

2021-09-23 04:36 UTC, NeverBehave approved these changes

2021-09-23 04:36 UTC, merged