feat(route): add 8视界
DIYgod/RSSHub pull request #8262
Opened 2021-09-25 12:34 UTC by nczitzk

## 该 PR 相关 Issue / Involved issue

Close #8252

## 完整路由地址 / Example for the proposed route(s)

```routes
/8world
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [x] New Route
- [x] Documentation
  - [x] CN
  - [ ] EN
- [x] 全文获取 fulltext
  - [x] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] 日期和时间 date and time
  - [x] 可以解析 Parsed
  - [x] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2021-09-25 18:49 UTC, TonyRL requested changes

2021-09-25 18:49 UTC, TonyRL commented on lib/v2/8world/radar.js
> +                target: '/:category?',
```suggestion
                target: '/8world/:category?',
```

2021-09-25 23:05 UTC, nczitzk commented on lib/v2/8world/radar.js
> +                target: '/:category?',
thank you for your review ❤️

2021-09-26 02:13 UTC, NeverBehave approved these changes

2021-09-26 02:13 UTC, merged

2021-09-30 06:41 UTC, wft44maqb commented
`Error message: wrong path` @nczitzk @NeverBehave