feat(timednews router): 新增时刻新闻
DIYgod/RSSHub pull request #8279
Opened 2021-09-27 07:14 UTC by linbuxiao

## 该 PR 相关 Issue / Involved issue

Close #8271

## 完整路由地址 / Example for the proposed route(s)

```routes
/timednews/news
/timednews/news/all
/timednews/news/currentAffairs
/timednews/news/finance
/timednews/news/technology
/timednews/news/social
/timednews/news/sports
/timednews/news/international
/timednews/news/usa
/timednews/news/cn
/timednews/news/europe
/timednews/news/comments
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [x] New Route
- [x] Documentation
  - [x] CN
  - [ ] EN
- [x] 全文获取 fulltext
  - [x] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] 日期和时间 date and time
  - [x] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note
时刻新闻 - 新闻
支持子分类

2021-09-27 08:28 UTC, TonyRL requested changes

2021-09-27 08:28 UTC, TonyRL commented on lib/v2/timednews/radar.js
> +                    return `/news/${name}`;
```suggestion
                    return `/timednews/news/${name}`;
```

2021-09-27 08:32 UTC, linbuxiao commented on lib/v2/timednews/radar.js
> +                    return `/news/${name}`;
I forgot about it again. Thanks!

2021-11-27 07:54 UTC, DIYgod approved these changes

2021-11-27 07:54 UTC, merged