add: x漫画网站(https://xmanhua.com)，指定漫画更新提醒
DIYgod/RSSHub pull request #8450
Opened 2021-10-25 07:42 UTC by Yemaoxin

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/xmanhua/73xm
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [x] New Route
- [x] Documentation
  - [x] CN
  - [ ] EN
- [ ] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] 日期和时间 date and time
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2021-11-27 08:48 UTC, DIYgod requested changes

2021-11-27 08:48 UTC, DIYgod commented on docs/xmanhua.md
> +---
Please use right docs file

2021-12-04 03:02 UTC, Yemaoxin commented
I has deleted the wrong md file, and add the content to docs/anime.md

2021-12-04 03:05 UTC, SukkaW commented on lib/routes/xmanhua/index.js
> +    };
```suggestion
    const description = finished ? '已完结' : '连载中';

    ctx.state.data = {
        title: `x漫画  ${name}`,
        link: `https://xmanhua.com/${uid}`,
        description,
        allowEmpty: true,
        item: items,
    };
```

2021-12-04 03:06 UTC, SukkaW commented on lib/routes/xmanhua/index.js
> +    if (newOneDate.search('月') !== -1 && newOneDate.search('號') !== -1) {
```suggestion
    if (newOneDate.includes('月') && newOneDate.includes('號')) {
```

2021-12-04 03:07 UTC, SukkaW commented on lib/routes/xmanhua/index.js
> +    });
```suggestion
    const url = `https://xmanhua.com/${uid}/`;
    const response = await got({
        method: 'get',
        url,
        headers: {
            Referer: host,
        },
    });
```

2021-12-04 03:07 UTC, SukkaW commented on lib/routes/xmanhua/index.js
> +    if (finished_text.search('已完結') !== -1 || finished_text.search('已完结') !== -1) {
```suggestion
    if (finished_text.includes('已完結') || finished_text.includes('已完结')) {
```

2021-12-04 03:10 UTC, Yemaoxin commented
I has accepted your suggestions and updated the codes

2022-02-01 19:26 UTC, TonyRL requested changes
Please use v2 script standard https://github.com/DIYgod/RSSHub/discussions/8236

Please use parseDate() from `@/utils/parse-date` for date handling
https://docs.rsshub.app/joinus/pub-date.html

2022-02-26 14:38 UTC, TonyRL commented
Migrated to v2
Removed pubDate for items that have no date. See: https://docs.rsshub.app/joinus/pub-date.html#mei-you-ri-qi

2022-02-26 14:38 UTC, merged