fix(route): MM范
DIYgod/RSSHub pull request #8701
Opened 2021-12-09 05:46 UTC by nczitzk

## 该 PR 相关 Issue / Involved issue

Close #8689

## 完整路由地址 / Example for the proposed route(s)

```routes
/95mm/category/1
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [ ] Documentation
  - [x] CN
  - [ ] EN
- [x] 全文获取 fulltext
  - [x] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] 日期和时间 date and time
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2022-01-22 18:48 UTC, DIYgod requested changes

2022-01-22 18:48 UTC, DIYgod commented on lib/v2/95mm/radar.js
> +    '': {
pointless contents

2022-02-02 11:56 UTC, TonyRL requested changes

2022-02-02 11:56 UTC, TonyRL commented on lib/v2/95mm/utils.js
> +                    item.description = `<img src="${images.map((i) => i.split("'")[1]).join('"><img src="')}">`;
Please use art-template for HTML https://github.com/DIYgod/RSSHub/discussions/8359

2022-02-26 15:56 UTC, merged