Modefy to get all content and change to V2
DIYgod/RSSHub pull request #8724
Opened 2021-12-15 09:37 UTC by Fatpandac

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/cqwu/news/notify
/cqwu/news/academiceve
/cqwu/news
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [X] Documentation
  - [X] CN
  - [ ] EN
- [X] 全文获取 fulltext
  - [X] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] 日期和时间 date and time
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2021-12-21 19:34 UTC, TonyRL requested changes

2021-12-21 19:34 UTC, TonyRL commented on lib/v2/cqwu/index.js
> +    const type = ctx.params.type || 'academiceve';
```suggestion
    const type = ctx.params.type ?? 'academiceve';
```

2021-12-21 19:35 UTC, TonyRL requested changes

2021-12-21 19:35 UTC, TonyRL commented on lib/v2/cqwu/index.js
> +    const type = ctx.params.type || 'academiceve';
```suggestion
    const type = ctx.params.type ?? 'academiceve';
```

2021-12-21 19:35 UTC, TonyRL commented on lib/v2/cqwu/maintainer.js
> +    '/cqwu/news/:type?': ['Fatpandac'],
```suggestion
    '/news/:type?': ['Fatpandac'],
```

2021-12-21 19:58 UTC, Fatpandac commented on lib/v2/cqwu/index.js
> +    const type = ctx.params.type || 'academiceve';
Thanks

2021-12-21 19:59 UTC, Fatpandac commented on lib/v2/cqwu/maintainer.js
> +    '/cqwu/news/:type?': ['Fatpandac'],
Thank you

2021-12-24 19:33 UTC, TonyRL requested changes

2021-12-24 19:33 UTC, TonyRL commented on lib/v2/cqwu/index.js
> +                pubDate: new Date($(item).find('span').text()).toUTCString(),
Please use `parseDate()`

2022-01-22 19:18 UTC, merged