Add 中国科学院大学
DIYgod/RSSHub pull request #8733
Opened 2021-12-18 14:07 UTC by Fatpandac

## 该 PR 相关 Issue / Involved issue

Close #8427

## 完整路由地址 / Example for the proposed route(s)

```routes
/ucas/job/jxkyrc
/ucas/job/glzcrc
/ucas/job/ktxmpy
/ucas/job/bsh
/ucas/job
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [X] New Route
- [X] Documentation
  - [X] CN
  - [ ] EN
- [X] 全文获取 fulltext
  - [X] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] 日期和时间 date and time
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2021-12-21 19:39 UTC, TonyRL requested changes

2021-12-21 19:39 UTC, TonyRL commented on lib/v2/ucas/index.js
> +    const type = ctx.params.type || 'bsh';
```suggestion
    const type = ctx.params.type ?? 'bsh';
```

2021-12-21 19:56 UTC, Fatpandac commented on lib/v2/ucas/index.js
> +    const type = ctx.params.type || 'bsh';
Thanks

2021-12-24 19:32 UTC, TonyRL requested changes

2021-12-24 19:32 UTC, TonyRL commented on lib/v2/ucas/index.js
> +            const pubDate = new Date($(item).find('span').text()).toUTCString();
Please use `parseDate()`

2022-01-22 19:19 UTC, merged