Add leetcode.com contest list
DIYgod/RSSHub pull request #8792
Opened 2021-12-30 08:17 UTC by a180285

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/leetcode-com/contest
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [x] New Route
- [x] Documentation
  - [x] CN
  - [ ] EN
- [ ] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] 日期和时间 date and time
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note
使用了 leetcode-com 与方便后期与 leetcode.cn 进行区分

2021-12-30 14:06 UTC, TonyRL requested changes
I would suggest using the namespace of `leetcode` instead of `leetcode-com`.

2021-12-30 14:06 UTC, TonyRL commented on lib/v2/leetcode-com/contest.js
> +        const duration = contest.duration / 3600.0;
I think you can also use day.js to achieve which is already available in current package.json

2021-12-30 14:06 UTC, TonyRL commented on lib/v2/leetcode-com/contest.js
> +            description: `北京时间： ${beijingTime} ，时长： ${duration} 小时<br>` + contest.description,
Please use art template engine.
See https://github.com/DIYgod/RSSHub/discussions/8359
Docs: https://docs.rsshub.app/joinus/script-standard.html#template

2021-12-30 14:06 UTC, TonyRL commented on docs/programming.md
> +## leetcode.com
There's already a H2 header of LeetCode few lines above.

Please also add english docs.

2021-12-31 01:47 UTC, a180285 commented
Waiting for #8787

2021-12-31 01:47 UTC, closed without merging