feat: add 华东理工继续教育学院新闻公告;
DIYgod/RSSHub pull request #8843
Opened 2022-01-07 14:15 UTC by jialinghui

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/news
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [x] New Route
- [ ] Documentation
  - [x] CN
  - [ ] EN
- [x] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] 日期和时间 date and time
  - [x] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2022-01-07 15:43 UTC, TonyRL requested changes

2022-01-07 15:43 UTC, TonyRL commented on docs/university.md
> +<Route author="jialinghui" example="/news" path="/news" />
```suggestion
<Route author="jialinghui" example="/ecust-jxjy/news" path="/ecust-jxjy/news" />
```

2022-01-07 15:43 UTC, TonyRL commented on lib/v2/ecust-jxjy/news.js
> +                pubDate: new Date(date(item.find('dd').text())),
Please use `parseDate()`.
Docs: https://docs.rsshub.app/joinus/pub-date.html

2022-01-07 15:43 UTC, TonyRL commented on lib/v2/ecust-jxjy/radar.js
> +                target: '/news',
```suggestion
                target: '/ecust-jxjy/news',
```

2022-01-07 15:47 UTC, TonyRL commented
I would suggest using the route `/ecust/jxjy/news` instead of `/ecust-jxjy/news` for better route management.

2022-01-11 08:20 UTC, jialinghui commented
> I would suggest using the route `/ecust/jxjy/news` instead of `/ecust-jxjy/news` for better route management.

Thanks for the suggestion, but I think `/ecust-jxjy/news` is appropriate

2022-01-22 20:30 UTC, merged