Add(route): add 深圳市委组织部 & 深圳考试院
DIYgod/RSSHub pull request #8851
Opened 2022-01-09 09:55 UTC by zlasd

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/gov/shenzhen/zzb/tzgg
/gov/shenzhen/zzb/gzdt
/gov/shenzhen/zzb/zcfg
/gov/shenzhen/hrss/szksy/tzgg
/gov/shenzhen/hrss/szksy/bmxx
/gov/shenzhen/hrss/szksy/cjxx
/gov/shenzhen/hrss/szksy/hgbz
/gov/shenzhen/hrss/szksy/hgrygs
/gov/shenzhen/hrss/szksy/zsff
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [x] New Route
- [x] Documentation
  - [x] CN
  - [ ] EN
- [ ] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] 日期和时间 date and time
  - [x] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2022-01-09 12:50 UTC, TonyRL requested changes
Please use v2 script standard https://github.com/DIYgod/RSSHub/discussions/8236

2022-01-09 12:50 UTC, TonyRL commented on lib/routes/gov/shenzhen/hrss/szksy.js
> +    const page = ctx.params.page || '1';
```suggestion
    const page = ctx.params.page ?? '1';
```

2022-01-09 12:50 UTC, TonyRL commented on lib/routes/gov/shenzhen/zzb/zzb.js
> +    const page = ctx.params.page || '1';
```suggestion
    const page = ctx.params.page ?? '1';
```

2022-01-09 12:50 UTC, TonyRL commented on lib/routes/gov/shenzhen/hrss/szksy.js
> +                pubDate: new Date(tag2.text().trim()).toUTCString(),
Please use `parseDate()`
docs: https://docs.rsshub.app/joinus/pub-date.html

2022-01-09 12:50 UTC, TonyRL commented on lib/routes/gov/shenzhen/zzb/zzb.js
> +                pubDate: new Date(tag2.text().trim()).toUTCString(),
Please use `parseDate()`
docs: https://docs.rsshub.app/joinus/pub-date.html

2022-01-10 15:40 UTC, zlasd commented
> Please use v2 script standard #8236

thanks for reviewing, now the router rule is up-to-date

2022-01-10 16:17 UTC, TonyRL requested changes

2022-01-10 16:17 UTC, TonyRL commented on docs/government.md
> +
Please put it in this section

https://github.com/DIYgod/RSSHub/blob/b36b326742e18f1f1506c3a7c59c565dfb6f1b82/docs/government.md#L61-L91

2022-01-10 16:21 UTC, TonyRL commented
I think you can also keep your previous route structures 
```
/gov/shenzhen/zzb/tzgg
/gov/shenzhen/hrss/szksy/tzgg
```

2022-01-11 08:42 UTC, zlasd commented
> I think you can also keep your previous route structures
> 
> ```
> /gov/shenzhen/zzb/tzgg
> /gov/shenzhen/hrss/szksy/tzgg
> ```

I will change it back later. In the beginning, I'm afraid that it would conflict with v1 router rule.

2022-01-11 14:01 UTC, zlasd commented
> I will change it back later. In the beginning, I'm afraid that it would conflict with v1 router rule.

done

2022-01-11 15:10 UTC, TonyRL approved these changes

2022-01-22 19:55 UTC, merged