Add(route): add 链新闻abmedia
DIYgod/RSSHub pull request #8862
Opened 2022-01-11 13:27 UTC by Fatpandac

## 该 PR 相关 Issue / Involved issue

Close #8861

## 完整路由地址 / Example for the proposed route(s)

```routes
/abmida/technology-development
/abmida/business-application
/abmida/regulation
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [X] New Route
- [X] Documentation
  - [X] CN
  - [ ] EN
- [X] 全文获取 fulltext
  - [X] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [X] 日期和时间 date and time
  - [X] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2022-01-11 15:15 UTC, TonyRL requested changes

2022-01-11 15:15 UTC, TonyRL commented on lib/v2/abmedia/index.js
> +    }));
Please add cache.
docs: https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun

2022-01-22 19:51 UTC, DIYgod requested changes

2022-01-22 19:51 UTC, DIYgod commented on lib/v2/abmedia/index.js
> +            ctx.cache.tryGet(item.link, () => ({
No cache needed

2022-01-23 00:13 UTC, Fatpandac commented on lib/v2/abmedia/index.js
> +            ctx.cache.tryGet(item.link, () => ({
OK

2022-01-23 14:42 UTC, merged