Add(route): add informs
DIYgod/RSSHub pull request #8873
Opened 2022-01-13 05:43 UTC by Fatpandac

## 该 PR 相关 Issue / Involved issue

Close #8868
Close #8869

## 完整路由地址 / Example for the proposed route(s)

```routes
/informs/mnsc
/informs/orsc
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [X] New Route
- [X] Documentation
  - [X] CN
  - [X] EN
- [X] 全文获取 fulltext
  - [X] Use Cache
- [X] 反爬/频率限制 anti-bot or rate limit?
  - [X] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [X] 日期和时间 date and time
  - [X] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2022-01-13 06:22 UTC, TonyRL requested changes

2022-01-13 06:22 UTC, TonyRL commented on docs/en/new-media.md
> +
Please put it in journal.md

2022-01-13 06:22 UTC, TonyRL commented on docs/new-media.md
> +
Please put it in journal.md

2022-01-13 06:38 UTC, Fatpandac commented on docs/en/new-media.md
> +
OK

2022-01-13 06:38 UTC, Fatpandac commented on docs/new-media.md
> +
OK

2022-01-13 11:03 UTC, fredericky123 commented
感谢！
不过在Inoreader中的显示是不是有些不够清晰，abstract那里是不是可以优化一下？再次谢谢！
![image](https://user-images.githubusercontent.com/13982749/149318642-6a6993c4-26f0-4d32-b4ca-52e9923bdfd7.png)

2022-01-13 11:08 UTC, Fatpandac commented
> 感谢！
> 
> 不过在Inoreader中的显示是不是有些不够清晰，abstract那里是不是可以优化一下？再次谢谢！
> 
> ![image](https://user-images.githubusercontent.com/13982749/149318642-6a6993c4-26f0-4d32-b4ca-52e9923bdfd7.png)
> 
> 

我待会儿看看

2022-01-13 11:12 UTC, fredericky123 commented
> > 感谢！
> > 不过在Inoreader中的显示是不是有些不够清晰，abstract那里是不是可以优化一下？再次谢谢！
> > ![image](https://user-images.githubusercontent.com/13982749/149318642-6a6993c4-26f0-4d32-b4ca-52e9923bdfd7.png)
> 
> 我待会儿看看

提前感谢！

2022-01-13 14:46 UTC, Fatpandac commented
@fredericky123 这个似乎是 Inoreader 显示的问题，他会把内容的所有文字不按格式显示出来。
或则你有相关的例子麻烦提供给我参考一下

2022-01-13 15:11 UTC, fredericky123 commented
> @fredericky123 这个似乎是 Inoreader 显示的问题，他会把内容的所有文字不按格式显示出来。 或则你有相关的例子麻烦提供给我参考一下

相关的例子 我还真不好找唉 这样也能将就看 要不只解决 Abstract后面没有空格的那个问题呢？ 在Abstract后直接加个空格就行

2022-01-13 17:08 UTC, Fatpandac commented
> > @fredericky123 这个似乎是 Inoreader 显示的问题，他会把内容的所有文字不按格式显示出来。 或则你有相关的例子麻烦提供给我参考一下
> 
> 相关的例子 我还真不好找唉 这样也能将就看 要不只解决 Abstract后面没有空格的那个问题呢？ 在Abstract后直接加个空格就行

Done

2022-01-13 17:10 UTC, fredericky123 commented
> https://rsshub-ggqw4b3an-diy.vercel.app/informs/mnsc

感谢！

2022-01-13 17:13 UTC, Fatpandac commented
> > https://rsshub-ggqw4b3an-diy.vercel.app/informs/mnsc
> 
> 感谢！

甭客气

2022-01-22 20:26 UTC, merged

2022-02-15 09:56 UTC, fredericky123 commented
![image](https://user-images.githubusercontent.com/13982749/154037895-eab93aad-f31e-48ee-9e34-9978c948b9cb.png)

这里的显示有些问题，会出现代码

2022-02-15 10:30 UTC, Fatpandac commented
> ![image](https://user-images.githubusercontent.com/13982749/154037895-eab93aad-f31e-48ee-9e34-9978c948b9cb.png)
> 
> 这里的显示有些问题，会出现代码

收到，我提交新 PR 修复

2022-02-15 11:31 UTC, fredericky123 commented
> 收到，我提交新 PR 修复

感谢！