中国工业和信息化部
DIYgod/RSSHub pull request #8898
Opened 2022-01-18 15:47 UTC by chancenju

## 该 PR 相关 Issue / Involved issue

Close #8351 

## 完整路由地址 / Example for the proposed route(s)

```routes
/gov/miit/wjgs
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [ ] Documentation
  - [ ] CN
  - [ ] EN
- [ ] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] 日期和时间 date and time
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note
已更新

2022-01-18 15:53 UTC, chancenju commented
新手请指教!

2022-01-18 22:25 UTC, chancenju commented
救救我把，第一次接触nodejs。16小时过去了，熬不住了。

2022-01-22 12:11 UTC, DIYgod commented
How to get the cookie? Is it possible to get it automatically? Or can you add a document for it?

2022-01-22 12:11 UTC, DIYgod requested changes

2022-02-16 03:01 UTC, chancenju commented on lib/config.js
> +            cookie: envs.miit_cookie,
when you first visit the websites. Sorry, I am not an expert on it. I tried and tried, but cannot get the source.

2022-03-05 15:23 UTC, TonyRL commented on lib/config.js
> +            cookie: envs.miit_cookie,
See #9221

2022-06-08 13:57 UTC, TonyRL commented
This route does not require any cookies.

2022-06-08 13:57 UTC, merged