fix(route): JAVLibrary
DIYgod/RSSHub pull request #8956
Opened 2022-01-29 06:07 UTC by nczitzk

## 该 PR 相关 Issue / Involved issue

Close #8936

## 完整路由地址 / Example for the proposed route(s)

```routes
/javlibrary/update/cn
/javlibrary/newrelease/cn
/javlibrary/newentries/cn
/javlibrary/mostwanted/cn
/javlibrary/bestrated/cn
/javlibrary/genre/amjq/cn
/javlibrary/star/abbds/cn
/javlibrary/bestreviews/cn
/javlibrary/userposts/mangudai/cn
/javlibrary/userwanted/mangudai/cn
/javlibrary/userwatched/mangudai/cn
/javlibrary/userowned/mangudai/cn
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [x] New Route
- [x] Documentation
  - [x] CN
  - [x] EN
- [x] 全文获取 fulltext
  - [x] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] 日期和时间 date and time
  - [x] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2022-01-29 16:22 UTC, TonyRL commented
Can you make it backwards compatible with current routes?
```
/javlibrary/videos/:vtype
/javlibrary/stars/:sid
/javlibrary/users/:uid/:utype
/javlibrary/bestreviews
```

2022-01-29 18:24 UTC, nczitzk commented
> Can you make it backwards compatible with current routes?
> 
> ```
> /javlibrary/videos/:vtype
> /javlibrary/stars/:sid
> /javlibrary/users/:uid/:utype
> /javlibrary/bestreviews
> ```

Already done 😃

2022-02-02 15:50 UTC, TonyRL requested changes

2022-02-02 15:50 UTC, TonyRL commented on lib/v2/javlibrary/router.js
> +};
Please sort the routes in alphabetical order for both old routes and new routes in two sections.

2022-02-02 15:50 UTC, TonyRL commented on lib/v2/javlibrary/maintainer.js
> +};
Please sort the routes in alphabetical order.

2022-02-08 09:45 UTC, merged