[WIP] feat: /spotify/*
DIYgod/RSSHub pull request #8966
Opened 2022-01-31 09:42 UTC by outloudvi

## 该 PR 相关 Issue / Involved issue

目前实现了 #6601 提到的后两项。

## 完整路由地址 / Example for the proposed route(s)

```routes
/spotify/playlist/4UBVy1LttvodwivPUuwJk2
/spotify/artist/31zCA3lKnObwtGBbDNnNAt
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [x] New Route
- [ ] Documentation
  - [ ] CN
  - [ ] EN
- [ ] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] 日期和时间 date and time
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

* Spotify 的 API 需要 token，因此 GHA 的测试应该会失败。生成这些 token 需要 clientId/clientSecret，但不一定需要用户登录。
* Spotify 专辑的 `release_date` 只能精确至日、月或年。 [src](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-track)
* 对于与用户相关的端点，可能需要让用户填入 `refresh_token` 来获取。其它端点只需要 clientId/clientSecret。 [src](https://developer.spotify.com/documentation/general/guides/authorization/code-flow/)
* [Spotify Developer Terms](https://developer.spotify.com/terms/).

2022-02-03 14:08 UTC, TonyRL requested changes
Please provide screenshots of the xmls and feed content in RSS reader(that you preferred)

2022-02-03 14:08 UTC, TonyRL commented on docs/install/README.md
> +
Please also update `docs/en/install/README.md`

2022-02-03 14:45 UTC, outloudvi commented
I've deployed <https://rsshub-8966.vercel.app/> with valid configurations, so please feel free to check:

* https://rsshub-8966.vercel.app/spotify/playlist/4UBVy1LttvodwivPUuwJk2
* https://rsshub-8966.vercel.app/spotify/artist/31zCA3lKnObwtGBbDNnNAt
* https://rsshub-8966.vercel.app/spotify/saved/25

Note that since the corresponding Spotify account is new and only for testing, Spotify hasn't curated Top Tracks and Top Artists for it. They may need several days or so to generate some contents:

* https://rsshub-8966.vercel.app/spotify/top/tracks
* https://rsshub-8966.vercel.app/spotify/top/artists

2022-02-04 08:44 UTC, outloudvi commented
All the links on my test RSSHub instance are curated for now. Please feel free to check it out.

2022-02-04 10:46 UTC, merged