Add(route): add hacker news user follow
DIYgod/RSSHub pull request #8976
Opened 2022-02-02 02:51 UTC by xie-dongping

## 该 PR 相关 Issue / Involved issue

## 完整路由地址 / Example for the proposed route(s)

```routes
/hackernews/new_comments/comments_list/
/hackernews/threads/comments_list/dang
/hackernews/submitted/source/dang
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ x ] New Route
- [ ] Documentation
  - [ x ] CN
  - [ x ] EN
- [ ] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ x ] 日期和时间 date and time
  - [ x ] 可以解析 Parsed
  - [ x ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

Add route to subscribe to a certain user in hacker news.

2022-02-02 02:55 UTC, xie-dongping commented
> Successfully generated as following:
> https://rsshub-qo1005cff-diy.vercel.app/hackernews/new_comments/comments_list/ - **Failed**
> https://rsshub-qo1005cff-diy.vercel.app/hackernews/threads/comments_list/dang - Success
> https://rsshub-qo1005cff-diy.vercel.app/hackernews/submitted/source/dang - Success

The route test failed because of a typo, there shouldn't be any underscore in the `newcomments` section.

2022-02-02 16:27 UTC, TonyRL requested changes

2022-02-02 16:27 UTC, TonyRL commented on docs/en/programming.md
> +<RouteEn author="cf020031308 nczitzk xie-dongping" example="/hackernews/threads/comments_list/dang" path="/hackernews/:section?/:type?/:user?" :paramsDesc="['Section, see below, index by default', 'L
```suggestion
<RouteEn author="cf020031308 nczitzk xie-dongping" example="/hackernews/threads/comments_list/dang" path="/hackernews/:section?/:type?/:user?" :paramsDesc="['Section, see above, `index` by default', 'Link, see above, `sources` by default', 'User, only valid for section `threads` and `submitted`']" />
```
Please close your Route tag

2022-02-02 16:27 UTC, TonyRL commented on docs/programming.md
> +<Route author="cf020031308 nczitzk xie-dongping" example="/hackernews/threads/comments_list/dang" path="/hackernews/:section?/:type?/:user?" :paramsDesc="['内容分区，见下表，默认为 index', '链接类型，见下表，默认为 sources'
```suggestion
<Route author="cf020031308 nczitzk xie-dongping" example="/hackernews/threads/comments_list/dang" path="/hackernews/:section?/:type?/:user?" :paramsDesc="['内容分区，见上表，默认为 `index`', '链接类型，见上表，默认为 `sources`', '设定用户，只在 `threads` 和 `submitted` 分区有效']" />
```

2022-02-02 16:27 UTC, TonyRL commented on docs/programming.md
> +<Route author="cf020031308 nczitzk" example="/hackernews" path="/hackernews/:section?/:type?/:user?" :paramsDesc="['内容分区，见下表，默认为 index', '链接类型，见下表，默认为 sources', '设定用户，只在threads和submitted分区有效']">
```suggestion
<Route author="cf020031308 nczitzk" example="/hackernews" path="/hackernews/:section?/:type?/:user?" :paramsDesc="['内容分区，见下表，默认为 `index`', '链接类型，见下表，默认为 `sources`', '设定用户，只在 `threads` 和 `submitted` 分区有效']">
```
Please add `threads` and `submitted` into the Section table

2022-02-02 16:27 UTC, TonyRL commented on docs/en/programming.md
> +<RouteEn author="cf020031308 nczitzk" example="/hackernews" path="/hackernews/:section?/:type?/:user?" :paramsDesc="['Section, see below, index by default', 'Link, see below, sources by default', 'Us
```suggestion
<RouteEn author="cf020031308 nczitzk" example="/hackernews" path="/hackernews/:section?/:type?/:user?" :paramsDesc="['Section, see below, `index` by default', 'Link, see below, `sources` by default', 'User, only valid for section `threads` and `submitted`']">
```

Please add `threads` and `submitted` into the Section table

2022-02-02 17:42 UTC, xie-dongping commented
@TonyRL , thanks for the review and the suggested changes. I updated the table according to your suggestion. PTAL

I would like to rebase and squash the PR to one commit, but I'm not sure if it is the normal case so I didn't do so.

2022-02-03 12:56 UTC, TonyRL requested changes

2022-02-03 12:56 UTC, TonyRL commented on lib/v2/hackernews/maintainer.js
> +    '/:section?/:type?/:user?': ['nczitzk'],
```suggestion
    '/:section?/:type?/:user?': ['nczitzk', 'xie-dongping'],
```
Please also put your name in it.

2022-02-03 13:00 UTC, xie-dongping commented on lib/v2/hackernews/maintainer.js
> +    '/:section?/:type?/:user?': ['nczitzk'],
Done

2022-02-03 13:02 UTC, xie-dongping commented
Added myself as maintainer and also rebased/squashed to one commit.

2022-02-03 13:30 UTC, merged