优化：蓝桥云课新增课程排序规则并修复多个错误
DIYgod/RSSHub pull request #8986
Opened 2022-02-03 14:16 UTC by huhuhang

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/lanqiao/courses/latest/all
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [ ] Documentation
  - [ ] CN
  - [ ] EN
- [ ] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] 日期和时间 date and time
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2022-02-03 15:16 UTC, TonyRL requested changes

2022-02-03 15:16 UTC, TonyRL commented on docs/programming.md
> +<Route author="huhuhang" example="/lanqiao/courses/latest/all" path="/lanqiao/courses/:sort/:tag"  :paramsDesc="['排序规则 sort, 默认(default)、最新(latest)、最热(hotest)', '课程标签 tag，可在该页面找到：https://www.lanqiao.
```suggestion
<Route author="huhuhang" example="/lanqiao/courses/latest/all" path="/lanqiao/courses/:sort/:tag"  :paramsDesc="['排序规则 sort, 默认(`default`)、最新(`latest`)、最热(`hotest`)', '课程标签 tag，可在该页面找到：https://www.lanqiao.cn/courses/']" radar="1" rssbud="1"/>
```

2022-02-03 15:16 UTC, TonyRL commented on lib/v2/lanqiao/courses.js
> +                item.pubDate = dateParser(new Date().toISOString());
Please use parseDate() from `@utils/parse-date`
docs: https://docs.rsshub.app/joinus/pub-date.html#shi-yong-gong-ju-lei

2022-02-05 05:31 UTC, huhuhang commented on lib/v2/lanqiao/courses.js
> +                item.pubDate = dateParser(new Date().toISOString());
数据源无日期，已经移除 `pubDate` 字段。

2022-02-05 10:27 UTC, merged