Feat(route): add wallhaven
DIYgod/RSSHub pull request #9021
Opened 2022-02-08 07:46 UTC by Fatpandac

## 该 PR 相关 Issue / Involved issue

Close #9020

## 完整路由地址 / Example for the proposed route(s)

```routes
/wallhaven/latest
/wallhaven/hot
/wallhaven/toplist
/wallhaven/random
/wallhaven/search/categories=110&purity=100&sorting=hot&order=desc
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [X] New Route
- [X] Documentation
  - [X] CN
  - [X] EN
- [ ] 全文获取 fulltext
  - [ ] Use Cache
- [X] 反爬/频率限制 anti-bot or rate limit?
  - [X] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] 日期和时间 date and time
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2022-02-08 07:50 UTC, nczitzk commented
哈哈撞上啦 😂

2022-02-08 07:53 UTC, Fatpandac commented
> 哈哈撞上啦 😂

😂两天都撞上了
要不以后要处理的话就留个备注？

2022-02-08 07:56 UTC, nczitzk commented
> > 哈哈撞上啦 😂
> 
> 😂两天都撞上了 要不以后要处理的话就留个备注？

好呀，以后在 issue 那边备注一下 😊

2022-02-08 08:04 UTC, nczitzk commented
我把 #9022 关了，要不要考虑一下把两个 Pull requests 的代码和文档整合一下呢

2022-02-08 08:06 UTC, Fatpandac commented
> 我把 #9022 关了，要不要考虑一下把两个 Pull requests 的代码和文档整合一下呢

可以

2022-02-08 08:14 UTC, nczitzk commented on docs/en/picture.md
> +<RouteEn author="Fatpandac" example="/wallhaven/search/categories=110&purity=100&sorting=date_added&order=desc&page=2" path="/wallhaven/search/:params" :paramsDesc="['params of search, you can get it
加入 `page=2` 会获取到第 2 页

2022-02-08 08:14 UTC, nczitzk commented on docs/picture.md
> +<Route author="Fatpandac" example="/wallhaven/search/categories=110&purity=100&sorting=date_added&order=desc&page=2" path="/wallhaven/search/:params" :paramsDesc="['用于搜索的参数。可在原网站搜索后复制`https://wallhav
加入 `page=2` 会获取到第 2 页

2022-02-08 08:14 UTC, nczitzk commented on lib/v2/wallhaven/index.js
> +            description: $(item)
可以将 `src` 修改为该图片高清原图的地址，而非缩略图 😊

2022-02-08 08:14 UTC, nczitzk commented on lib/v2/wallhaven/search.js
> +            description: $(item)
可以将 `src` 修改为该图片高清原图的地址，而非缩略图 😊

2022-02-08 08:14 UTC, nczitzk commented on lib/v2/wallhaven/search.js
> +        title: `Wallhaven - search`,
可以直接使用目标网页标题展示用户搜索的关键字

2022-02-08 08:15 UTC, nczitzk commented
> 可以，我来整合吧

辛苦啦

2022-02-08 08:22 UTC, Fatpandac commented on lib/v2/wallhaven/index.js
> +            description: $(item)
如果不要详细信息的情况下，只拿缩略图会好些吧

2022-02-08 08:22 UTC, Fatpandac commented on docs/picture.md
> +<Route author="Fatpandac" example="/wallhaven/search/categories=110&purity=100&sorting=date_added&order=desc&page=2" path="/wallhaven/search/:params" :paramsDesc="['用于搜索的参数。可在原网站搜索后复制`https://wallhav
是的，不加默认拿到第一页

2022-02-08 08:31 UTC, nczitzk commented on lib/v2/wallhaven/index.js
> +            description: $(item)
> 如果不要详细信息的情况下，只拿缩略图会好些吧

也可以

2022-02-08 09:48 UTC, nczitzk commented
LGTM. Good job 😄

2022-02-08 10:08 UTC, Fatpandac commented
> 

Thx.

2022-02-08 11:09 UTC, TonyRL requested changes

2022-02-08 11:09 UTC, TonyRL commented on docs/en/picture.md
> +<RouteEn author="nczitzk Fatpandac" example="/wallhaven/search/categories=110&purity=110&sorting=date_added&order=desc" path="/wallhaven/search/:filter?/:needDetails?" :paramsDesc="['Filter, empty by
```suggestion
<RouteEn author="nczitzk Fatpandac" example="/wallhaven/search/categories=110&purity=110&sorting=date_added&order=desc" path="/wallhaven/search/:filter?/:needDetails?" :paramsDesc="['Filter, empty by default', 'Need Details, `true`/`yes` as yes, no by default']">
```

2022-02-08 11:09 UTC, TonyRL commented on docs/picture.md
> +<Route author="nczitzk Fatpandac" example="/wallhaven/search/q=id%3A711&sorting=random&ref=fp&seed=8g0dgd" path="/wallhaven/search/:filter?/:needDetails?" :paramsDesc="['过滤器，默认为空', '需要图片信息，填写 true/ye
```suggestion
<Route author="nczitzk Fatpandac" example="/wallhaven/search/q=id%3A711&sorting=random&ref=fp&seed=8g0dgd" path="/wallhaven/search/:filter?/:needDetails?" :paramsDesc="['过滤器，默认为空', '需要图片信息，填写 `true`/`yes` 表示需要，默认不需要']">
```

2022-02-08 12:21 UTC, merged

2022-02-10 02:51 UTC, Clackz commented
目前来说，rss获取到的是小图，是否能获取大图呢？

2022-02-10 03:55 UTC, Fatpandac commented
> 

![image](https://user-images.githubusercontent.com/30423976/153333949-b2b11e82-5856-45e7-9caf-26dd961f37f9.png)
获取图片详细信息拿到的是大图，
我的想法是如果只需要获取省略信息的话用小图会好些，毕竟加载时间不会很长。

如果你确实需要大图，我可以进行相应的修改。

2022-02-10 05:32 UTC, Clackz commented
@Fatpandac 不用了，能够有获取大图的方法就足够了