feat(route): add A姐分享 #9027
DIYgod/RSSHub pull request #9028
Opened 2022-02-08 15:28 UTC by zhenhappy

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/abskoop
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [ ] Documentation
  - [ ] CN
  - [ ] EN
- [ ] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] 日期和时间 date and time
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

## 说明 / Note

2022-02-08 15:34 UTC, TonyRL requested changes
Please use v2 script standard https://github.com/DIYgod/RSSHub/discussions/8236
docs: https://docs.rsshub.app/joinus/script-standard.html

2022-02-09 12:02 UTC, TonyRL requested changes

2022-02-09 12:02 UTC, TonyRL commented on lib/v2/abskoop/index.js
> +                item.pubDate = parseDate($detail('article time').attr('datetime'), 'YYYY-MM-DD HH:mm:ss');
Timezone seems wrong. Please check Vercel's output.

2022-02-09 13:04 UTC, zhenhappy commented on lib/v2/abskoop/index.js
> +                item.pubDate = parseDate($detail('article time').attr('datetime'), 'YYYY-MM-DD HH:mm:ss');
Fixed timezone error

2022-02-09 13:43 UTC, zhenhappy commented on lib/v2/abskoop/index.js
> +                item.pubDate = parseDate($detail('article time').attr('datetime'), 'YYYY-MM-DD HH:mm:ss');
Fixed timezone error

2022-02-10 09:24 UTC, zhenhappy commented on lib/v2/abskoop/index.js
> +                item.pubDate = parseDate($detail('article time').attr('datetime'), 'YYYY-MM-DD HH:mm:ss');
Timezone was fixed

2022-02-22 13:49 UTC, TonyRL requested changes

2022-02-22 13:49 UTC, TonyRL commented on lib/v2/abskoop/maintainer.js
> +    '/abskoop': ['zhenhappy'],
```suggestion
    '/': ['zhenhappy'],
```

2022-02-23 07:43 UTC, zhenhappy commented on lib/v2/abskoop/maintainer.js
> +    '/abskoop': ['zhenhappy'],
Fixed

2022-02-23 18:28 UTC, TonyRL requested changes
Missing radar.js

2022-02-24 01:58 UTC, zhenhappy commented
> Missing radar.js

add radar.js

2022-02-24 11:09 UTC, merged