fix(route): JavDB Domain
DIYgod/RSSHub pull request #9085
Opened 2022-02-13 06:58 UTC by Felix2yu

## 该 PR 相关 Issue / Involved issue

Close #9083

## 完整路由地址 / Example for the proposed route(s)

```routes
/javdb/censored/2/2
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [ ] 中文文档 CN
  - [ ] 英文文档 EN
- [x] 全文获取 fulltext
  - [x] 使用缓存 Use Cache
- [x] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [x] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note
javdb7.com域名失效，更换为javdb36.com

2022-02-13 12:18 UTC, TonyRL requested changes

2022-02-13 12:18 UTC, TonyRL commented on lib/v2/javdb/utils.js
> +        const domain = ctx.query.domain ?? 'javdb36.com';
```suggestion
        const domain = ctx.query.domain ?? 'javdb.com';
```

2022-02-13 16:28 UTC, Felix2yu commented
之前在 https://github.com/DIYgod/RSSHub/pull/7536 有讨论过为什么不用javdb.com，而用javdb7。当时也测过不带后缀的确实不行，现在测了下javdb.com也能获取了。

2022-02-13 16:39 UTC, TonyRL commented
Please also update the [docs](https://docs.rsshub.app/multimedia.html#javdb) stated that the route will use `javdb.com` by default (instead of `javdb7.com`)

2022-02-13 17:00 UTC, merged

2022-02-19 11:46 UTC, JamYiz commented
修正后的路由似乎很容易触发反爬，一共测试了三个自建站点，均返回Response code 403 (Forbidden)，短时间内路由便失效

2022-02-19 13:19 UTC, Felix2yu commented
你可以最后加上 ?domain=javdb36.com，比主站成功率高很多。
参考 [文档](https://docs.rsshub.app/multimedia.html#javdb)