对JavBus的一点处理
DIYgod/RSSHub pull request #9205
Opened 2022-02-26 02:51 UTC by lychichem

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)
/javbus/.*

```routes
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [ ] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note
提交此PR的原因：JavBus被tls rst待遇，不上vpn或者反代的话，比较难以完整体验该路由，因此换了一个目前只观测到了DNS污染的备用域名，使用该域名可以在仅添加了hosts的系统下获得完整体验。好处是能够在客户端节省一定的VPN流量。
当然也有一个问题，就是如果开了这个头，是不是每次javbus域名被tls rst都得开个PR换新域名。所以我比较犹豫，这里先开成draft，请各位大佬定夺。

2022-02-26 13:39 UTC, TonyRL commented
Consider using the same approach as JavDB which takes a `domain` parameter and uses it instead of pre-defined domain

2022-02-26 14:35 UTC, lychichem commented
> Consider using the same approach as JavDB which takes a `domain` parameter and uses it instead of pre-defined domain

我注意到了JavDB的处理方式，但没学会怎么用，毕竟我没有计算机相关背景，不太能看得懂，现在只能按这样临时自己部署用用……

2022-03-10 09:37 UTC, SukkaW requested changes
https://github.com/DIYgod/RSSHub/pull/9205#issuecomment-1052127619

https://github.com/DIYgod/RSSHub/blob/6286bee55d9eb58d470565c98274fbf35b2dfae2/lib/v2/javdb/utils.js#L7

2022-03-12 02:47 UTC, closed without merging

2022-03-12 02:59 UTC, lychichem commented
> [#9205 (comment)](https://github.com/DIYgod/RSSHub/pull/9205#issuecomment-1052127619)
> 
> https://github.com/DIYgod/RSSHub/blob/6286bee55d9eb58d470565c98274fbf35b2dfae2/lib/v2/javdb/utils.js#L7

虽然知道这句是关键但不知道怎么加，还是先close吧