feat: add ielts
DIYgod/RSSHub pull request #9217
Opened 2022-02-28 03:16 UTC by zenxds

## 该 PR 相关 Issue / Involved issue

[Close #](https://github.com/DIYgod/RSSHub/issues/9094)

## 完整路由地址 / Example for the proposed route(s)

```routes
/ielts
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [x] 新的路由 New Route
  - [x] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [x] 文档说明 Documentation
  - [x] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [x] 可以解析 Parsed
  - [x] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [x] `Puppeteer`

## 说明 / Note

2022-02-28 05:37 UTC, SukkaW requested changes
Please remove the modification of eslint configuration.

2022-02-28 06:09 UTC, zenxds commented
> Please remove the modification of eslint configuration.

Done.

2022-02-28 14:38 UTC, TonyRL requested changes

2022-02-28 14:38 UTC, TonyRL commented on lib/v2/ielts/radar.js
> +        '.': [
```suggestion
    'neea.cn': {
        _name: 'IELTS雅思',
        ielts: [
```

2022-03-01 01:17 UTC, TonyRL commented on lib/v2/ielts/radar.js
> +                title: '雅思最新消息',
```suggestion
                title: '最新消息',
```
Title here should match the H3 header of the docs

2022-03-01 02:23 UTC, merged