增加了六个美国博物馆的展讯
DIYgod/RSSHub pull request #9451
Opened 2022-04-02 19:02 UTC by chazeon

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [x] 新的路由 New Route
  - [x] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [x] 文档说明 Documentation
  - [x] 中文文档 CN
  - [x] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note

增加了六个美国博物馆的展讯

2022-04-03 13:44 UTC, TonyRL commented on lib/v2/brooklynmuseum/exhibitions.js
> +        title: `Brooklyn Museum - Exhibitions`,
```suggestion
        title: 'Brooklyn Museum - Exhibitions',
```

2022-04-03 13:44 UTC, TonyRL commented on lib/v2/jewishmuseum/exhibitions.js
> +    const link = `https://thejewishmuseum.org/exhibitions`;
```suggestion
    const link = 'https://thejewishmuseum.org/exhibitions';
```

2022-04-03 13:44 UTC, TonyRL commented on lib/v2/jewishmuseum/exhibitions.js
> +        title: `Jewish Museums - Exhibitions`,
```suggestion
        title: 'Jewish Museums - Exhibitions',
```

2022-04-03 13:44 UTC, TonyRL commented on lib/v2/jewishmuseum/exhibitions.js
> +};
There's one empty item in `/jewishmuseum/exhibitions`

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/11386903/161429849-b9c16e9f-d13e-4807-81dc-8bf38c9b9783.png)
</details>

2022-04-03 13:44 UTC, TonyRL commented on lib/v2/jewishmuseum/radar.js
> +                docs: 'http://docs.rsshub.app/en/travel.html#the-jewish-museum',
```suggestion
                docs: 'https://docs.rsshub.app/en/travel.html#the-jewish-museum',
```

2022-04-03 13:44 UTC, TonyRL commented on lib/v2/metmuseum/exhibitions.js
> +        insecureHTTPParser: true,
```suggestion
```
https://github.com/sindresorhus/got/issues/1794#issuecomment-886050367

2022-04-03 13:44 UTC, TonyRL commented on lib/v2/mcachicago/exhibitions.js
> +        title: `MCA Chicago - Exhibitions`,
```suggestion
        title: 'MCA Chicago - Exhibitions',
```

2022-04-03 13:44 UTC, TonyRL commented on lib/v2/mcachicago/exhibitions.js
> +    const link = `https://mcachicago.org/exhibitions`;
```suggestion
    const link = 'https://mcachicago.org/exhibitions';
```

2022-04-03 13:44 UTC, TonyRL commented on lib/v2/metmuseum/exhibitions.js
> +        pubDate: result.startDate,
```suggestion
        pubDate: parseDate(result.startDate),
```
docs: https://docs.rsshub.app/en/joinus/pub-date.html

2022-04-03 13:44 UTC, TonyRL commented on lib/v2/newmuseum/exhibitions.js
> +            link = `https://www.newmuseum.org/exhibitions/`;
```suggestion
            link = 'https://www.newmuseum.org/exhibitions/';
```

2022-04-03 13:44 UTC, TonyRL commented on lib/v2/newmuseum/exhibitions.js
> +        title: `New Museum - Exhibitions`,
```suggestion
        title: 'New Museum - Exhibitions',
```

2022-04-03 14:25 UTC, TonyRL requested changes

2022-04-03 14:25 UTC, TonyRL commented on lib/v2/guggenheim/exhibitions.js
> +}
```suggestion
const { parseDate} = require('@/utils/parse-date');
```
docs: https://docs-rsshub.pages.dev/en/joinus/pub-date.html

2022-04-03 14:25 UTC, TonyRL commented on lib/v2/guggenheim/exhibitions.js
> +    const data = context.bootstrap;
```suggestion
    const data = JSON.parse(cheerio.load(response.data)('#app-js-extra').html().match(/var bootstrap = (.*);\svar navFooter/)[1]);
```
no need to use `vm`

2022-04-03 14:25 UTC, TonyRL commented on lib/v2/guggenheim/exhibitions.js
> +            pubDate: ex.dates ? parseDate(ex.dates.start) : null,
```suggestion
            pubDate: ex.dates ? parseDate(`${ex.dates.start.month} ${ex.dates.start.day}, ${ex.dates.start.year}`, 'MMMM D, YYYY') : null,
```

2022-04-03 14:25 UTC, TonyRL commented on lib/v2/guggenheim/exhibitions.js
> +        title: `The Guggenheim Museums and Foundation - Exhibitions`,
```suggestion
        title: 'The Guggenheim Museums and Foundation - Exhibitions',
```

2022-04-03 14:25 UTC, TonyRL commented on lib/v2/guggenheim/exhibitions.js
> +    const link = `https://www.guggenheim.org/exhibitions`;
```suggestion
    const link = 'https://www.guggenheim.org/exhibitions';
```

2022-04-03 19:48 UTC, chazeon commented
@TonyRL **About the `insecureHTTPParser`**: I used to get the `HPE_INVALID_HEADER_TOKEN` error, and adding this option indeed fix the error. Now even after removing this option this error no longer appears. Do you have any idea why I got `HPE_INVALID_HEADER_TOKEN` earlier?

2022-04-03 20:10 UTC, TonyRL commented
> @TonyRL **About the `insecureHTTPParser`**: Yesterday I used to get the `HPE_INVALID_HEADER_TOKEN` error, and adding this `insecureHTTPParser` option indeed fix the error. Today even after removing this option this error no longer appears. Do you have any idea why I got `HPE_INVALID_HEADER_TOKEN` earlier?

There are some replies that reported it's an issue with Incapsula CDN in https://github.com/nodejs/node/issues/27711#issuecomment-553122893 and above, though one below said it's not just Incapsula.

Coincident?
```shell
$ nslookup www.metmuseum.org
Server:         192.168.1.250
Address:        192.168.1.250#53

Non-authoritative answer:
www.metmuseum.org       canonical name = bhpijji.x.incapdns.net.
Name:   bhpijji.x.incapdns.net
Address: 45.60.83.20
```

2022-04-03 21:02 UTC, chazeon commented
> > @TonyRL **About the `insecureHTTPParser`**: Yesterday I used to get the `HPE_INVALID_HEADER_TOKEN` error, and adding this `insecureHTTPParser` option indeed fix the error. Today even after removing this option this error no longer appears. Do you have any idea why I got `HPE_INVALID_HEADER_TOKEN` earlier?
> 
> There are some replies that reported it's an issue with Incapsula CDN in [nodejs/node#27711 (comment)](https://github.com/nodejs/node/issues/27711#issuecomment-553122893) and above, though one below said it's not just Incapsula.
> 
> Coincident?
> 
> ```shell
> $ nslookup www.metmuseum.org
> Server:         192.168.1.250
> Address:        192.168.1.250#53
> 
> Non-authoritative answer:
> www.metmuseum.org       canonical name = bhpijji.x.incapdns.net.
> Name:   bhpijji.x.incapdns.net
> Address: 45.60.83.20
> ```

Good to know. This is likely to be the cause.

2022-04-03 21:11 UTC, chazeon commented
I think all the issues have been resolved. Please take another look.

2022-04-04 13:22 UTC, TonyRL commented on lib/v2/jewishmuseum/exhibitions.js
> +            item: '#current article.exhibition, #upcoming article.exhibition, #past article.exhibition',
```suggestion
            item: '#current article.exhibition, #upcoming article, #past article.exhibition',
```
upcoming exhibition isn't shown

2022-04-04 13:22 UTC, TonyRL commented on lib/v2/guggenheim/exhibitions.js
> +            pubDate: ex.dates ? parseDate(ex.dates.start, 'MMMM D, YYYY') : null,
Built-in `parseDate()` accept `Date` object or a date string but not a custom JSON
```suggestion
            pubDate: ex.dates ? parseDate(`${ex.dates.start.month} ${ex.dates.start.day}, ${ex.dates.start.year}`, 'MMMM D, YYYY') : null,
```

2022-04-04 13:54 UTC, TonyRL reviewed
It seems their Incapsula WAF has already blocked me

2022-04-04 13:54 UTC, TonyRL commented on docs/en/travel.md
> +    :paramsDesc="['state of the exhibition: `current`，`past`, or `upcoming`, the default value is `current`']"
```suggestion
    :paramsDesc="['state of the exhibition: `current`，`past`, or `upcoming`, the default value is `current`']" anticrawler="1"
```

2022-04-04 13:54 UTC, TonyRL commented on docs/travel.md
> + :paramsDesc="['展览进行的状态：`current` 对应展览当前正在进行，`past` 对应过去的展览，`upcoming` 对应即将举办的展览，默认为 `current`']"
```suggestion
 :paramsDesc="['展览进行的状态：`current` 对应展览当前正在进行，`past` 对应过去的展览，`upcoming` 对应即将举办的展览，默认为 `current`']" anticrawler="1"
```

2022-04-04 14:31 UTC, merged