修复观察网、CCTV、CNBeta、新华网作者、时间取值，新增国家广播电视总局及参考消息源
DIYgod/RSSHub pull request #9541
Opened 2022-04-15 03:25 UTC by yuxinliu-alex

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```
/guancha/review
/cctv/china
/cnbeta
/cankaoxiaoxi/news/military_news
/news/whxw
/nrta/news/important
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [x] 新的路由 New Route
  - [x] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [ ] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [x] 可以解析 Parsed
  - [x] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note

2022-04-15 11:45 UTC, TonyRL requested changes
Please do not squash route fixes and new routes into one PR.

2022-04-15 11:45 UTC, TonyRL commented on lib/routes/thepaper/utils.js
> +const date = require('@/utils/date');
Please use `parseDate` from `@/utils/parse-date`

2022-04-15 11:45 UTC, TonyRL commented on lib/routes/thepaper/utils.js
> +        const res = await got.get(link);
```suggestion
        const res = await got(link);
```

2022-04-15 11:45 UTC, TonyRL commented on lib/routes/thepaper/utils.js
> +                const cache = await ctx.cache.get(itemUrl);
Please use `ctx.cache.tryGet(k, v)` instead.

2022-04-15 11:45 UTC, TonyRL commented on lib/routes/thepaper/utils.js
> +                return Promise.resolve(single);
```suggestion
                return single;
```

2022-04-15 11:45 UTC, TonyRL commented on lib/v2/cankaoxiaoxi/index.js
> +const utils = require('@/v2/icac/utils');
Do not use utilities for other routes

2022-04-15 11:45 UTC, TonyRL commented on lib/v2/cankaoxiaoxi/index.js
> +// module.exports = async (ctx) => {
Please remove commented code of another route

2022-04-15 11:45 UTC, TonyRL commented on lib/v2/nrta/news.js
> +    currentUrl = `${rootUrl}/col/col${categories[category]}/index.html`;
Use `const` if `currentUrl` will not be reassigned

2022-04-15 11:45 UTC, TonyRL commented on lib/v2/nrta/router.js
> +module.exports = function (router) {
This route should be added into `lib/v2/gov` as `.gov`-related website are added there.

2022-04-18 07:21 UTC, closed without merging

2022-04-18 12:00 UTC, yuxinliu-alex commented
> Please do not squash route fixes and new routes into one PR.

seperate the fixes into #9561 #9562 #9559 #9563,

seperate the new routes into #9566 #9564 .

Best