add(route)北极星光伏
DIYgod/RSSHub pull request #9542
Opened 2022-04-15 06:17 UTC by 1065464173

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
https://guangfu.bjx.com.cn/:type?
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [ ] 新的路由 New Route
  - [x] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [x] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note

2022-04-15 11:25 UTC, TonyRL requested changes
Missing `lib/v2/bjxgf/router.js`

2022-04-15 11:25 UTC, TonyRL commented on assets/radar-rules.js
> +    'guangfu.bjx.com.cn': { _name: '北极星光伏', '.': [{ title: '分类', docs: 'https://docs.rsshub.app/others.html#bei-ji-xing-guang-fu', source: ['/:type', '/'], target: '/bjxgf/:type?' }] },
Do not add radar rules here.
You should add the rules in `lib/v2/bjxgf/radar.js`

2022-04-15 11:25 UTC, TonyRL commented on docs/other.md
> +
Missing H3 heading

2022-04-15 11:28 UTC, TonyRL commented
I would recommend using `bjx` instead of `bjxgf`

2022-04-15 11:50 UTC, 1065464173 commented
> Missing `lib/v2/bjxgf/router.js`

Found it works without `lib/v2/bjxgf/router.js`,amazing!!

> I would recommend using `bjx` instead of `bjxgf`

Thinks  for your advice.  finding it already exists in `lib/routers/` by others.
Should I put it together in v2 ...?? （Stupidly asked）

--- 
I'll push it in right rules tomorrow！

2022-04-15 11:55 UTC, TonyRL commented
> Thinks for your advice. finding it already exists in `lib/routers/` by others. Should I put it together in v2 ...?? （Stupidly asked）
> 
You can put it together if you want. If you don't, I will do it before merging.

2022-04-23 11:16 UTC, merged

2024-06-19 01:12 UTC, fucao commented
想要的是北极星风电网，不是光伏网