增加微语简报源
DIYgod/RSSHub pull request #9577
Opened 2022-04-19 04:34 UTC by x2009again

## 完整路由地址 / Example for the proposed route(s)

/yunspe/newsflash 

## 说明 / Note
增加微语简报源

2022-04-19 12:36 UTC, TonyRL requested changes
New routes should follow [v2 standard](https://docs.rsshub.app/joinus/script-standard.html)

2022-04-19 16:32 UTC, x2009again commented
> New routes should follow [v2 standard](https://docs.rsshub.app/joinus/script-standard.html)

New routes for v2 standard have been added.

2022-04-19 16:43 UTC, TonyRL reviewed
Please remove changes on
`lib/router.js`
`lib/routes/yunspe/newsflash.js`

2022-04-20 06:05 UTC, x2009again commented
> Please remove changes on `lib/router.js` `lib/routes/yunspe/newsflash.js`

ok

2022-04-20 13:54 UTC, TonyRL commented on lib/v2/yunspe/newsflash.js
> +            Referer: `https://www.yunspe.com/newsflashes`,
```suggestion
        url: 'https://www.yunspe.com/wp-json/b2/v1/getNewsflashesList',
        headers: {
            Referer: 'https://www.yunspe.com/newsflashes',
```

2022-04-20 13:54 UTC, TonyRL commented on lib/v2/yunspe/newsflash.js
> +        link: `https://www.yunspe.com/wp-json/b2/v1/getNewsflashesList`,
```suggestion
        title: '微语简报',
        link: 'https://www.yunspe.com/newsflashes/微语简报',
```

2022-04-20 13:54 UTC, TonyRL commented on docs/new-media.md
> +
Missing H3 heading
```suggestion
## 云奇网

### 微语简报
```

2022-04-20 13:54 UTC, TonyRL commented on lib/v2/yunspe/radar.js
> +        _name: '微语简报',
```suggestion
        _name: '云奇网',
```

2022-04-20 13:54 UTC, TonyRL commented on lib/v2/yunspe/radar.js
> +                source: '/',
```suggestion
                source: ['/newsflashes/微语简报', '/newsflashes', '/'],
```

2022-04-20 14:10 UTC, TonyRL commented on lib/v2/yunspe/newsflash.js
> +    });
```suggestion
    const out = data.map((item) => {
        const link = item[0].link;
        const date = item[0]._date.match(/datetime="(.*)" itemprop/)[1];
        const title = item[0].title.replace('【微语简报】', '');
        const description = item[0].content
            .substring(item[0].content.indexOf('【今日简报】') + 6)
            .replace(/(\d*\.\s)|(【)/g, '<br>$1$2')
            .substring(4);

        const single = {
            title,
            link,
            pubDate: timezone(parseDate(date, 'YYYY-M-D H:mm:ss'), +8),,
            description,
        };

        return single;
    });
```

2022-04-21 13:42 UTC, TonyRL commented
https://github.com/DIYgod/RSSHub/pull/9577#discussion_r854162208
The link here should not be the API link

2022-04-21 15:18 UTC, merged