feat(utils): 增加微信公众号文章音频部分处理逻辑
DIYgod/RSSHub pull request #9674
Opened 2022-05-01 07:29 UTC by rpsh

## 该 PR 相关 Issue / Involved issue
无相关 issue
Close #

## 完整路由地址 / Example for the proposed route(s)
```route
/wechat/feeddd/6131e1401269c358aa0e1867
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [ ] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note
- 增加微信公众号文章中音频部分处理逻辑

2022-05-02 18:45 UTC, Rongronggg9 requested changes

2022-05-02 18:45 UTC, Rongronggg9 commented on lib/utils/wechat-mp.js
> +        const voiceInfo = detectVoiceInfo(rootHtml);
Please do not aggressively match the whole HTML, but firstly using cheerio to select that part may contain these resources before performing matching.

2022-05-02 18:45 UTC, Rongronggg9 commented on lib/utils/wechat-mp.js
> +            const originalVoiceInfo = detectVoiceInfo(originalResponse.data);
Please do not aggressively match the whole HTML, but firstly using cheerio to select that part may contain these resources before performing matching.

2022-05-02 18:45 UTC, Rongronggg9 commented on lib/utils/wechat-mp.js
> +    });
```suggestion
    // fix single voice article
    // example: https://mp.weixin.qq.com/s/FY6yQC_e4NMAxK0FBr6jwQ
    if (voiceInfo) {
    	$('#voice_parent').each((_, voice) => {
        	voice = $(voice);
            voice.html(renderAudio(voiceInfo));
    	});
    }
```

2022-05-02 18:45 UTC, Rongronggg9 commented on lib/utils/wechat-mp.js
> +        const sourceUrl = detectSourceUrl(rootHtml);
Please do not aggressively match the whole HTML, but firstly using cheerio to select that part may contain these resources before performing matching.

2022-05-02 18:45 UTC, Rongronggg9 commented on lib/utils/wechat-mp.js
> +        const matchs = script.html().match(/document\.getElementById\('(?:js_image_desc|js_audio_desc)'\)\.innerHTML = (?:'|")(.*)(?:'|")\.replace/);
```suggestion
        const matchs = script.html().match(/document\.getElementById\('(?:js_image_desc|js_audio_desc)'\)\.innerHTML = ['"](.*)['"]\.replace/);
```

2022-05-02 18:45 UTC, Rongronggg9 commented on lib/utils/wechat-mp.js
> +        item.enclosure_url = `https://res.wx.qq.com/voice/getvoice?mediaid=${voiceInfo.voiceId}`;
Please do not write a URL twice.

2022-05-02 18:45 UTC, Rongronggg9 commented on lib/utils/wechat-mp.js
> +        return `<audio controls="controls" preload="auto" duration="${options.duration || ''}"  style="width:100%" src="https://res.wx.qq.com/voice/getvoice?mediaid=${options.voiceId}" title="${optio
Please do not write a URL twice.

2022-05-02 19:03 UTC, Rongronggg9 requested changes

2022-05-02 19:03 UTC, Rongronggg9 commented on lib/utils/wechat-mp.js
> +    const matchs2 = html.match(/getXmlValue\('hd_head_img.DATA'\) \|\| '' : '([^']+)'/);
```suggestion
    const matchs2 = html.match(/getXmlValue\('hd_head_img.DATA'\) *\|\| *'' *: *'([^']+)'/);
```
To make it more adaptive.

2023-03-19 20:56 UTC, DIYgod commented
pr 时间过长，将先被关闭，如果还有疑问可以随时在下面继续讨论

2023-03-19 20:56 UTC, closed without merging