tapechat
DIYgod/RSSHub pull request #9684
Opened 2022-05-03 09:47 UTC by ch1y4

## 该 PR 相关 Issue / Involved issue

无

## 完整路由地址 / Example for the proposed route(s)

```routes
/tapechat/dynamic/:userId/:pagesize?
```

## 新 RSS 检查列表 / New RSS Script Checklist

- [x] 新的路由 New Route
  - [ ] 跟随 [[v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html)](https://docs.rsshub.app/joinus/script-standard.html) Follows [[v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)](https://docs.rsshub.app/en/joinus/script-standard.html)
- [x] 文档说明 Documentation
  - [x] 中文文档 CN
  - [ ] 英文文档 EN
- [x] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] [[日期和时间](https://docs.rsshub.app/joinus/pub-date.html)](https://docs.rsshub.app/joinus/pub-date.html) [[date and time](https://docs.rsshub.app/en/joinus/pub-date.html)](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [x] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note

2022-05-03 15:41 UTC, Rongronggg9 requested changes
A new route should follow the v2 standard. Otherwise, it would probably not be accepted.

Your master branch is not clean, please close this PR, create a new branch based on the **upstream** master then cheery-pick your commits. Afterward, create a new PR from that branch.
Of course, you can do it on your master branch in situ if you know how to. In this way, you don't need to create a new PR. But it is not recommended to create a PR from the master branch.

2022-05-03 15:55 UTC, Rongronggg9 requested changes

2022-05-03 15:55 UTC, Rongronggg9 commented on lib/pr.md
> +<!--
Please do not copy and/or modify the PR template. You just need to fill in it while creating a PR on github.

2022-05-03 15:55 UTC, Rongronggg9 commented on lib/routes/tapechat/tapechat.js
> +                description: `<meta name="referrer" content="no-referrer">${item.item.txtContent}<br>${images.join('')}`,
```suggestion
                description: `${item.item.txtContent}<br>${images.join('')}`,
```
`description` is not a web page, `<meta>` tags won't work.
You don't need to apply a no-referer policy on images, RSSHub will do it automatically.

2022-05-03 15:55 UTC, Rongronggg9 commented on lib/routes/tapechat/tapechat.js
> +                    images.push(`<img src=${x}>`);
```suggestion
                    images.push(`<img src="${x}">`);
```

2022-05-03 15:55 UTC, Rongronggg9 commented on lib/routes/tapechat/tapechat.js
> +        description: String(description),
Why force type conversion?

2022-05-03 15:55 UTC, Rongronggg9 commented on lib/routes/tapechat/tapechat.js
> +            Authorization: String(token),
Why force type conversion?

2022-05-03 15:55 UTC, Rongronggg9 commented on lib/routes/tapechat/tapechat.js
> +                    const x = v.substring(10);
What's this?

2022-05-03 15:55 UTC, Rongronggg9 commented on lib/routes/tapechat/tapechat.js
> +                title: '',
```suggestion
                title: item.item.txtContent,
```

2023-03-19 20:54 UTC, closed without merging

2023-03-19 20:55 UTC, DIYgod commented
pr 时间过长，将先被关闭，如果还有疑问可以随时在下面继续讨论