fix route pianyuan, add  pianyuan/search
DIYgod/RSSHub pull request #9721
Opened 2022-05-07 15:04 UTC by jerry1119

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/pianyuan/index
/pianyuan/index/mv
/pianyuan/index/tv
/pianyuan/indexers/pianyuan/results/search/
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [ ] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note
更新到片源网新地址
现在只能通过coockie来访问
规范rss输出格式,增加磁链输出
新增搜索路由,改动原路由地址

2022-05-07 16:01 UTC, TonyRL commented on lib/routes/pianyuan/utils.js
> +            const link = url.resolve(link_base, e);
`url.resolve` is deprecated. Please use [`URL`](https://nodejs.org/api/url.html#the-whatwg-url-api) instead.

2022-05-07 16:01 UTC, TonyRL commented on lib/routes/pianyuan/utils.js
> +            return Promise.resolve(single);
```suggestion
            return single;
```

2022-05-07 16:01 UTC, TonyRL commented on lib/routes/pianyuan/search.js
> +            return Promise.resolve(single);
```suggestion
            return single;
```

2022-05-07 20:54 UTC, TonyRL commented
The issues mentioned above have not been resolved yet.

2022-05-08 10:10 UTC, Rongronggg9 requested changes

2022-05-08 10:10 UTC, Rongronggg9 commented on lib/routes/pianyuan/utils.js
> +            throw 'pianyuan  is disabled due to the lack of <a href="https://docs.rsshub.app/install/#pei-zhi-bu-fen-rss-mo-kuai-pei-zhi">relevant config</a>';
```suggestion
            throw 'pianyuan is disabled due to the lack of <a href="https://docs.rsshub.app/install/#pei-zhi-bu-fen-rss-mo-kuai-pei-zhi">relevant config</a>';
```

2022-05-08 15:51 UTC, TonyRL commented on docs/multimedia.md
> +<Route author="greatcodeeer jerry1119" example="/pianyuan/index" path="/pianyuan/index/:media?" :paramsDesc="['类别，见下表，默认为首页']" radar="1" rssbud="1"/>
```suggestion
<Route author="greatcodeeer jerry1119" example="/pianyuan/index" path="/pianyuan/index/:media?" :paramsDesc="['类别，见下表，默认为首页']" radar="1" rssbud="1"  selfhost="1"/>
```

2022-05-08 15:51 UTC, TonyRL commented on docs/multimedia.md
> +<Route author="jerry1119" example="/pianyuan/indexers/pianyuan/results/search/api?t=test&q=长津湖" path="/pianyuan/indexers/pianyuan/results/search/" />
```suggestion
<Route author="jerry1119" example="/pianyuan/indexers/pianyuan/results/search/api?t=test&q=长津湖" path="/pianyuan/indexers/pianyuan/results/search/" selfhost="1"/>
```

2022-05-08 15:51 UTC, TonyRL commented on docs/multimedia.md
> +:::
Please add this to `docs/install/README.md` instead

2022-05-08 15:51 UTC, TonyRL commented on lib/routes/pianyuan/app.js
>          title: `片源网`,
```suggestion
        title: '片源网',
```

2022-05-08 15:51 UTC, TonyRL commented on lib/routes/pianyuan/search.js
> +        throw `pianyuan 搜索失败`;
```suggestion
        throw 'pianyuan 搜索失败';
```

2022-05-08 15:51 UTC, TonyRL commented on lib/routes/pianyuan/search.js
> +        title: `片源网`,
```suggestion
        title: '片源网',
```

2022-05-08 15:51 UTC, TonyRL commented on lib/routes/pianyuan/utils.js
> +        throw `pianyuan Cookie已失效`;
```suggestion
        throw 'pianyuan Cookie已失效';
```

2022-05-08 17:00 UTC, merged