fix(route): 9to5/subsite fix selector and refactor to V2
DIYgod/RSSHub pull request #9771
Opened 2022-05-16 17:22 UTC by Fatpandac

## 该 PR 相关 Issue / Involved issue

Close #9766

## 完整路由地址 / Example for the proposed route(s)

```routes
/9to5/mac
/9to5/toys
/9to5/google
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [ ] 新的路由 New Route
  - [X] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [X] 文档说明 Documentation
  - [X] 中文文档 CN
  - [X] 英文文档 EN
- [X] 全文获取 fulltext
  - [X] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [X] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note

2022-05-16 17:31 UTC, Rongronggg9 requested changes

2022-05-16 17:40 UTC, Fatpandac commented on lib/v2/9to5/radar.js
> +                title: 'Toys 分站',
How about `9TO5Toys 分站`

2022-05-16 17:52 UTC, Rongronggg9 requested changes

2022-05-16 17:52 UTC, Rongronggg9 commented on lib/v2/9to5/radar.js
> +                title: 'Toys 分站',
```suggestion
        _name: '9to5',
        '.': [
            {
                title: 'Toys 分站',
```

![](https://user-images.githubusercontent.com/15956627/168653090-5c78eda4-4490-4c23-a2e4-a410c5859ed1.png)

2022-05-16 17:52 UTC, Rongronggg9 commented on lib/v2/9to5/radar.js
> +        _name: '9TO5Mac',
```suggestion
        _name: '9to5',
```

2022-05-16 17:52 UTC, Rongronggg9 commented on lib/v2/9to5/radar.js
> +        _name: '9TO5Google',
```suggestion
        _name: '9to5',
```

2022-05-16 18:12 UTC, Rongronggg9 requested changes
https://github.com/DIYgod/RSSHub/blob/6044b48a901875a0d00c907c4fffcc466597aed6/lib/v2/9to5/subsite.js#L34

```js
        link = `${link}/guides/${ctx.params.tag}/feed/`;
```

https://github.com/DIYgod/RSSHub/runs/6457480046?check_suite_focus=true#step:11:33

2022-05-16 19:01 UTC, Rongronggg9 requested changes

2022-05-17 02:23 UTC, Fatpandac commented on lib/v2/9to5/radar.js
> +                target: '/9to5/toys',
OK

2022-05-17 08:31 UTC, TonyRL commented on lib/v2/9to5/subsite.js
> +        feed.items.splice(0, 10).map((item) =>
```suggestion
        feed.items.splice(0, ctx.query.limit ? parseInt(ctx.query.limit) : 10).map((item) =>
```

2022-05-17 08:38 UTC, Fatpandac commented on lib/v2/9to5/subsite.js
> +        feed.items.splice(0, 10).map((item) =>
thx ♥️

2022-05-17 15:18 UTC, merged