feat(route):add 健康界
DIYgod/RSSHub pull request #9899
Opened 2022-06-05 13:17 UTC by qnloft

## 该 PR 相关 Issue / Involved issue

Close #

## 完整路由地址 / Example for the proposed route(s)

```routes
/healthcare/index
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [x] 新的路由 New Route
  - [x] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [x] 中文文档 CN
  - [ ] 英文文档 EN
- [x] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [x] 可以解析 Parsed
  - [x] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note

健康界-RSS，网站地址：https://www.cn-healthcare.com/

2022-06-05 13:22 UTC, TonyRL requested changes
New route(s) should follow [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html) which will not have any changes to `assets/radar-rules.js` and `lib/router.js`

2022-06-07 08:44 UTC, qnloft commented
> New route(s) should follow [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html) which will not have any changes to `assets/radar-rules.js` and `lib/router.js`

已修改

2022-06-07 09:06 UTC, TonyRL reviewed
Please remove your changes on `assets/radar-rules.js` and `lib/router.js` as it is already done in v2 routes.
I would suggest using the folder name `cn-healthcare` instead of `healthcare` to match the domain name.

2022-06-07 09:06 UTC, TonyRL commented on lib/v2/healthcare/index.js
> +            pubDate: new Date(item.createdate).toUTCString(),
```suggestion
    const name = '健康界 [cn-healthcare]';
    ctx.state.data = {
        // 源标题
        title: name,
        // 源链接
        link: 'https://www.cn-healthcare.com',
        // 源说明
        description: `${name} - RSS`,
        // 遍历此前获取的数据
        item: data.datalist.map((item) => ({
            // 文章标题
            title: item.title,
            // 文章正文
            description: item.content,
            // 文章发布时间
            pubDate: parseDate(item.createdate),
```
docs: https://docs.rsshub.app/joinus/pub-date.html#shi-yong-gong-ju-lei-parse-date

2022-06-07 10:18 UTC, TonyRL reviewed
`lib/routes/healthcare/index.js` should also be removed as it's not being used.

2022-06-07 10:18 UTC, TonyRL commented on lib/v2/cn-healthcare/index.js
> +            description: String(item.content),
```suggestion
            description: item.content,
```

2022-06-07 14:43 UTC, TonyRL commented on docs/new-media.md
> +<Route author="qnloft" example="/healthcare/index" path="/healthcare/index" />
```suggestion
<Route author="qnloft" example="/cn-healthcare/index" path="/cn-healthcare/index" />
```

2022-06-08 03:59 UTC, TonyRL commented on docs/new-media.md
>  |      | zh-hk | zh-tw |
```suggestion
|      | zh-hk | zh-tw |

 </Route>
```

2022-06-08 04:01 UTC, merged