feat(core): anti-hotlink workaround parameters
DIYgod/RSSHub pull request #9984
Opened 2022-06-18 21:10 UTC by Rongronggg9

## 该 PR 相关 Issue / Involved issue

Close #9982
#7187 should NOT be closed before, it is this PR the one that can close it.
https://github.com/DIYgod/RSSHub/pull/9618#issuecomment-1129252158

## 完整路由地址 / Example for the proposed route(s)

```routes
NOROUTE
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [ ] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note

2022-06-19 11:46 UTC, Seeger0216 commented
请尽快merge此pr以解决问题，谢谢。

2022-06-19 18:22 UTC, NeverBehave commented
如果iFrame支持差，那就只保留反代一个处理方法就好了

2022-06-19 18:55 UTC, Rongronggg9 commented
> 如果iFrame支持差，那就只保留反代一个处理方法就好了 遇到类似情况大多数时候都还是要操作

不赞同。
基本上，调用 Qt WebEngine 的阅读器很可能都不能从搭建于 Cloudflare Workers 的反代上拉取大型媒体（即视频），具体原因不明。另一方面，除了自行搭建，目前似乎未见其它提供 drop Referer 的非图片反代服务，而自行搭建最简便经济的方式仍是 Cloudflare Workers。因此，iframe workaround 成为这些阅读器几乎唯一可选的 solution。
从这个角度讲，两种方法是互为补充，不见得 iframe 支持一定差，而反代的支持就一定好。只要阅读器渲染时提供一个大致完整的浏览器环境且不额外过滤元素，就可支持 iframe。许多传统桌面端阅读器应是支持的。文档中的说明仅是基于当今移动端当道的现状而作出，首要目的是将其声明为「专业用户」可尝试的方法，不见得桌面端阅读器就式微，iframe workaround 就应用面窄。

2022-06-19 19:50 UTC, NeverBehave commented
如果非cf worker可以使用，不应该擅自做主认为因为经济实用而大家都会使用这个服务
介于大部分自建本身已经有自己的服务器，多数人可能会选择直接用现有的服务器继续加带反代服务
我更倾向于把这个服务直接纳入rsshub的api一部分，如果情况普遍，可以直接使用现成的token保护，整合也更方便

2022-06-20 02:49 UTC, Rongronggg9 commented
> 如果非cf worker可以使用，不应该擅自做主认为因为经济实用而大家都会使用这个服务

无任何证据证明「非（搭建于）cf worker（上的反代）可以使用」，亦非本人提出之论点。因「未见其它提供 drop Referer 的非图片反代服务」，本人亦懒于对「非（搭建于）cf worker（上的反代）可以使用」之论点进行验证。

本人对搭建于 Cloudflare Workers 的反代的评述是「<ins>简便</ins>经济」，不是「经济实用」。「简便」是首要考虑，鉴于大部分用户的知识储备现状，推断用户会倾向于使用「易于自行搭建」（「简便」，仅需要 copy and paste）之服务，并无不妥；「经济」是次要考虑，鉴于反代是需要消耗大量网络流量，推断用户会倾向于使用无流量限制且每日 100k 次调用内免费（「经济」）之服务，亦无不妥。因此，推断大部分用户会选择 Cloudflare Workers，实无不妥。

> 介于大部分自建本身已经有自己的服务器

阁下已经不当地预设一前提，即「本 PR 的用例是面向自建实例用户」，这是真正的「擅自做主」。本人全不认可这一预设前提。在 Cloudflare Workers 上搭建反代或启用 iframe workaround 所需要之知识储备并不高于自行搭建实例；即使有足够的知识储备，亦不代表必须要拥有自行搭建之实例。阁下之预期前提实属不当。

同时该断言无附上任何可信之统计数据或引文，本人同样可以作出如下断言：

据本人之观察，使用自建实例之用户中，最广大用户是使用他人共享之自建实例；次要的是使用 Heroku 自建之实例；真正使用自己在服务器/VPS 上自建的实例的人是最少。

本人之断言与阁下之断言在可信度上无本质区别。

> 多数人可能会选择直接用现有的服务器继续加带反代服务

这同样是「擅自做主」。在不认同不当之预设前提之基础上，本人仅就该断言本身对等地作出如下论述：

鉴于前一项断言，只有为数最少的自建实例用户是真正拥有服务器（或 VPS，下同），「多数人」已经不能成立。同时，回顾过往 issue，可知拥有自己的服务器与技术水平并无必然联系。RSSHub 是已优化部署方式使之易于在服务器上自行部署，然反代不是。可合理推断，即使对于拥有自己的服务器的用户，亦不能假定他们有大比数拥有足够的知识储备以在自己的服务器/VPS 上搭建反代。反代媒体文件是非常消耗流量，同时一部分 VPS 是传出流量计费、传入流量免费，因此运行 RSSHub 及运行反代在计费流量消耗上是有本质区别。鉴于此，更加不应假定拥有自己的服务器的用户中有大比数不具有流量使用超限之担忧。

> 我更倾向于把这个服务直接纳入rsshub的api一部分

赞同，类似服务（如 [bibliogram](https://sr.ht/~cadence/bibliogram/)）有采用类似方案的。但[「在现在，能做的第一步」](https://github.com/DIYgod/RSSHub/pull/9618#issuecomment-1129167144)是合并这个 PR。

鉴于阁下不能给出合理之论据使本人信服于 iframe workaround 无存留之价值，本人仍不赞同将其移除。即使阁下所提及之 feature 在未来被实现，也不是本 PR 中所有 workaround （在未来）被撤除的理由。首要原因即是「使用自建实例之用户中，最广大用户是使用他人共享之自建实例」及「不应假定拥有自己的服务器/VPS 的用户中有大比数不具有流量使用超限之担忧」。同时，若官方实例（在可预见的未来）因流量担忧不能提供该项服务，即是本 PR 中所有 workaround 不应（在未来）被撤除的最大理由。如果在可预见的，RSSHub 更完善的未来，它们不应被移除，那么现在亦然。

<hr>

务实地考虑，无任何必须移除 iframe workaround 的理由。

2022-06-20 02:56 UTC, NeverBehave commented
这个评论不是为了移除iframe提出的
简便的话应当只需要一个服务即可，本身服务只是进行反向代理的话其实完全可以作为一个api引入，不需要额外单独出来一个第三方个人维护的项目配合
然后的话就是自建服务部分似乎也并没有依据说明数量多少，反代本身默认可以关闭，和protected route相同

2022-06-20 03:29 UTC, Seeger0216 commented
我觉得[Rongronggg9](https://github.com/Rongronggg9)更多说的是解决问题吧，[NeverBehave](https://github.com/NeverBehave)说的是是否有必要通过这种方式解决。我认为这种解决方案是简单而轻便的，且不增加额外成本。[Rongronggg9](https://github.com/Rongronggg9)说得对，作为一个VPS自建使用者，我仅限于能对照说明修改一些变量，其他都是copy&paste，合并PR可以解决这个问题，“移除iframe”和“成为API”并不影响本PR所提供的办法。正如[Rongronggg9](https://github.com/Rongronggg9)所说，这个办法也可以作为节省服务器流量开支的一种办法，是确实有效的。

2022-06-20 03:35 UTC, NeverBehave commented
@Seeger0216 所以你的问题是iframe可以解决的那一类，我说的是新增反代的一类

更有意思的是反代后阅读器不认这个问题，直接现在是不明。

我的意思很简单，要加是没有问题的，都已经写了。但是至少不要在引入新的，可以合并的部分

本来说这些是想分出来RSSProxy来做的，但是确实没有做出来，所以直接和进rsshub我目前也没有意见

2022-06-20 03:41 UTC, Rongronggg9 commented
> 简便的话应当只需要一个服务即可，本身服务只是进行反向代理的话其实完全可以作为一个api引入，不需要额外单独出来一个第三方个人维护的项目配合，而且也不需要额外依赖第三方服务--heroku/vps用户为什么需要额外注册cloudflare之类的服务才能使用呢？这个问题应该需要考虑一下

那么为什么使用他人共享或官方的（假设）关闭了反代 feature 的实例用户就必须跑去注册 Heroku/购买 VPS 自建实例才能用反代呢？另外本人已经特别提出，VPS 用户会有流量超限之担忧。即使是拥有自建实例，也未必就一定有条件启用反代。

> 不需要额外单独出来一个第三方个人维护的项目配合

本质上，这个 PR 做的是让用户自己提供一个反代，只是顺便教用户怎么搭建这样一个反代。不存在什么配合不配合，一切皆是用户自己的选择。这和 cde5d9af45c6e7383f48ab3ced3de60b2e310db1 及 config 中大量存在的 `XX_PROXY` 并无实质不同。也不与 RSSHub 提供的反代服务（假如被实现）有冲突。

> 反代本身默认可以关闭，和protected route相同，足以防范滥用

那么就应该允许用户提供自己的反代。在防范滥用之同时不失功能性。

> 至于流量问题，我同时也认为不是每个人每次都会把自己所有订阅的feed里面的媒体都给点一遍

`<video>` 元素默认不是懒加载，是激进预取。即使特别设置懒加载，也不应假定用户的行为，更不应假定共享自建实例给公众使用的实例维护者会与阁下一样不担忧流量。

> 目前的实现似乎是无差别替换，这样带来的问题也很多

什么问题？没有说明。本身针对媒体文件的反代就是透明的，和一个媒体 CDN 没有本质区别。除了我上面提到的部分阅读器可能不能用 Cloudflare Workers 上面的反代以外，不见得有什么问题。

阁下亦有在 https://github.com/DIYgod/RSSHub/pull/9618#issuecomment-1129167144 中提到 RSSProxy，很显然 RSSProxy 能且只能使用无差别替换。

基本上，接受用户输入，是用户自己选择要替换，只需要作有限度的功能性优化即可，没有必要一定要尽善尽美。

鉴于这些原因。无差别替换并不是一个真正的问题。

2022-06-20 03:56 UTC, Rongronggg9 commented
> 所以你的问题是iframe可以解决的那一类，我说的是新增反代的一类

提醒：几乎所有移动端阅读器都不能渲染 iframe。上下文不能得知所使用的阅读器。

> 更有意思的是反代后阅读器不认这个问题，直接现在是不明。

推测是 Qt WebEngine 不能正确处理 206 状态码返回的媒体文件；又或者是 HTTP/2 的问题。总而言之从 Workers 日志里可以看到 Workers 返回了 HTTP/2 206 而阅读器自己断开了连接。

> 合进去的话就直接整体合并，至少要给到一个官方的途径去做这个事情

这个 PR 已经够大了，再继续增大会增加合并前的维护成本。先合并再作进一步打算没有什么问题。有机会的话我也可以写一个这样的官方反代，但不是在这个 PR 里。

2022-06-20 04:04 UTC, NeverBehave commented
之前的单个proxy的原因主要是因为用wp的网站会有这个hotlink的问题，但是现在很明显已经延伸到更广泛的地方了，目前pr是一个很通用的规则，这个时候既然是在更新添加新的规则了，需要考虑的多一点，这应该也是合理的吧

既然提到了流量问题，也不是所有的源都需要替换，这样为什么不会带来不必要的流量呢？如果真的在乎所谓的问题的话。接着就是替换本身需要维护替换的源的规则，这个替换过程插件是不应该需要担心的，但是作为rsshub的中间件来考虑这个目标又大了一点。rssproxy是可以处理这个情况的人，毕竟他的概念说到底只是rsshub中间件处理层的分离

最后就是这个设定对于共享而言完全可以关闭，而且是在配置之中，共享用户无权设定反代，管理者可以自行选用。对于自建用户来说有条件可以开启。你可以不使用内建的反代，用兼容的，但是官方应该要有一个标准化的可以方便大家直接使用，让需要做更多自定义的开发者方便对照适配

2022-06-20 04:16 UTC, NeverBehave commented
作为一个配合pr的关键性改动我认为有必要联合在一起进行。开分成两个pr后再一起合并也是可以接受的

2022-06-20 05:29 UTC, Rongronggg9 commented
> 目前pr是一个很通用的规则，这个时候既然是在更新添加新的规则了，需要考虑的多一点，这应该也是合理的吧

这颇有以 collaborator 的高要求对待 contributor 的味道了。Contributor 即使全局观再高，首要目标还是不要发生 requested changes 的拉锯战，尽快合并。这就要求避免不必要地提升 PR 复杂度。

我没有在该 PR 中实现，并不代表我未有作出同样之考虑。事实上，正因为我考虑到了，且认为 RSSHub 自带反代和用户自备反代并行不悖，才不考虑在这个 PR 里实现 RSSHub 自带反代。

考虑到庞大 PR 的维护是困难的，且 RSSHub 已经存在庞大 PR 因各种原因被放弃维护而无法合并的先例，这个 PR 的首要目标是解决亟需解决的问题和需求，而不是一个 PR 就 all in one 尽善尽美。这是脚踏实地、逐个击破的做法。

作为维护者，「考虑得多一点」当然合理；但是对于贡献者而言，即使考虑再多，也不愿开一个庞大 PR 的愿望，也是合理的。

> 既然提到了流量问题，也不是所有的源都需要替换，这样为什么不会带来不必要的流量呢？

光是做软件测试的时候，就已经不应当假定用户是善意的了，那么在 production 的时候，就更没有理由这么假定。因此认为实例维护者可能有担忧，是非常 reasonable 的。

> 这个替换过程插件是不应该需要担心的，但是作为rsshub的中间件来考虑这个目标又大了一点。

可能的解决方案是路由给需要被反代的元素加一个 attribute 作为标记，这样中间件就可识别到。这样也 empower 了用户自备反代和 RSSHub 自带反代并行不悖的可能。

> rssproxy是可以处理这个情况的

除非引入更多参数做过滤，RSSProxy 仍然只能无差别替换。

> 最后就是这个设定对于共享而言完全可以关闭，而且是在配置之中，共享用户无权设定反代，管理者可以自行选用。

所以这个 PR 通过用户自备反代的方式，有效地调和了实例维护者对流量使用的担忧、用户的实际需求、潜在的滥用可能三者之间的矛盾，是一个典型的折衷调和，而不是冰冷地把刀子递给实例维护者一刀切。因此确实应当和 RSSHub 自带反代并行不悖。

> 对于自建用户来说有条件可以开启。你可以不使用内建的反代，用兼容的

自建用户可以，那么用他人实例的用户也应该可以自备反代才对，毕竟这是个对实例维护者基本无害的 feature。

> 只是对于这类新加的组件我的态度都是如果可以，直接纳入仓库管理……保证一定程度的风险控制

这个组件做的只是接受用户输入然后做用户指定的事，风险控制的义务自始而终是在用户身上。另一方面，虽然那个项目是我在维护，但我确实没有直接提供可用的反代，而要求用户自行搭建，因此用户自行搭建即已代表用户自愿承担风险。因此，即便从道义上而不是义务上，这个 PR 已经是做到了清除 RSSHub 和我本人的连带责任（那个项目原本是在 description 里提供了我自建的实例的，为此我已经在写抖音路由的时候删掉了）。在文档中提到我那个项目的出发点就和原本已经提到的可用的图片反代的出发点是一致的，都只是为了方便用户。当然我能理解一定的风险控制是合理的，我也不反感实现一个官方反代，但没必要为此过度自缚手脚。

> 这个pr是没有问题的

那么这个 PR 就是 ready to be merged 了。

下次未合并的 PR 没有问题的时候，只是可以从 RSSHub 的全局设计上尽善尽美的时候，还是新开一个 issue 或者 discussion 讨论吧……

2022-06-20 05:58 UTC, NeverBehave commented
噢等一下，你说的是参数进行管理……我一开始还是以为是在配置选项中
构造链接是完全可以控制产生内容的。我觉得还是要考虑一下，和Proxy一样，虽然不需要额外的访问但是会引入无法控制的模板和外链构造（控制所有的媒体内容），是可以被利用的一个问题

2022-06-20 06:26 UTC, NeverBehave requested changes

2022-06-20 06:26 UTC, NeverBehave commented on docs/parameter.md
> +-   `multimedia_hotlink_template`: 用法同 `image_hotlink_template`，但应用于音频和视频。注意：该服务必须跟随跳转、允许反代音频和视频，且必须在反代时丢弃 `Referer` 请求头。[这里有一个符合要求的易于自行搭建的项目](https://github.com/Rongronggg9/rsstt-img-relay/blob/main
我觉得可以做一个尝试，但是要求在`config`中添加对于这个中间件参数的控制 `ALLOW_MULTIMEDIA_HOTLINK_TEMPLATE`，默认为false

如果有需要共享，自建的用户可以自行打开允许用户进行操作

2022-06-20 07:58 UTC, Rongronggg9 commented
> 构造链接是完全可以控制产生内容的。我觉得还是要考虑一下，和Proxy一样，虽然不需要额外的访问但是会引入无法控制的模板和外链构造（控制所有的媒体内容），是可以被利用的一个问题，利用方式和XSS可以很相似，比如合法做一个反代提供内容，在不知情的用户添加使用后在反代处进行修改，这对于一部分只会添加链接的用户来说是不安全的

严格来说，**使用他人共享的实例更加不安全，甚至对官方实例的信任也是相对的，这对不会自建的用户来说不也是不安全的吗？** 包括现在对 `HOTLINK_TEMPLATE` 的说明中**提到 #2769，也从未明示用户风险自担。** `HOTLINK_TEMPLATE` 是不是更加方便了共享实例维护者投毒？所以真的没必要在这个问题上纠结太多，一切都是用户自己的选择。至少我已经做到了明示用户自行搭建，这在道义上已经非常足够了。如果还不够，可以在文档里加一段声明（但是文档里既没有告知用户使用他人共享的实例的风险，也没有对官方实例作免责声明呀 XD）。

替换媒体的危害性根本不大。说句难听的，RSSHub 本来就预设了被抓取的网站可信，而这个预设其实没有道理。被抓取的网站也完全可以在发现有人写了 RSSHub 路由以后偷偷定向投毒，效果可以比恶意反代更恶劣，不仅可以替换媒体，整个网页内容都在源站控制之下，危害岂不是更大？把用反代的选择权交给用户反倒可以规避通过检测 Referer 的媒体投毒（尽管目前没有证据表明有网站这么投毒）。**被抓取的网站明明就是安全环节里最薄弱的那个，明明就是 RSSHub 最大的攻击面，明明就可以搞任何种类的 XSS。这是不是对所有不及时更新 RSSHub 也不关心公告的用户来说都不安全？**`mode=fulltext` 是不是也是有这样的问题？那难道要默认关掉外部网站的抓取，只留一个 `/rsshub/routes` 吗？恐怕不必吧？**用户使用 RSSHub 的时候已经等于明示了对实例及被抓取网站的信任，正如用户填入自定义反代的时候已经等于明示了对反代的信任。**

如果预设被抓取的网站可信，那么也没有必要去担忧用户自己填的反代。RSSHub 的架构并不如同家长制政府，也不存在如同 Apple 的软硬件一般的封闭生态。**用户已经明示了信任，为何还要替用户的信任感到不信任？** 最多作个声明让用户自己小心，也就够了。

> github code scan 也有类似的安全性警告，不过我才意识到原来之前的路由是这样暴露参数的emmmmm

然而这些警告涉及到的代码在 cde5d9af45c6e7383f48ab3ced3de60b2e310db1 就已经有了。

> 你有其他路由有相关情况的例子吗

至少有三个了。抖音、网易新闻、Instagram。可能还有更多。

包括相当热门的微博路由也有视频相关的问题（部分视频锁区，虽可被境外 RSSHub 实例抓取到，但播放时仅中国大陆可播放），这也可以通过自定义一个在中国大陆的反代解决。实际上我开发的 [RSS-to-Telegram-Bot](https://github.com/Rongronggg9/RSS-to-Telegram-Bot) 恰恰遇到了这个问题，因为它为了节省流量永远请求 Telegram DC 自行从媒体 URL 下载媒体，因此即使搭建在中国大陆也根本发不出锁区的微博视频（disclaimer: 这不是我开这个 PR 的 motivation）。

> 由用户定义参数后任意第三方可控输出内容
> 路由级别的处理无所谓，但是到core级别我认为是需要纳入的

怎么在路由层面就可控，到了 core 层面就不是呢？实际上二者并没有本质区别，都是照用户吩咐，办用户要求的事。也没有什么用户会给每个订阅都闲得无聊加上反代，**本质还是由用户精准控制了需要反代的路由。** 充其量也就是做不到精准替换某个元素而已，然 RSSProxy 也做不到啊 XD

> pr没有问题的前提是这个功能rsshub本身也可以做到。路由级别的处理无所谓，但是到core级别我认为是需要纳入的。
> RSShub新添加的特性应该是自己处理完自己可以使用而已。

这个功能本质是修改媒体 URL，至于给它取了个 anti-hotlink 的名字以及加入相关说明只是为了说明常见用例而已，实际应用面并没有窄到只能用来防盗链。上面提到的微博视频的例子就不是一个反防盗链用例（如果 RSSHub 实例不在中国大陆，内置反代就完全不能替代该用例），也可以用于反代被 GFW 阻断的媒体内容。还有更多用例是可以在反代上做一些用户需要的预处理，比如 images.weserv.nl 就是一个绝佳的例子。你不喜欢这个名字的话可以改掉。**本质上这个功能与 RSSHub 自带反代是一个有一定交集但差集也很大的关系。**

这就好比 `tgiv` 参数，也是高度依赖用户输入，也不能直接使用（由 RSSHub 主动发现模板），也可能被 instant view 模板维护者投毒，如果没有现成模板也要用户自己去写一个，也没有达成上述目标，那是不是就应该默认关掉 `tgiv` 这个功能了？

> 加入一个反代的API PR和这个PR本身应该没有任何冲突

是有冲突的，同时维护两个开着的 PR 可能导致其中一个被合并后另一个产生 conflict，所以第一步应该是把「没有问题的」这个 PR 合并。如果在 `anti-hotlink.js` 注入反代 API 提供的媒体 URL，显然必然与该 PR 产生 conflict。

> 如果其他维护者认为没有必要，可以继续合并

实际上我很不愿意指出这一点，即，有 collaborator 权限的人除了 @TonyRL 根本没有任何一个是在近一年内活跃的。所以这里我就仅仅 ping 一下 @TonyRL 了，要是再要求更多 collaborator 来发表意见，恐怕这个 PR 就石沉大海了罢（笑）

另外这个 PR 修复了 #9983 中的一个 bug，我一开始没意识到这是个恶性 bug （让形如 `<video><source src="..."></video>` 的视频直接无法播放）所以也就没有另开 PR，直接在这里顺便修了。如果一定要搁置这个 PR，我就不得不另开一个 PR 去修这个问题了（很显然我不想这么做）。假如我要去写个反代 API，搁置这个 PR 也只会徒增我的工作量而已。

2022-06-20 08:04 UTC, Rongronggg9 commented on docs/parameter.md
> +-   `multimedia_hotlink_template`: 用法同 `image_hotlink_template`，但应用于音频和视频。注意：该服务必须跟随跳转、允许反代音频和视频，且必须在反代时丢弃 `Referer` 请求头。[这里有一个符合要求的易于自行搭建的项目](https://github.com/Rongronggg9/rsstt-img-relay/blob/main
你有你的坚持，我也有我的。可以加一个配置项来控制，但默认值应该是 `true`，理由已经在 https://github.com/DIYgod/RSSHub/pull/9984#issuecomment-1160103859 中讲得非常清楚。要不问问同样有自建实例的 @Seeger0216 觉得有没有必要让它默认关掉？这根本对实例维护者及用户而言从任何一个角度讲都不是一个 anti-feature，为什么要多此一举默认关掉它呢？

一旦选择默认关掉，就又与路由自己注入反代的年代没什么两样了。这个 PR 本就是为了让路由不要自己注入反代，用户也不必自己搭建实例来注入反代而诞生，这么一来这个 PR 所做的努力又有什么意义呢？

2022-06-20 08:10 UTC, NeverBehave commented
> 被抓取的网站明明就是安全环节里最薄弱的那个，明明就是 RSSHub 最大的攻击面，明明就可以搞任何种类的 XSS。这是不是对所有不及时更新 RSSHub 也不关心公告的用户来说都不安全？

是的，之前在解析nextjs的时候就已经有过类似的CVE。现在要开放一个API，但是会带来额外的安全风险。

如果说开放，之前做RSSProxy那个路由的PR，有用户自行加入自己的实例并使用。如果需要用户可以自行选择使用你的PR并部署，没有任何问题

我要求的不过是添加一个控制选项并默认关闭，之前添加审核没有做的事情，可能是流程不完善没有仔细思考的结果，你在这里提出来添加并没有完全考虑过第三方服务这个问题，确实存在，所以这一次也要继续下去吗？

2022-06-20 08:29 UTC, NeverBehave commented on docs/parameter.md
> +-   `multimedia_hotlink_template`: 用法同 `image_hotlink_template`，但应用于音频和视频。注意：该服务必须跟随跳转、允许反代音频和视频，且必须在反代时丢弃 `Referer` 请求头。[这里有一个符合要求的易于自行搭建的项目](https://github.com/Rongronggg9/rsstt-img-relay/blob/main
如果共享实例管理者了解了过程并且决定这个是可以开放的，他们可以在环境变量中打开他们，和其他配置一样

2022-06-20 08:30 UTC, NeverBehave commented on docs/parameter.md
> +-   `multimedia_hotlink_template`: 用法同 `image_hotlink_template`，但应用于音频和视频。注意：该服务必须跟随跳转、允许反代音频和视频，且必须在反代时丢弃 `Referer` 请求头。[这里有一个符合要求的易于自行搭建的项目](https://github.com/Rongronggg9/rsstt-img-relay/blob/main
在这里的各位都是利益相关者，如果问你们有没有必要我觉得结果很明显，那我完全可以说我自己用的路由就没有这些问题，完全没有必要有这个参数，这是不对的。这个和hotlink模板应该是一样，由实例管理者决定

2022-06-20 08:41 UTC, NeverBehave commented on docs/parameter.md
> +-   `multimedia_hotlink_template`: 用法同 `image_hotlink_template`，但应用于音频和视频。注意：该服务必须跟随跳转、允许反代音频和视频，且必须在反代时丢弃 `Referer` 请求头。[这里有一个符合要求的易于自行搭建的项目](https://github.com/Rongronggg9/rsstt-img-relay/blob/main
@Seeger0216 这个是通用参数，对于任何路由，只要在链接后加入就会产生影响。看来很明显对于大部分用户来说他们甚至不知道影响范围……

2022-06-20 08:56 UTC, NeverBehave commented on docs/parameter.md
> +-   `multimedia_hotlink_template`: 用法同 `image_hotlink_template`，但应用于音频和视频。注意：该服务必须跟随跳转、允许反代音频和视频，且必须在反代时丢弃 `Referer` 请求头。[这里有一个符合要求的易于自行搭建的项目](https://github.com/Rongronggg9/rsstt-img-relay/blob/main
@Seeger0216 目前的问题是添加控制本身 @Rongronggg9 是可以接受的，但是默认参数这一点他不认同，这并不是”完美“问题

2022-06-20 09:21 UTC, Seeger0216 commented on docs/parameter.md
> +-   `multimedia_hotlink_template`: 用法同 `image_hotlink_template`，但应用于音频和视频。注意：该服务必须跟随跳转、允许反代音频和视频，且必须在反代时丢弃 `Referer` 请求头。[这里有一个符合要求的易于自行搭建的项目](https://github.com/Rongronggg9/rsstt-img-relay/blob/main
> @Seeger0216 目前的问题是添加控制本身 @Rongronggg9 是可以接受的，但是默认参数这一点他不认同，这并不是”完美“问题。安全风险如果注意到了就不应该忽视，默认关闭作为一个主流防御方案我并不认为有什么问题。这就和捆绑安装默认把捆绑打勾都给你选中是一个道理，你也许觉得捆绑对我来说是好事情，这不意味着所有人都是这样想的

你之所以坚持默认False是因为你觉得这是个安全风险。我支持True是因为我觉得这是个方便的解决方案，只是追求不同罢了吧……

2022-06-20 12:19 UTC, Rongronggg9 commented
> 默认关闭应该是没有副作用的……那这个功能对他们的实例就是一个开放的攻击面，小的话是算力攻击，大的话可以用于投毒，而且无法简单地关闭

默认打开有什么副作用吗？有让现状变得更糟吗？让我来一一驳斥：

### 算力攻击？

既然你对攻击面这么感兴趣，那我就不困了。从我对 RSSHub 的审计来看，我很难相信 RSSHub 没有假定网络上没有什么恶意攻击者。我没有搞过网安，但作为一个稍有网络安全常识的人，我能数出来的攻击面已经有这么多了：

* `mercury-parser` 耗算力也耗流量。`mode=fulltext` 这一功能没有默认关闭，甚至都不能关闭。
* 上一条不仅可以用来对 RSSHub 实例进行 DoS 攻击哦。直接在网上扫几个 RSSHub 实例然后访问 `/rsshub/routes?mode=fulltext` 就可以对 docs.rsshub.app 进行 DoS 攻击了，要不你试试？`mercury-cache` 可没有像路由缓存一样实现缓存锁哦，对同一个 URL 的请求是可以并行发出的哦。（刚刚审计了一下才发现，深感震撼，过几天我会把它修一下。虽然我相信 docs.rsshub.app 可以防住这种攻击）这同样 empower 了利用 RSSHub 对在路由列表里的网站进行 DoS 攻击的可能性。因为带有深入的全文抓取的路由，一旦开启 `mode=fulltext`，流量直接翻倍。
* `api_router.js` 暴露了实例支持的路由列表到 `/api/routes`，攻击者只要遍历一下这个列表，对路由参数随机填入，就可以直接构造攻击了。这个 API 可没有默认关闭哦。结合 `mode=fulltext` 负载直接翻倍。
* RSSHub 在不启用 Redis 缓存的情况下，由于缓存会超限而被 LRU，不用我特别提前一个攻击方法只需要遍历一小部分路由就可以对网络流量和算力产生大量消耗了吧？而在启用了 Redis 缓存的情况下，可以直接 OOM，何况机器内存也是有限的，最终和还是和不启用 Redis 缓存一样。路由缓存根本什么也防不住。
* Docker Compose、npm/yarn、Ansible 等部署方式没有默认关闭 puppeteer。毕竟「不是所有的用户都会订阅这些路由」嘛，怎么不关掉呢？对吧？直接暴力请求用 puppeteer 的路由导致开几百个 Chromium 进程造成的算力消耗是不是高几个数量级？只要接受路由参数输入的 puppeteer 路由全都逃不掉，只要随机构造路由参数就能有效开新的 Chromium 进程，参数对源站是否有效根本不重要。随机构造参数就可以让 cache miss，同时结合上一条的缓存容量问题，根本防不胜防。
* 有些带自定义参数的路由并没有如我习惯的写法一样对 entrypoint 加一个有效期为 `cacheExpire` 的缓存期限，那么只要随便构造一下自定义参数就可以开始攻击了。这样的路由是可以通过 RSSHub 的审查然后被合并的。
* 讲了这么多，把实例配置的 `cacheExpire` 暴露在 `<ttl>` tag 里的危害有多大不用我说了吧？攻击者可以直接挑 ttl 短的实例开搞。实际上这个 tag 根本没有用，[有几个阅读器遵守了呢](https://rssweblog.com/?guid=20070529130637)？不过就算去掉它，response headers 里也还是写得明明白白，为了 HTTP cache 也必须写得明明白白。防不胜防嘛。
* `DEBUG_INFO` 没有默认关闭。给攻击者提供太多信息。
* 错误页显示的 Git hash 根本关不掉，你看要是 RSSHub 或其依赖发了个 Security Advisory 的话会发生什么呢？就连 [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server) 都警告不能设置详细的 `Server` 响应头，RSSHub 虽然不返回 `Server`，可倒是反其道而行之直接把版本信息精细到 Git hash 了。文档里可是一嘴都没提不使用容器部署的风险，更不用说容器还可以逃逸了。
* 要不去看看 GitHub 给 RSSHub 警告了多少个 Dependabot alerts？任何人只要 fork 一下就能看到了。那么多个 high，这么久了，为了不破坏依赖关系和不迁移依赖也没修嘛。

上面提到的攻击面文档里全部都没有做任何警示。这让我很难界定什么是对攻击面的了解足够而自恰，什么是吹毛求疵。

非常显然地，RSSHub 的 principle 里功能性是大于安全性的，不然怎么会有这么多攻击面？假如你说不要引入 breaking change，这就真的可以说明安全性没那么重要嘛。

其实讲这么多也没意思，限制一下 anti-hotlink 模板能填的模板参数数量，再把它整合进 parameter 里减少 cheerio 构建文档树的次数，就直接让它没有什么攻击价值了（等会会做）。

暴露在公网上的 RSSHub 就是一个应用受限的大型肉鸡。要是有攻击者有心，就直接给 RSSHub 开个 PR 给想攻击的网站适配几个路由，等到公网上更新到该版本的 RSSHub 实例足够多了，直接来 DDoS。谁要是无聊到想针对实例本身搞攻击，谁会不想算力和流量攻击双管其下呢？恐怕 anti-hotlink 模板不过是个最菜的攻击方法而已。所以你看到底是一个多无聊的攻击者才会来用 anti-hotlink 模板搞算力攻击呢？

说句难听的，要是把 RSSHub 做得滴水不漏，RSSHub 也就大失吸引力了。这也就是为什么我早就知道了这么多攻击面，却没有去修任何一个。所有攻击面的利用都需要大规模的请求，还不如去文档里加一句「请自建示例的用户一定要套一个 Cloudflare」来得**务实**。

### 用于投毒？

我已经说了，除非 RSSHub 默认关闭对外部网站的抓取，这根本不自恰嘛，都不是一个值得讨论的论点。都是用户自己选择的，又有什么不同嘛。何况这根本不是实例维护者要担忧的事，根本不能由一个用户影响到其他用户，把这个论点放在实例维护者这里是混淆视听。

### 无法简单地关闭？

我已经明确同意加一个开关，我不同意的只是默认关闭。何况上面提到了那么多攻击面是不是也有不能简单关闭的？

<hr>

所以结论非常简单，RSSHub 的口子本来就很大，这个 feature 根本没有把它扩大，根本没什么副作用。然后一定会说「不妨碍做得更好」，这就属于为了反对而反对。除非能够证明 RSSHub 的 principle 不是功能性大于安全性，不然就等于什么也没说。

> 如果说开放，之前做RSSProxy那个路由的PR，有用户自行加入自己的实例并使用。如果需要用户可以自行选择使用你的PR并部署，没有任何问题

这不是我所关心的。我只关心 RSSHub 能不能自恰地合并这个 PR。

> 信任问题的话，我不认为用户使用rsshub交付任何信任在里面，这不过是各取所需的过程，这对于任何网站都是一样的。

不知道你看了上面这么多攻击面还能不能认为用户真的没有交付信任。退一万步讲，如果没有交付信任，为了一个潜在危害性极低（是个 feature 都有潜在危害性）的 feature 把 RSSHub 搞得这么家长制去丢掉功能性何必呢。一方面你说用户没有交付信任，一方面你在到处都是攻击面的情况下对无关紧要的东西说「风险控制」，还是不自恰啊。

> RSSHub要做的事情应该是忠实的转换目标网站到可订阅的形式这件事情

那么假如自定义反代被默认关掉的话，就没有做到「可订阅」了吧？你可能要说视频反代需求小，但图片反代可不是。如果不可订阅，那么忠实又有什么意义。何况你讲来讲去的投毒问题还是绕不开目标网站投毒，外部网站抓取肯定不能被默认关闭，而用户自备反代又没有什么本质区别。

> 之前添加审核没有做的事情，可能是流程不完善没有仔细思考的结果，你在这里提出来添加并没有完全考虑过第三方服务这个问题，确实存在，所以这一次也要继续下去吗？

假如为了不引入 breaking change 不把 `tgiv` 默认关掉，其实也就恰恰说明这些都不是真正的问题。也许又要说「不妨碍做得更好」，那还是请看看前文吧。

> 这个部分可以动的只有管理者，和当前场景明显不一样

所以我还是提了一嘴，「`HOTLINK_TEMPLATE` 是不是更加方便了共享实例维护者投毒」？如果无限制搞「风险控制」，为用户着想，是不是也要 drop 掉这个功能？所以我就说了嘛，用 RSSHub 就是给实例和源站交付信任。

> 我注意的点是目前rsshub的特性需要依赖外部服务才能完成这一点

我已经说过了，这是一个为了折衷调和必然需要的解决方案，即使实现了自带反代也不影响这一点。毕竟「RSSHub要做的事情应该是忠实的转换目标网站到可订阅的形式这件事情」。这个外部服务只是用户自己准备的，严格而言不是「rsshub的特性需要依赖外部服务才能完成」，而是这个特性 empower 了有需要的用户可以让 RSSHub 和外部服务协作。毕竟你要说「rsshub的特性需要依赖外部服务才能完成」的话，路由是不是一个特性（PR title 可是要写 feat 的哦）？要不要依赖外部服务？所以这个 feature 根本没有和 RSSHub 的确切定位有抵触嘛。

2022-06-20 12:32 UTC, Rongronggg9 commented on docs/parameter.md
> +-   `multimedia_hotlink_template`: 用法同 `image_hotlink_template`，但应用于音频和视频。注意：该服务必须跟随跳转、允许反代音频和视频，且必须在反代时丢弃 `Referer` 请求头。[这里有一个符合要求的易于自行搭建的项目](https://github.com/Rongronggg9/rsstt-img-relay/blob/main
> 这并不是”完美“问题。安全风险如果注意到了就不应该忽视

所以我已经证明了这就是「完美」问题，我列出了这么多攻击面，这么多安全风险，你要去修复一下吗？

> 默认关闭作为一个主流防御方案我并不认为有什么问题。这就和捆绑安装默认把捆绑打勾都给你选中是一个道理

RSSHub 的路由也是 feature，也是捆绑的，甚至是强制捆绑。我提到的攻击面也很依赖路由数量的哦。（然后你就会说有计划做成插件，那还是做出来再说吧）

> 你也许觉得捆绑对我来说是好事情，这不意味着所有人都是这样想的

那么我指出来的攻击面，你又怎么解释呢？是个 feature 就会有默认开启和默认关闭，就会有潜在的攻击面，要是无限度地在这里讲默认开启就是捆绑，那以后还是分发空盒好了。

2022-06-20 13:03 UTC, Seeger0216 commented
虽然看不懂技术层面上的东西，但[Rongronggg9](https://github.com/Rongronggg9)的定义是很好理解的，“为了折衷调和必然需要的解决方案”和“完美”的问题。Contributor更关注于功能的实现，而Collaborator更关注于项目的整体性，这无可厚非。我仍支持“这么追求‘完美’恐怕带来的影响就是增大Contributor的压力”这一观点。正如[Rongronggg9](https://github.com/Rongronggg9)所说，“feature 都有潜在危害性”，而且他也指出了按照[NeverBehave](https://github.com/NeverBehave)的理解，会出现数量可观的、比这个安全风险更大的安全风险。没必要因为意识到了可能的安全风险，就让Feature趋近于一种将就状态。建议尽快合并PR。

2022-06-20 15:12 UTC, TonyRL commented on docs/parameter.md
> +-   `multimedia_hotlink_template`: 用法同 `image_hotlink_template`，但应用于音频和视频。注意：该服务必须跟随跳转、允许反代音频和视频，且必须在反代时丢弃 `Referer` 请求头。[这里有一个符合要求的易于自行搭建的项目](https://github.com/Rongronggg9/rsstt-img-relay/blob/main
Please add a flag in `config` to disable these 2 parameters.

2022-06-20 21:05 UTC, Rongronggg9 commented
A benchmark shows the typical load.

```sh
set -x

git checkout c7268a6

time bash -c 'for i in {1..1000}; do curl 2> /dev/null; done'  # baseline

NO_LOGFILES=1 CACHE_TYPE= npm start > /dev/null &
sleep 5
bash -c $'for i in {1..100}; do curl -s \'http://127.0.0.1:1200/test/multimedia\' > /dev/null; done'  # bootstrap
time bash -c $'for i in {1..1000}; do curl -s \'http://127.0.0.1:1200/test/multimedia\' > /dev/null; done'
killall node
sleep 5

NO_LOGFILES=1 CACHE_TYPE= npm start > /dev/null &
sleep 5
bash -c $'for i in {1..100}; do curl -s \'http://127.0.0.1:1200/test/multimedia?image_hotlink_template=${protocol}//${host}${pathname}${search}${hash}&multimedia_hotlink_template=${protocol}//${host}${pathname}${search}${hash}\' > /dev/null; done'  # bootstrap
time bash -c $'for i in {1..1000}; do curl -s \'http://127.0.0.1:1200/test/multimedia?image_hotlink_template=${protocol}//${host}${pathname}${search}${hash}&multimedia_hotlink_template=${protocol}//${host}${pathname}${search}${hash}\' > /dev/null; done'
killall node
sleep 5

git checkout 9a14b63
NO_LOGFILES=1 CACHE_TYPE= npm start > /dev/null &
sleep 5
bash -c $'for i in {1..100}; do curl -s \'http://127.0.0.1:1200/test/multimedia?image_hotlink_template=${protocol}//${host}${pathname}${search}${hash}&multimedia_hotlink_template=${protocol}//${host}${pathname}${search}${hash}\' > /dev/null; done'  # bootstrap
time bash -c $'for i in {1..1000}; do curl -s \'http://127.0.0.1:1200/test/multimedia?image_hotlink_template=${protocol}//${host}${pathname}${search}${hash}&multimedia_hotlink_template=${protocol}//${host}${pathname}${search}${hash}\' > /dev/null; done'
killall node
sleep 5
```

Baseline: 
```console
$ bash -c 'for i in {1..1000}; do curl 2> /dev/null; done'

real    0m5.235s
user    0m3.517s
sys     0m1.742s
```

No template:
```console
$ bash -c $'for i in {1..1000}; do curl -s '\''http://127.0.0.1:1200/test/multimedia'\'' > /dev/null; done'

real    0m9.486s
user    0m4.085s
sys     0m2.038s
```

Template applied (c7268a6, unoptimized):
```console
$ bash -c $'for i in {1..1000}; do curl -s '\''http://127.0.0.1:1200/test/multimedia?image_hotlink_template=${protocol}//${host}${pathname}${search}${hash}&multimedia_hotlink_template=${protocol}//${host}${pathname}${search}${hash}'\'' > /dev/null; done'

real    0m10.167s
user    0m3.924s
sys     0m2.236s
```

Template applied (9a14b63, optimized):
```console
$ bash -c $'for i in {1..1000}; do curl -s '\''http://127.0.0.1:1200/test/multimedia?image_hotlink_template=${protocol}//${host}${pathname}${search}${hash}&multimedia_hotlink_template=${protocol}//${host}${pathname}${search}${hash}'\'' > /dev/null; done'

real    0m9.754s
user    0m4.041s
sys     0m2.117s
```

In conclusion, a DoS attack could hardly take advantage of using hotlink templates.

2022-06-20 21:14 UTC, TonyRL requested changes

2022-06-20 21:14 UTC, TonyRL commented on docs/en/install/README.md
> +`HOTLINK_DISABLE_USER_TEMPLATE`: Prohibit users to provide their custom templates via [Parameters -> Multimedia processing](/en/parameter.html#multimedia-processing), default to `false`
```suggestion
`DISABLE_USER_HOTLINK_TEMPLATE`: Prohibit users to provide their custom templates via [Parameters -> Multimedia processing](/en/parameter.html#multimedia-processing), default to `false`
```

2022-06-21 00:00 UTC, NeverBehave commented
谢谢你提出了这么多意见，说实话第一次有人开始好好看core里面写的历史遗留问题。这些都是没有解决的问题，尤其是并发类的处理完全是没有到位的。我同时也说了，我个人是没有空管理那么多，我现在能做的只有是新进来的pr，如果是新的功能，我们要做的更好一点，以前的伤害不能说没有，但是你也已经说了活跃维护者大部分精力已经投入在了路由整理的方向，而大部分用户目前也并不在乎这些问题，就算他们问题很大

我的PR里面把这一类都归到feature里面，默认这类都是关闭的，有需要的管理者可以自行打开。你也已经看到没有开关并且默认开启带来了很多问题，在当时大家都不觉得是问题，直到后续变成问题。现在我们采取保守一点的方法尝试解决问题。就是这样

2022-06-21 01:43 UTC, NeverBehave commented
Superseded by #9997

没事了，我只能说你被block也是有理由的，比如你的说法方式在这个PR里面变动很多。我也是实在是没有精力和你纠结这个层面的安排，这也是为什么最后我把你的PR修订了做了补充自己提交了。

2022-06-21 01:43 UTC, closed without merging

2022-06-21 01:49 UTC, Rongronggg9 commented
> 比如你的说法方式在这个PR里面变动很多

即使你的断言是真的，这也不是你出尔反尔的理由。

既然你出尔反尔，自相矛盾，让 @TonyRL 和我都落得尴尬，那么我不再会向你展示 `把 parameter 里面的参数都用正常的 payload 跑一遍，用数据告诉你哪些是最没攻击潜力的那些`。我会直接按 Security Policy 办事。本来就是你让我不得不去审计了 RSSHub 的代码来翔实论据反驳你，那么我也不会让审计白费。毕竟，这确实是「风险管理」、避免「算力攻击」，确实和你的目标一致。